<?php
/**
 * @file
 * Install the feature multisite_activity_core
 */

/**
 * hook_install
 */
function multisite_activity_core_install() {
  //Nothing yet
}

/**
 * hook_uninstall
 */
function multisite_activity_core_uninstall() {
  //Nothing yet
}

/*
 * hook_enable
 */
function multisite_activity_core_enable() {
  //Add block in context

}


/*
 * hook_disable
 */
function multisite_activity_core_disable() {

}
