<?php

/**
 * @file
 * Enable and disable functions for the nexteuropa_geojson_feeds feature.
 */

/**
 * Implements hook_enable().
 */
function nexteuropa_geojson_feeds_enable() {
  drupal_set_message(t('The GeoJSON Feeds feature is now active on your site.'));
}
/**
 * Implements hook_disable().
 */
function nexteuropa_geojson_feeds_disable() {
  drupal_set_message(t('The GeoJSON Feeds feature is now disabled on your site.'));
}
