<?php

/*
* hook_enable
*/
function wiki_og_enable() {
  // add elements to contexts
  multisite_drupal_toolbox_add_views_context("communities", "wiki_list");
  //  multisite_drupal_toolbox_add_block_context('communities', 'wiki_list-block_1', 'views', 'wiki_list-block_1', 'sidebar_first');
  multisite_drupal_toolbox_add_content_type_context('communities', 'wiki');
  
  // add wiki content type to newsletters related contents
  multisite_drupal_toolbox_add_content_type_newsletters('wiki');
  
  // override drupal variables defined in core feature
  variable_set('pathauto_node_wiki_pattern', 'community/[node:group_audience]/wiki/[node:title]');
  
  drupal_flush_all_caches();
}




/*
 * Hook disable 
 */
function wiki_og_disable() {
  // Remove block
  multisite_drupal_toolbox_remove_views_context("communities", "wiki_list");
  //multisite_drupal_toolbox_remove_block_context('communities', 'wiki_list-block_1');
  multisite_drupal_toolbox_remove_content_type_context('communities', 'wiki');

  /*** Remove permissions ***/
  multisite_drupal_toolbox_disable_content_type('wiki');
       
  // delete drupal variables
  variable_del('pathauto_node_wiki_pattern');
}
