<?php
/**
 * @file
 * Provides field definition for a Node layer field for maps.
 */

module_load_include('inc', 'node_layer', 'node_layer.formatter');

/**
 * Implements hook_map_layer_build_content().
 *
 * See MapLayerController->buildContent();
 */
function node_layer_map_layer_build_content_alter(&$content, $wrapper, $entity) {

  // Fetches map data from node layer.
  if ($entity->type == 'node_layer') {
    $settings = drupal_json_decode($wrapper->settings->value());

    // Fetches nodes using chosen filters.
    $filters = $settings['node_filters'];
    $nodes = node_layer_fetch_nodes($filters);
    if ($nodes) {
      $items = array();
      foreach ($nodes as $node) {
        $title = $node->title;

        // Prepares the node to render the pop-up using the chosen view mode.
        $node_view = isset($settings['view_mode']) ? node_view($node, $settings['view_mode']) : 'teaser';

        // Gets all the field values.
        $field_items = field_get_items('node', $node, $filters['geofield']);
        $items[] = array(
          'field_items' => $field_items,
          'title' => $title,
          'popup' => drupal_render($node_view),
        );
      }
      $features = node_layer_prepare_features($items);
      $layers[] = array(
        'layer_settings' => $settings,
        'label' => $wrapper->title->value(),
        'features' => $features,
        'id' => map_layer_id($wrapper->title->value()),
      );
      $content['#attached']['js'][] = array(
        'data' => array(
          'node_layers' => $layers,
        ),
        'type' => 'setting',
      );
    }
    return $content;
  }
}

/**
 * Implements hook_map_layer_inline_entity_form().
 *
 * Adds the Node layer custom JavaScript.
 */
function node_layer_ne_map_build_content_alter(&$custom_js) {
  $node_layer_js = base_path() . drupal_get_path('module', 'node_layer') . "/js/node_layer.js?v=" . rand(0, 33333);
  $custom_js[] = $node_layer_js;
  return $custom_js;
}

/**
 * Implements hook_map_layer_inline_entity_form().
 *
 * Extends the inline entity form with node layer specific fields. This is
 * independent from the stand alone node form as defined in
 * node_layer_form_map_layer_form_alter().
 */
function node_layer_map_layer_inline_entity_form_alter(&$entity_form, $settings, $type) {
  if ($type == 'node_layer') {

    // Defines the form elements shared by inline entity and stand alone form.
    $entity_form = node_layer_form_elements($entity_form, $settings);

  }
  return $entity_form;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the stand alone entity form with node layer specific fields. See also
 * inline entity form. Shares  form elements with the inline entity form.
 */
function node_layer_form_map_layer_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['map_layer']->type == 'node_layer') {
    // Defines the form elements shared by inline entity and stand alone form.
    $settings = $form_state['settings'];
    $form = node_layer_form_elements($form, $settings);
  }
}

/**
 * Provides shared form elements.
 *
 * Form elements that are shared by the stand-alone and the inline entity form.
 */
function node_layer_form_elements(&$form, $settings) {

  // Adds pop up fields.
  $form['popup'] = map_layer_form_elements('popup', $settings);

  // Adds clustering fields.
  $form['clustering'] = map_layer_form_elements('clustering', $settings);

  // Adds attribution fields.
  $form['attribution'] = map_layer_form_elements('attribution', $settings);

  // Adds icon fields.
  $form['icon'] = map_layer_form_elements('icon', $settings);

  // Adds a filter fieldset.
  $form['node_filters'] = array(
    '#type' => 'fieldset',
  );

  // Adds map content type filter field.
  $form['node_filters']['map_content_type'] = array(
    '#type' => 'select',
    '#options' => node_layer_get_content_types(),
    '#title' => t('Content type'),
    '#description' => t('Content type that contains the geospatial data'),
    '#default_value' => isset($settings['node_filters']['map_content_type']) ? $settings['node_filters']['map_content_type'] : 0,
  );

  // Provides a geofield selection field to choose in which field to find geo
  // data.
  $geofield_options = array();
  foreach (node_layer_get_content_types() as $key => $content_type) {
    foreach (node_layer_get_geofields($key) as $key => $field) {
      $geofield_options[$key] = $field;
    }
  }

  // @todo make dependent on content type.
  $form['node_filters']['geofield'] = array(
    '#type' => 'select',
    '#options' => $geofield_options,
    '#title' => t('Geofield'),
    '#description' => t('Field that contains the geospatial data'),
    '#default_value' => isset($settings['node_filters']['geofield']) ? $settings['node_filters']['geofield'] : 0,
  );

  // Provides taxonomy term filter fields based on vocabularies.
  $taxonomy_fields = node_layer_get_taxonomy_fields();
  foreach ($taxonomy_fields as $taxonomy_field) {
    if ($taxonomy_field) {
      $field = $taxonomy_field['field'];
      $vocabulary = taxonomy_vocabulary_machine_name_load($taxonomy_field['vocabulary']);
      $options = node_layer_get_taxonomy_term_options($taxonomy_field['vocabulary']);
      $form['node_filters']['terms'][$field] = array(
        '#type' => 'select',
        '#options' => $options,
        '#title' => $vocabulary->name,
        '#multiple' => TRUE,
        '#description' => t('Filter results by @vocab', array('@vocab' => $vocabulary->name)),
        '#default_value' => isset($settings['node_filters']['terms'][$field]) ? $settings['node_filters']['terms'][$field] : 0,
      );
    }
  }

  // Provides node status filter.
  $form['node_filters']['show_unpublished'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show unpublished'),
    '#default_value' => isset($settings['node_filters']['show_unpublished']) ? $settings['node_filters']['show_unpublished'] : 0,
    '#description' => t('Show unpublished nodes in a map'),
  );

  // Allows choosing the view mode for displaying the pop-up.
  // @todo make dependent on content type.
  $entity_info = entity_get_info('node');
  foreach ($entity_info['view modes'] as $key => $view_mode) {
    $view_mode_options[$key] = $view_mode['label'];
  }
  $form['view_mode'] = array(
    '#type' => 'select',
    '#options' => $view_mode_options,
    '#title' => t('Pop-up view mode'),
    '#description' => t('View mode to use for the pop-up'),
    '#default_value' => isset($settings['view_mode']) ? $settings['view_mode'] : 'teaser',
  );
  return $form;
}

/**
 * Populates a list of terms for use in a form api select.
 */
function node_layer_get_taxonomy_term_options($machine_name) {
  $options = array();
  $vid = taxonomy_vocabulary_machine_name_load($machine_name)->vid;
  $options_source = taxonomy_get_tree($vid);
  foreach ($options_source as $item) {
    $key = $item->tid;
    $value = $item->name;
    $options[$key] = $value;
  }
  return $options;
}

/**
 * Implements hook_map_layer_settings_alter().
 *
 * Adds node layer filters to the map layer settings before submitting
 * (saves the specific field values).
 */
function node_layer_map_layer_settings_alter(&$settings, $form_state) {
  if ($form_state['map_layer']->type == 'node_layer') {
    $settings['node_filters'] = array();

    // Adds bundle as node filter.
    $settings['node_filters']['map_content_type'] = $form_state['values']['map_content_type'];

    // Adds geofield as node filter.
    $settings['node_filters']['geofield'] = $form_state['values']['geofield'];

    // Adds terms as node filter.
    $fields = node_layer_get_taxonomy_fields();
    foreach ($fields as $field) {
      $field_name = $field['field'];
      foreach ($form_state['values'][$field_name] as $term) {
        $settings['node_filters']['terms'][$field_name][] = $term;
      }
    }

    // Adds node status as filter.
    $settings['node_filters']['show_unpublished'] = $form_state['values']['show_unpublished'];

    // Adds the chosen view mode to the settings.
    $settings['view_mode'] = $form_state['values']['view_mode'];
  }
  return $settings;
}

/**
 * Provides list of content types that have a geofield.
 */
function node_layer_get_content_types() {
  $geofielded_content_types = array();

  // Fetches all the site's content types.
  $content_types = node_type_get_names();

  // Cycles through all the field of the geofield type to create a list of
  // content types that use that field.
  $fields = field_read_fields(array('type' => 'geofield'));
  foreach ($fields as $key => $field) {
    $instances = field_read_instances(array('field_name' => $key));
    foreach ($instances as $key => $instance) {
      $geofielded_content_types[$instance['bundle']] = $content_types[$instance['bundle']];
    }
  }
  return $geofielded_content_types;
}

/**
 * Finds taxonomy fields in a content type.
 */
function node_layer_get_geofields($bundle) {
  $geofields = array();
  $fields = field_read_instances(array('bundle' => $bundle));
  foreach ($fields as $field) {
    $field_info = field_info_field($field['field_name']);
    if ($field_info['type'] == 'geofield') {
      $geofields[$field['field_name']] = $field['label'];
    }
  }
  return $geofields;
}

/**
 * Provides list of vocabularies in content types with geofield.
 *
 * @todo add entity reference fields.
 */
function node_layer_get_taxonomy_fields() {

  // Cycles through all the fields of all the content types that contains
  // geofield to find vocabularies.
  $content_types = node_layer_get_content_types();
  foreach ($content_types as $key => $content_type) {
    $fields = field_read_instances(array('bundle' => $key));
    foreach ($fields as $field) {
      $field_info = field_info_field($field['field_name']);
      if ($field_info['type'] == 'taxonomy_term_reference') {
        foreach ($field_info['settings']['allowed_values'] as $allowed_value) {
          $taxnonomy_fields[] = array(
            'vocabulary' => $allowed_value['vocabulary'],
            'field' => $field_info['field_name'],
          );
        }
      }
    }
  }
  return $taxnonomy_fields;
}

/**
 * Fetches nodes.
 *
 * @todo consider selecting country data to display on map.
 */
function node_layer_fetch_nodes($filters) {
  if ($filters['map_content_type']) {
    $nodes = array();
    $query = new EntityFieldQuery();

    // Filters result by bundle.
    $query->entityCondition('entity_type', 'node')

      // @todo clean up.
      // ->addTag('efq_debug')
      ->entityCondition('bundle', $filters['map_content_type']);

    // Fetches the geofields in the content type and filters out nodes that
    // have an empty geofield.
    if ($filters['geofield']) {
      $query->fieldCondition($filters['geofield'], 'lat', 'NULL', '!=');
    }

    // Allows including unpublished nodes in the result.
    if ($filters['show_unpublished'] == TRUE) {
      $query->propertyCondition('status', array(0, 1), 'in');
    }
    else {
      $query->propertyCondition('status', 1);
    }

    // Applies chosen taxonomy terms filters.
    if (isset($filters['terms'])) {
      foreach ($filters['terms'] as $term_field => $tids) {
        if (count($tids) > 0) {
          $query->fieldCondition($term_field, 'tid', $tids, 'in');
        }
      }
    }

    // Runs the query and loads the nodes.
    $result = $query->execute();
    if (isset($result['node'])) {
      $nids = array_keys($result['node']);
      $nodes = entity_load('node', $nids);
    }
    return $nodes;
  }
  else {
    drupal_set_message('Not enough information to build map.', 'error');
  }
}

/**
 * Prints entity field query.
 */
function node_layer_query_alter($query) {
  if ($query->hasTag('efq_debug') && module_exists('devel')) {
    // @codingStandardsIgnoreStart
    dpm((string) $query);
    dpm($query->arguments());
    // @codingStandardsIgnoreEnd
  }
}

/**
 * Turns field items into geojson features.
 *
 * Shameless copy from leaflet_process_geofield().
 */
function node_layer_prepare_features($items = array()) {
  $data = array();
  geophp_load();
  foreach ($items as $item) {
    foreach ($item['field_items'] as $delta => $field_item) {

      // Translate linestring to polyline:
      if ($field_item['geo_type'] == 'multilinestring') {
        $field_item['geo_type'] = 'multipolyline';
      }
      // Geofield 7.x-2.x compatibility.
      if (!isset($field_item['wkt']) && isset($field_item['geom'])) {
        $field_item['wkt'] = $field_item['geom'];
      }
      $geom = geoPHP::load($field_item['wkt'], 'wkt');
      $type = get_class($geom);
      switch ($field_item['geo_type']) {
        // Formats single features.
        case 'point':
        case 'polygon':
        case 'linestring':
          $geofeature = new MapeditorGeoFeature($type, $geom);
          if (isset($item['title']) && isset($item['popup'])) {
            $geofeature->setProperties($item['title'], $item['popup']);
          }
          $geofeature->setGeometry($type, $geom);
          $data[] = $geofeature->data;
          break;

        // Formates multiple features of the same type.
        case 'multipolyline':
        case 'multipolygon':
        case 'multipoint':
          $components = $geom->getComponents();
          foreach ($components as $component) {
            $class = get_class($component);
            $geofeature = new MapeditorGeoFeature();
            if (isset($item['title']) && isset($item['popup'])) {
              $geofeature->setProperties($item['title'], $item['popup']);
            }
            $geofeature->setGeometry($class, $component);
            $data[] = $geofeature->data;
          }
          break;

        // Formates multiple features of mixed types.
        // @todo merge with other multiple?
        case 'geometrycollection':
          $components = $geom->getComponents();
          foreach ($components as $component) {
            $class = get_class($component);
            $geofeature = new MapeditorGeoFeature($class, $component);
            if (isset($item['title']) && isset($item['popup'])) {
              $geofeature->setProperties($item['title'], $item['popup']);
            }
            $geofeature->setGeometry($class, $component);
            $data[] = $geofeature->data;
          }
          break;

      }
    }
  }
  return $data;
}

/**
 * Implements hook_map_layer_inline_entity_form_submit().
 *
 * Alters the settings before submitting (saves the specific field values).
 *
 * @todo merge with map layer settings alter.
 */
function node_layer_map_layer_inline_entity_form_submit_alter(&$settings, $map_layer) {
  if ($map_layer->type == 'node_layer') {
    $settings['attribution'] = $map_layer->attribution;
    $settings['popup'] = $map_layer->popup;
    $settings['icon'] = $map_layer->icon;
    $settings['control'] = $map_layer->control;
    $settings['clustering'] = $map_layer->clustering;
    $settings['node_filters'] = $map_layer->node_filters;
    $settings['view_mode'] = $map_layer->view_mode;
  }
  return $settings;
}
