<?php

/**
 * @file
 * Code for the Splash_screen feature.
 */

define("SPLASH_SCREEN_PATH", "splash");

/**
 * Implements hook_menu().
 */
function splash_screen_menu() {
  $items['admin/config/regional/splash_screen_settings'] = array(
    'title' => 'Splash screen settings',
    'description' => 'Configure the splash screen module',
    'file' => 'includes/splash_screen.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_splash_screen_settings_form'),
    'access arguments' => array('administer splash screen'),
  );

  $items[SPLASH_SCREEN_PATH] = array(
    'title' => 'Splash screen',
    'page callback' => 'theme',
    'page arguments' => array('splash'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function splash_screen_permission() {
  return array(
    'administer splash screen' => array(
      'title' => t('Administer splash screen'),
      'description' => t('Administrer full settings of the splash screen module.'),
    ),
  );
}

/**
 * Implements hook_boot().
 *
 * Display splash page when go at /.
 */
function splash_screen_boot() {
  // If empty, $_GET['q'] is rewritten by splash screen path.
  if (empty($_GET['q'])) {
    $_GET['q'] = SPLASH_SCREEN_PATH;
  }
}

/**
 * Implements hook_theme().
 */
function splash_screen_theme($existing, $type, $theme, $path) {
  return array(
    'splash' => array(
      'template' => 'splash',
      'path' => $path . '/theme',
      'variables' => array(
        'path' => NULL,
      ),
    ),
    'page__splash' => array(
      'template' => 'page--splash',
      'path' => $path . '/theme',
      'render element' => 'page',
      'base hook' => 'page',
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function splash_screen_preprocess_splash(&$variables) {
  // Cache our custom title.
  $custom_splash_screen_title = variable_get('splash_screen_title_value', FALSE);
  // Fallback to the site name if it is not configured.
  $splash_screen_title = $custom_splash_screen_title ? $custom_splash_screen_title : variable_get('site_name');
  // Set the title.
  drupal_set_title($splash_screen_title);

  // Initialize variables.
  $home_page = variable_get('site_frontpage', '');
  $href = $home_page;
  $options = array();
  $languages_blacklist = variable_get('splash_screen_blacklist', array());

  // Compile list of enabled languages, if not in blacklist.
  $languages = array_filter(language_list('enabled')[1], function ($language) use ($languages_blacklist) {
    return !in_array($language->language, $languages_blacklist);
  });

  // Export variables to template.
  $variables['icon'] = theme('nexteuropa_multilingual_language_icon');
  $variables['languages_list'] = theme('nexteuropa_multilingual_language_list', [
    'languages' => $languages,
    'path' => $href,
    'options' => $options,
  ]);
  $variables['languages_list_array'] = $languages;
  $variables['languages_blacklist'] = $languages_blacklist;
}
