<?php
/**
 * @file
 * Code for the NextEuropa Metatags feature.
 */

/**
 * Implements hook_metatag_info().
 */
function nexteuropa_metatags_metatag_info() {
  $info['groups']['ESS_metatags'] = array(
    'label' => t('ESS metatags : metatags for ES indexation'),
  );

  $vocabulary = taxonomy_vocabulary_machine_name_load('metatags_ess_gf');
  $options = array();
  $terms = taxonomy_get_tree($vocabulary->vid);
  foreach ($terms as $term) {
    $term_full = taxonomy_term_load($term->tid);
    $options[$term_full->field_meta_value['und'][0]['value']] = str_repeat('-', $term->depth) . $term->name;
  }

  $info['tags']['ESS_GF'] = array(
    'label' => t('ESS GF'),
    'description' => t('Global search'),
    'class' => 'DrupalTextMetaTag',
    'group' => 'ESS_metatags',
    'form' => array(
      '#type' => 'select',
      '#options' => $options,
      '#empty_option' => t('- None -'),
    ),
    'select_or_other' => TRUE,
  );

  $info['tags']['ESS_RF'] = array(
    'label' => t('ESS RF'),
    'description' => t('Restricted search'),
    'class' => 'DrupalTextMetaTag',
    'group' => 'ESS_metatags',
  );

  return $info;
}
