<?php

/**
 * @file
 * nexteuropa_ds_layouts.module
 */

/**
 * Define Display Suite layouts.
 *
 * @return array
 *   A collection of layouts.
 */
function nexteuropa_ds_layouts_ds_layout_info() {
  $path = drupal_get_path('module', 'nexteuropa_ds_layouts');

  $layouts['ne_bootstrap_3_6_3_stacked'] = array(
    'label' => t('NE Bootstrap: 3-6-3 stacked'),
    'path' => $path . '/layouts/ne_bootstrap_3_6_3_stacked',
    'regions' => array(
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'top' => t('Top'),
      'left' => t('Left'),
      'central' => t('Middle'),
      'right' => t('Right'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  $layouts['ne_bootstrap_3_9_stacked'] = array(
    'label' => t('NE Bootstrap: 3-9 stacked'),
    'path' => $path . '/layouts/ne_bootstrap_3_9_stacked',
    'regions' => array(
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'top' => t('Top'),
      'left' => t('Left'),
      'central' => t('Middle'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  $layouts['ne_bootstrap_3_9_stacked_conditional'] = array(
    'label' => t('NE Bootstrap: 3-9(12) stacked conditional sidebar'),
    'path' => $path . '/layouts/ne_bootstrap_3_9_stacked_conditional',
    'regions' => array(
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'top' => t('Top'),
      'left' => t('Left'),
      'central' => t('Middle'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  $layouts['ne_bootstrap_1col_stacked'] = array(
    'label' => t('NE Bootstrap: 1col stacked'),
    'path' => $path . '/layouts/ne_bootstrap_1col_stacked',
    'regions' => array(
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'top' => t('Top'),
      'central' => t('Main'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  $layouts['ne_bootstrap_1col_stacked_bottom_header'] = array(
    'label' => t('NE Bootstrap: 1col stacked with bottom header'),
    'path' => $path . '/layouts/ne_bootstrap_1col_stacked_bottom_header',
    'regions' => array(
      'left_header' => t('Left Header'),
      'right_header' => t('Right Header'),
      'bottom_header' => t('Bottom Header'),
      'top' => t('Top'),
      'central' => t('Main'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  $layouts['ne_2col'] = array(
    'label' => t('NE: 2col'),
    'path' => $path . '/layouts/ne_2col',
    'regions' => array(
      'main' => t('Main'),
      'second' => t('Second'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  $layouts['ne_2col_sidebar_no_link'] = array(
    'label' => t('NE: 2col - sidebar without link'),
    'path' => $path . '/layouts/ne_2col_sidebar_no_link',
    'regions' => array(
      'main' => t('Main'),
      'second' => t('Second'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  $layouts['ne_1col'] = array(
    'label' => t('NE: 1col'),
    'path' => $path . '/layouts/ne_1col',
    'regions' => array(
      'main' => t('Main'),
    ),
    'form' => TRUE,
    'image' => TRUE,
    'is_nexteuropa' => TRUE,
  );

  return $layouts;
}
