<?php

/**
 * @file
 * Install, update and uninstall functions for multisite_block_carousel module.
 */

/**
 * Implements hook_enable().
 */
function multisite_block_carousel_enable() {
  drupal_set_message(t('Multisite Block Carousel feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function multisite_block_carousel_disable() {
  drupal_set_message(t('Multisite Block Carousel feature is now inactive on your site.'));
}
