<?php
/**
 * @file
 * Code for the wiki feature.
 */

include_once('wiki.features.inc');

/*
* hook_menu
*/
function wiki_menu() {
  $items = array();
 
  $items['community/%group_name/wiki'] = array(
    'title' => 'wiki',
    'page callback' => 'views_page',
    'page arguments' => array('wiki_list', 'page_1', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}

/*
* hook_enable
*/
function wiki_enable() {
  _add_views_context("communities","wiki_list");
}

function wiki_disable() {
  _remove_views_context("communities","wiki_list");
}



/**
* Implements hook_element_info_alter().
*
* Sets the text format processor to a custom callback function.
* This code is taken from the Better Formats module.
*/

function wiki_element_info_alter(&$type) {
  if (isset($type['text_format']['#process'])) {
    foreach ($type['text_format']['#process'] as &$callback) {
      if ($callback === 'filter_process_format') {
        $callback = 'wiki_format_filter_process_format';
      }
    }
  }
}

	
/*
* hook_filter_process_format
*/

function wiki_format_filter_process_format($element) {
  $element = filter_process_format($element);
  // Change the default text format of the 'body' field to ' wiki'.
  if ($element['#bundle'] == 'wiki' && $element['#field_name'] == 'body') {
    $element['format']['format']['#default_value'] = 'wiki';
  }
  return $element;
}
