<?php

/**
 * @file
 * Install file of the translation management MT@EC.
 */

/**
 * Implements hook_install().
 *
 * Add the uuid field to the tmgmt_job schema.
 */
function tmgmt_mtec_install() {
  $schema = drupal_get_schema('tmgmt_job');
  db_add_field('tmgmt_job', 'uuid', $schema['fields']['uuid']);
}

/**
 * Implements hook_schema_uninstall().
 *
 * Remove the uuid field to the tmgmt_job schema.
 */
function tmgmt_mtec_uninstall() {
  db_drop_field('tmgmt_job', 'uuid');
}
