# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    depth: 1
    # The tags property is not documented but can be found in the following
    # snippet of code
    # https://github.com/drone-plugins/drone-git/blob/master/plugin.go#L153
    tags: true

# ==============================================================================
# Workspace location ===========================================================
# ==============================================================================
# Define the build path inside the container ( Here /test/platform )
# ==============================================================================
workspace:
  base: /test
  path: platform

# ==============================================================================
# Main services ================================================================
# ==============================================================================
services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:7.3-ci
    environment:
      - DOCUMENT_ROOT=/test/platform
      - SMTP_SERVER=bananas
    pull: true
    when:
      event: [ push, pull_request, tag ]
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    pull: true
    command: --innodb-log-file_size=2G --max-allowed-packet=1G --innodb-buffer-pool-size=512M --wait-timeout=31536000
    when:
      event: [ push, pull_request, tag ]
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.5
    shm_size: 2gb
    pull: true
    when:
      event: [ push, pull_request, tag ]

# ==============================================================================
# pipeline =====================================================================
# ==============================================================================
pipeline:

  # ============================================================================
  # Build install and tests ====================================================
  # ============================================================================
  # Build and install developement platform and run phpcs and behat tests
  # ============================================================================

  # Build and install platform
  site-build:
    image: registry.fpfis.eu/fpfis/httpd-php:7.3-ci
    commands:
      - php --version
      - composer install --ansi --no-suggest --no-progress
      - ./bin/phing build-platform-dev -propertyfile 'build.properties.drone' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'
      - ./bin/phing setup-drone-file-system -propertyfile 'build.properties.drone' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'
      #- ./bin/phing install-platform  -propertyfile 'build.properties.drone' -D'platform.profile.name'='${PLATFORM_PROFILE=multisite_drupal_standard}' -D'platform.site.theme_default'='${THEME_DEFAULT=ec_resp}'
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      event: [push, tag, pull_request]

  # Run behat tests
  behat:
    image: registry.fpfis.eu/fpfis/httpd-php:7.3-ci
    commands:
      - php test.php
    when:
      event: [push, tag, pull_request]
