<?php
/**
 * @file
 * Code for the Megia Gallery feature.
 */

include_once 'multisite_mediagallery_community.features.inc';
include_once 'multisite_mediagallery_community.views_alter.inc';

/**
 * Implements hook_menu().
 */
function multisite_mediagallery_community_menu() {
  $items = array();

  $items['community/%group_name/gallerymedia'] = array(
    'title' => 'Media Gallery',
    'page callback' => 'views_page',
    'page arguments' => array('galleries', 'galleries_community', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function multisite_mediagallery_community_form_gallerymedia_node_form_alter(&$form, &$form_state, $form_id) {
  // Get children from group tab 'Commnunity'.
  if (isset($form['#groups']['group_gallerymedia_community'])) {
    $fields_group_community = $form['#groups']['group_gallerymedia_community']->children;
    foreach ($fields_group_community as $field) {
      // If a field of the group tab 'Community' has the class 'element-hidden'.
      if (in_array('element-hidden', $form[$field]['#attributes']['class'])) {
        // Hide the group tab 'Community'.
        field_group_hide_field_groups($form, array('group_gallerymedia_community'));
        continue;
      }
    }
  }
}

/**
 * Implemets hook_views_pre_render().
 */
function multisite_mediagallery_community_views_pre_render(&$view) {
  if ($view->name == 'galleries' && $view->current_display == 'page') {
    $output = '';
    $og = og_context();

    if ($og) {
      $gid = $og['gid'];

      // Check if user has permissions to create content for the community and
      // render the button 'Create content'.
      if (og_is_member('node', $gid) && og_user_access('node', $gid, 'create gallerymedia content') && user_access('create gallerymedia content')) {
        $output .= l(t('Create a Media Gallery'), 'node/add/gallerymedia', array(
          'attributes' => array(
            'type' => 'add',
            'action_bar' => 'single',
            'btn_group' => 'single',
          ),
          'query' => array(
            'og_group_ref' => $og['gid'],
          ),
        ));
      }
    }

    // Add menu to the exsiting header.
    if (isset($view->header['area'])) {
      $view->header['area']->options['content'] = $view->header['area']->options['content'] . $output;
    }
  }
}
