<?php
/**
 * @file
 * Module file.
 */

/**
 * Necessary to ensure compatibility with older versions of Registry Rebuild.
 *
 * @link https://www.drupal.org/project/registry_rebuild
 */
include_once 'src/LanguageCoverageService.php';

use Drupal\nexteuropa_laco\LanguageCoverageService as Service;

/**
 * Implements hook_boot().
 */
function nexteuropa_laco_boot() {
  if (Service::isServiceRequest()) {
    Service::getInstance()->hookBoot();
  }
}

/**
 * Implements hook_init().
 */
function nexteuropa_laco_init() {
  if (Service::isServiceRequest()) {
    Service::getInstance()->hookInit();
  }
}
