<?php
/**
 * @file
 * Code for the communities feature.
 */

include_once('communities.features.inc');


/*
* hook_disable
*/
function communities_disable() {
  _disable_content_type('community');
}

/*
* hook_enable
*/
function communities_enable() {
  // affect a file image to the default image of the field thumbnail of the content type community -------------------------------------------------------
  // file creation
  $file = new stdClass();
  $file->fid = NULL;
  $file->uri = "public://default_images/community_default.png";
  $file->filename = "community_default.png";
  $file->filemime = file_get_mimetype($file->uri);
  $file->uid = 1;
  $file->status = FILE_STATUS_PERMANENT;
  $f = file_save($file);

  // field config update
  $field = field_info_field('field_thumbnail');
  $field['settings']['default_image'] = $f->fid;
  field_update_field($field);
}



/*
* hook_views_pre_render
*/
function communities_views_pre_render(&$view) {
  if($view->name == 'communities_directory') {
    $alphabet = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
    $output = '<ul class="glossary">';
    foreach($alphabet as $letter) {
      $url = $_GET['q'].'/'.$letter;
      $output .= '<li>'.l($letter, $url).'</li>';
    }
    $output .= '<div class="add_content">'.l(t('create a new community'),'node/add/community').'</div>';
    $view->header['area']->options['content'] = $output;
  }
}

function communities_init() {
  drupal_add_css(drupal_get_path('module', 'communities') . '/communities.css');
}
