<?php
/**
 * @file
 * Code for the communities feature.
 */

include_once('communities.features.inc');


/*
* hook_disable
*/
function communities_disable() {
  _disable_content_type('community');
  
   // revoke permissions to roles ----------------------------------------------------------------------------------------------------------------------------------------------
  $result = db_select('role', 'r')
    ->condition('name', "contributor",'=')
    ->fields('r', array('rid'))
    ->execute()
    ->fetchAssoc();

  user_role_revoke_permissions($result['rid'], array(  
    'create community content',
	'delete own community content',
	'edit own community content',  
  ));  
}


/*
* hook_enable
*/
function communities_enable() {
  // create og role -------------------------------------------------------------------------------------------------------------------------------
  $community_manager_role = og_create_global_role("community_manager");
}



/*
* hook_views_pre_render
*/
function communities_views_pre_render(&$view) {
  if($view->name == 'communities_directory') {
    $alphabet = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
    
    $output = '<div class="well btn-toolbar action_bar">';
    $output .= '<div class="btn-group">';
    
    foreach($alphabet as $letter) {
      $url = $_GET['q'].'/'.$letter;
      $output .= l($letter,$url,array('attributes' => array('class' => array('btn btn-small action-expand'))));
    }
    
    $output .= '</div>';
    
    if(user_access('create community content'))  {
      $output.= '<div class="btn-group">';
      $output.= l('<i class="icon-plus icon-white"></i>'.t('Create a new community'),'node/add/community',array('attributes' => array('class' => array('btn btn-info')), 'html' => true));
      $output.= '</div>';    
    }
    
    $output .= '</div>';
    
    $view->header['area']->options['content'] = $output;
  }
}



/*
* hook_init
*/
function communities_init() {
  drupal_add_css(drupal_get_path('module', 'communities') . '/communities.css');
}


/*
* hook_modules_enabled
*/
function communities_modules_enabled($modules) {
  if(in_array('communities', $modules)) { 
    $account = user_load_by_name('administrator');
    $account->field_firstname['und'][0]['value'] = 'John';
    $account->field_lastname['und'][0]['value'] = 'Smith'; 
    user_save($account); 
    $account1 = user_load_by_name('contributor');
    $account1->field_firstname['und'][0]['value'] = 'John';
    $account1->field_lastname['und'][0]['value'] = 'Doe'; 
    user_save($account1); 	
  }
}


/*
* hook_node_type_insert
*/
function communities_node_type_insert($info) {
  if($info->type == 'community') {
	node_types_rebuild();
	  
    // add permissions to roles ----------------------------------------------------------------------------------------------------------------------------------------------
    $au = db_select('role', 'r')
      ->condition('name', "authenticated user",'=')
      ->fields('r', array('rid'))
      ->execute()
      ->fetchAssoc();

    user_role_grant_permissions($au['rid'], array(  
      'create community content',
	  'delete own community content',
	  'edit own community content',
      'view own unpublished content',
	  'view revisions',
	  'access workbench',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'view moderation messages', 
	  'moderate content from draft to needs_review',
      'view moderation history',
    )); 	
  
    // add permissions to OG roles ----------------------------------------------------------------------------------------------------------------------------------------------  
    $cm = db_select('og_role', 'r')
      ->condition('name', "community_manager",'=')
      ->fields('r', array('rid'))
      ->execute()
      ->fetchAssoc();  
  
    og_role_grant_permissions($cm['rid'], array(  
      'add user',
      'approve and deny subscription',
      'unsubscribe',
      'update group', 
      'administer group',
    ));  
  }	
}


/*
* hook_workbench_moderation_transition
*/
function communities_workbench_moderation_transition($node, $previous_state, $new_state) {
  global $base_url;

  drupal_set_message("DEBUG moderation workflow");
  drupal_set_message(print_r($previous_state, TRUE));
  drupal_set_message(print_r($new_state, TRUE));
  drupal_set_message($base_url);
  
  $query = db_select('users', 'u');
  $query->join('users_roles', 'ur', 'u.uid = ur.uid');
  $query->join('role', 'r', 'r.rid = ur.rid');
  $query->condition('r.name', "administrator",'=');
  $query->fields('u', array('uid'));
  $result = $query->execute();

  while($record = $result->fetchAssoc()) {
    $admin_users[] = $record['uid'];
  }

  drupal_set_message(print_r($admin_users, TRUE));

  $transition_made = $previous_state."__".$new_state;
  
  $transitions_settings = array(
    "draft__needs_review" => array(
	  "message" => get_mail_template(),
	  "subject" => "creation of community request",
	  "to_creator" => $node->uid,
         "to_admin" => $admin_users,
         "nid" => $node->nid,
	),
  );

  if(isset($transitions_settings[$transition_made])) {
    $settings = $transitions_settings[$transition_made];
    _send_mail($settings);
  }
   
}


function _send_mail($params) {
  $module = 'communities';
  $key = 'workbench_moderation_workflow';

  $from = variable_get('site_mail', 'admin@example.com');

  $language = language_default();
  $send = TRUE;

  foreach($params['to_admin'] as $uid) {
    $user = user_load($uid);
    $params['admin_uid'] = $uid;
    $result = drupal_mail($module, $key, $user->mail, $language, $params, $from, $send);
  }

  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }

}


/*
* hook_mail
*/
function communities_mail($key, &$message, $params) {
  global $user, $base_url;

  $admin_user = user_load($params['admin_uid']);
  $creator_user = user_load($params['to_creator']);

  drupal_set_message(print_r($params,TRUE));
  drupal_set_message(print_r($admin_user,TRUE));
  drupal_set_message(print_r($creator_user,TRUE));

  $node = node_load($params['nid']);

  // check if user fields are populated
  if(isset($admin_user->field_firstname['und'][0]['value'])) {
    $admin_name = $admin_user->field_firstname['und'][0]['value']." ".$admin_user->field_lastname['und'][0]['value'];
  }
  else {
    $admin_name = $admin_user->name;
  }
  if(isset($creator_user->field_firstname['und'][0]['value'])) {
    $creator_name = $creator_user->field_firstname['und'][0]['value']." ".$creator_user->field_lastname['und'][0]['value'];
  }
  else {
    $creator_name = $admin_user->name;
  }  
  
  // create token
  $variables = array(
    '%admin_user' => $admin_name, 
    '%creator_user' => $creator_name,
    '%community_link' => l($node->title, $base_url."/en/node/".$node->nid), 
    '%site_url' => $base_url,
  );

  $message['headers']['Content-Type'] = "text/html; charset=iso-8859-1";
  $message['headers']['Mime-Version'] = "1.0";

  switch ($key) {
    case 'workbench_moderation_workflow':
      $message['subject'] = $params["subject"];
      $message['body'][] = check_plain(strtr($params['message'], $variables));
      break;
  }
}


function get_mail_template() {
  $output = "Dear %admin_user,<br><p>%creator_user requests a community creation : %community_link<br></p><p><a href=\"%site_url/en/admin/workbench\">Go to administration</a></p>";
  return $output;
}