<?php

/**
 * Implements hook_block_info().
 */
function multisite_og_button_block_info() {
  $blocks['og-contextual-links'] = array(
    'info' => t('OG Contextual Links'), 
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function multisite_og_button_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'og-contextual-links':
      $block['subject'] = t('Create content');
      $block['content'] = _multisite_og_button_contextual_links();
      break;
  }
  return $block;
}

/**
 * Helper function to fetch the links
 */
function _multisite_og_button_contextual_links(){
  $context = og_context_determine_context();
  if($context){
    $links = og_node_create_links($context->gid);
    return $links;
  }
}
