<?php
/**
 * @file
 * Code for the E-library Standard feature.
 */

include_once('e_library_standard.features.inc');
include_once('e_library_standard.views_alter.inc');

/**
 * Add a buttons in the views associated with this feature
 * @param type $view 
 */
function e_library_views_pre_render(&$view) {

	if($view->name=='e_library'){

			switch( $view->current_display ) {
				case 'page':
					if ( user_access('create document content') ) {
						$output= l(t('Upload a new Document'),
								'node/add/document',
								array('attributes' => array('type' => 'add', 'action_bar' => 'single', 'btn_group' => 'single')));
						$view->header['area']->options['content'] = $view->header['area']->options['content'].$output;
					}
					break;
				default:
					break;
		}
	}
}