<?php

/**
 * @file
 * Install, update and uninstall functions for the STARTERKIT module.
 *
 * @see https://webgate.ec.europa.eu/CITnet/confluence/display/MULTISITE/Custom+features
 */

include_once 'STARTERKIT.install.inc';

/**
 * Implements hook_enable().
 */
function STARTERKIT_enable() {
  config_solr_bundle('CONTENT_TYPE','add');
  drupal_set_message(t('STARTERKIT %v feature is now active on your site.', array('%v' => _STARTERKIT_get_version())));
}

/**
 * Implements hook_disable().
 */
function STARTERKIT_disable() {
  //Example
  //multisite_drupal_toolbox_disable_content_type('kit');
  config_solr_bundle('CONTENT_TYPE','delete');
  drupal_set_message(t('STARTERKIT %v feature is now inactive on your site.', array('%v' => _STARTERKIT_get_version())));
}

/**
 * Implements hook_install().
 */
function STARTERKIT_install() {
  //Install scripts here
}

/**
 * Implements hook_uninstall().
 */
function STARTERKIT_uninstall() {
  //Uninstall scripts here
}