<?php

/**
 * @file
 * Code for the Splash_screen feature.
 */

/*
 * hook_init
 */

function splash_screen_init() {
  global $base_url, $user;

  $is_admin = 0;
  if (in_array('administrator', array_values($user->roles))) {
    $is_admin = 1;
  }

  $cookie_name = variable_get("language_cookie_param");
  $splash_screen_url = variable_get("splash_screen_url"); // TODO put these variables in a admin form settings

  if (!$is_admin) {
    if (count($_COOKIE) > 0) {
      if (!isset($_COOKIE['splash'])) {
        if (!isset($_GET['splash'])) {
          setcookie('splash', 1, time()+31536000);
          drupal_goto($splash_screen_url, array('query' => array('splash' => TRUE)));
        }
      }
    }
    else {
      if (!isset($_GET['cookies'])) {
        setcookie('test_cookies', 1, time()+60);
        header('Location:' . $base_url . '/' . request_path() . '?cookies=true');
      }
    }
  }
}


/**
 * Implements hook_menu().
 */
function splash_screen_menu() {
  $items['admin/config/splash_screen'] = array(
    'title' => 'Splash screen settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_splash_screen_settings'),
    'access arguments' => array('administer splash screen'),
  );
  $items['admin/config/splash_screen/settings'] = array(
    'title' => 'Splash screen settings',
    'description' => 'Configure the splash screen module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_splash_screen_settings'),
    'access arguments' => array('administer splash screen'),
  ); 
  return $items;
}


function form_splash_screen_settings($form, &$form_state) {
  $form['splash_screen_language_msg'] = array(
    '#type' => 'textfield',
    '#title' => t('splash screen language choice'),
    '#default_value' => variable_get("splash_screen_language_msg"),
  ); 
  return system_settings_form($form);
}

/**
 * Implements hook_permission().
 */
function hook_permission() {
  return array(
    'administer splash screen' => array(
      'title' => t('Administer splash screen'), 
      'description' => t('Administrer full settings of the splash screen module.'),
    ),
  );
}
