<?php
/**
 * @file
 * multisite_metatags.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function multisite_metatags_field_default_fields() {
  $fields = array();

  // Exported field: 'node-contenttype-field_meta_classification'.
  $fields['node-contenttype-field_meta_classification'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_meta_classification',
      'foreign keys' => array(
        'tid' => array(
          'columns' => array(
            'tid' => 'tid',
          ),
          'table' => 'taxonomy_term_data',
        ),
      ),
      'indexes' => array(
        'tid' => array(
          0 => 'tid',
        ),
      ),
      'locked' => '0',
      'module' => 'taxonomy',
      'settings' => array(
        'allowed_values' => array(
          0 => array(
            'vocabulary' => 'classification',
            'parent' => '0',
          ),
        ),
        'options_list_callback' => 'i18n_taxonomy_allowed_values',
      ),
      'translatable' => '0',
      'type' => 'taxonomy_term_reference',
    ),
    'field_instance' => array(
      'bundle' => 'contenttype',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Please select an IPG classification for your content. It will supply information to METADATA "Classification".<br/>This classification respects the <a href="http://ec.europa.eu/ipg/content/optimise/metadata/annex2_en.htm" target="_blank">IPG guidelines</a>.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'i18n_taxonomy',
          'settings' => array(),
          'type' => 'i18n_taxonomy_term_reference_link',
          'weight' => 1,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_meta_classification',
      'label' => 'IPG Classification',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '41',
      ),
    ),
  );

  // Exported field: 'node-contenttype-field_meta_description'.
  $fields['node-contenttype-field_meta_description'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_meta_description',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(),
      'translatable' => '0',
      'type' => 'text_long',
    ),
    'field_instance' => array(
      'bundle' => 'contenttype',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'This text will supply information to METADATA "Description".<br/>It should respect the <a href="http://ec.europa.eu/ipg/content/optimise/metadata/annex1_en.htm#section_6" target="_blank">IPG guidelines</a>.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 2,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_meta_description',
      'label' => 'Description metatag',
      'required' => 0,
      'settings' => array(
        'better_formats' => array(
          'allowed_formats' => array(
            'basic_html' => 'basic_html',
            'filtered_html' => 'filtered_html',
            'full_html' => 'full_html',
            'plain_text' => 'plain_text',
          ),
          'allowed_formats_toggle' => 0,
          'default_order_toggle' => 0,
          'default_order_wrapper' => array(
            'formats' => array(
              'basic_html' => array(
                'weight' => '5',
              ),
              'filtered_html' => array(
                'weight' => '-9',
              ),
              'full_html' => array(
                'weight' => '-10',
              ),
              'plain_text' => array(
                'weight' => '-8',
              ),
            ),
          ),
        ),
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '3',
        ),
        'type' => 'text_textarea',
        'weight' => '42',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('IPG Classification');
  t('Description metatag');
  t('Please select an IPG classification for your content. It will supply information to METADATA "Classification".<br/>This classification respects the <a href="http://ec.europa.eu/ipg/content/optimise/metadata/annex2_en.htm" target="_blank">IPG guidelines</a>.');
  t('This text will supply information to METADATA "Description".<br/>It should respect the <a href="http://ec.europa.eu/ipg/content/optimise/metadata/annex1_en.htm#section_6" target="_blank">IPG guidelines</a>.');

  return $fields;
}
