; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.12"

; Modules
projects[views_bulk_operations][subdir] = "contributed"
projects[views_bulk_operations][version] = "3.0-beta3"

projects[ctools][subdir] = "contributed"
projects[ctools][version] = "1.0-rc1"

projects[captcha][subdir] = "contributed"
projects[captcha][version] = "1.0-beta1"

projects[ckeditor][subdir] = "contributed"
projects[ckeditor][version] = "1.8"

projects[context][subdir] = "contributed"
projects[context][version] = "3.0-beta2"

projects[date][subdir] = "contributed"
projects[date][version] = "2.0-alpha5"

projects[defaultcontent][subdir] = "contributed"
projects[defaultcontent][version] = "1.0-alpha6"

projects[diff][subdir] = "contributed"
projects[diff][version] = "2.0"

projects[entity][subdir] = "contributed"
projects[entity][version] = "1.0-rc1"

projects[features][subdir] = "contributed"
projects[features][version] = "1.0-rc2"

projects[media][subdir] = "contributed"
projects[media][version] = "2.x-dev"

projects[fivestar][subdir] = "contributed"
projects[fivestar][version] = "2.0-alpha1"

projects[hidden_captcha][subdir] = "contributed"
projects[hidden_captcha][version] = "1.0"

projects[password_policy][subdir] = "contributed"
projects[password_policy][version] = "1.0-beta2"

projects[rules][subdir] = "contributed"
projects[rules][version] = "2.0"

projects[strongarm][subdir] = "contributed"
projects[strongarm][version] = "2.0-beta4"

projects[sweaver][subdir] = "contributed"
projects[sweaver][version] = "1.1"

projects[token][subdir] = "contributed"
projects[token][version] = "1.0-beta7"

projects[uuid][subdir] = "contributed"
projects[uuid][version] = "1.0-alpha2"

projects[varnish][subdir] = "contributed"
projects[varnish][version] = "1.0-beta1"

projects[views][subdir] = "contributed"
projects[views][version] = "3.3"

projects[views_datasource][subdir] = "contributed"
projects[views_datasource][version] = "1.x-dev"

projects[votingapi][subdir] = "contributed"
projects[votingapi][version] = "2.4"

projects[workbench][subdir] = "contributed"
projects[workbench][version] = "1.1"

projects[workbench_moderation][subdir] = "contributed"
projects[workbench_moderation][version] = "1.1"

projects[link][subdir] = "contributed"
projects[link][version] = "1.0"

projects[og][subdir] = "contributed"
projects[og][version] = "1.3"

projects[site_map][subdir] = "contributed"
projects[site_map][version] = "1.0"

;projects[less][subdir] = "contributed"
;projects[less][version] = "2.4"

projects[xmlsitemap][subdir] = "contributed"
projects[xmlsitemap][version] = "2.0-rc1"

projects[backup_migrate][subdir] = "contributed"
projects[backup_migrate][version] = "2.2"

projects[pathauto][subdir] = "contributed"
projects[pathauto][version] = "1.0"

projects[user_field_privacy][subdir] = "contributed"
projects[user_field_privacy][version] = "1.2"

projects[calendar][subdir] = "contributed"
projects[calendar][version] = "3.0-alpha2"

projects[og_create_perms][subdir] = "contributed"
projects[og_create_perms][version] = "1.0"

;projects[freelinking][subdir] = "contributed"
;projects[freelinking][version] = "3.1"

;projects[simplewiki][subdir] = "contributed"
;projects[simplewiki][version] = "1.x-dev"

projects[webform][subdir] = "contributed"
projects[webform][version] = "3.17"

projects[references][subdir] = "contributed"
projects[references][version] = "2.0"

projects[devel][subdir] = "contributed"
projects[devel][version] = "1.2"

projects[simplenews][subdir] = "contributed"
projects[simplenews][version] = "1.0-beta1"

;projects[views_slideshow][subdir] = "contributed"
;projects[views_slideshow][version] = "3.0"

;projects[libraries][subdir] = "contributed"
;projects[libraries][version] = "1.0"

projects[print][subdir] = "contributed"
projects[print][version] = "1.0-beta1"

;projects[features_override][subdir] = "contributed"
;projects[features_override][version] = "1.0-beta1"

projects[jquery_update][subdir] = "contributed"
projects[jquery_update][version] = "2.2"

projects[mailsystem][subdir] = "contributed"
projects[mailsystem][version] = "2.33"

projects[mimemail][subdir] = "contributed"
projects[mimemail][version] = "1.x-dev"

;projects[media_gallery][subdir] = "contributed"
;projects[media_gallery][version] = "1.0-beta7"

projects[multiform][subdir] = "contributed"
projects[multiform][version] = "1.0"

projects[apachesolr][subdir] = "contributed"
projects[apachesolr][version] = "1.0-beta17"

projects[file_entity][subdir] = "contributed"
projects[file_entity][version] = "2.x-dev"

projects[facetapi][subdir] = "contributed"
projects[facetapi][version] = "1.0-rc4"

projects[notifications][subdir] = "contributed"
projects[notifications][version] = "1.0-alpha2"

projects[messaging][subdir] = "contributed"
projects[messaging][version] = "1.0-alpha2"

projects[ds][subdir] = "contributed"
projects[ds][version] = "1.5"

;libraries
;libraries[ckeditor][download][type]= "get"
;libraries[ckeditor][download][file_type] = "tar.gz"
;libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.2/ckeditor_3.6.2.tar.gz"
;libraries[ckeditor][directory_name] = "ckeditor"
;libraries[ckeditor][destination] = "libraries"
;libraries[ckeditor][overwrite] = TRUE

