<?php

/**
 * @file
 * Install, update and uninstall functions for the node_pager module.
 *
 * @see https://webgate.ec.europa.eu/CITnet/confluence/display/MULTISITE/Custom+features
 */

/**
 * Implements hook_enable().
 */
function node_pager_enable() {
  drupal_set_message(t('node_pager feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function node_pager_disable() {
  drupal_set_message(t('node_pager feature is now inactive on your site.'));
}
