<?php
/**
 * @file
 * Code for the Multi-user blog feature.
 */

include_once 'multi_user_blog.features.inc';

/**
 * Implements hook_token_info().
 */
function multi_user_blog_token_info() {
  $info['types']['Breadcrumb_multi_user_blog'] = array(
    'name' => t('Breadcrumb_multi_user_blog'),
    'description' => t('Tokens related to Breadcrumb.'),
  );
  $info['tokens']['Breadcrumb_multi_user_blog']["multi_user_blog_title"] = array(
    'name' => t("Multi user blog Breadcrumb title"),
    'description' => t("The Breadcrumb title of the multi user blog."),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function multi_user_blog_tokens($type, $tokens, $data = array(), $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);
  // Tokens for e_libray_core Breadcrumb.
  if ($type == 'Breadcrumb_multi_user_blog') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'multi_user_blog_title':
                    $replacements[$original] = t("blog");
          break;
      }
    }
  }
  return $replacements;
}
