<?php

/**
 * @file
 */

/**
 * Add the js file needed to enable like/dislike button
 */
function likedislike_init() {
    drupal_add_js('http://ec.europa.eu/wel/like/js/likedislike.js', 'external');
}

/**
 * Implementation of hook_block_info().
 */
function likedislike_block_info() {
    $blocks['likedislike'] = array(
        'info' => t('likedislike'),
    );
    return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function likedislike_block_view($delta='') {
    $block = array();
    switch ($delta) {
        case 'likedislike':
            //$block['subject'] = t('Social bookmark');
            $block['content'] = likedislike_contents();
            break;
    }
    return $block;
}

/**
 * custom html block
 * @return string
 */
function likedislike_contents() {

    $current_url = curPageURL();
    return '<span class="like_dislike">{"url":"' . $current_url . '"}</span>';
}

/**
 * return the full current url
 * @return string
 */
function curPageURL() {
    $pageURL = 'http';
    if (isset($_SERVER["HTTPS"])) {
        if ($_SERVER["HTTPS"] == "on") {
            $pageURL .= "s";
        }
    }
    $pageURL .= "://";
    if ($_SERVER["SERVER_PORT"] != "80") {
        $pageURL .= $_SERVER["SERVER_NAME"] . ":" . $_SERVER["SERVER_PORT"] . $_SERVER["REQUEST_URI"];
    } else {
        $pageURL .= $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
    }
    return $pageURL;
}