<?php
/**
 * @file
 * This is the main file of the ecas module, which allows users to authenticate
 * to Drupal with their ECAS account.
 * Note that this module depends on the presence of:
 *   - the "FPFIS_Common" library
 *   - the phpcas client library
 * Both will be included from the FPFIS_COMMON_LIBRARIES_PATH
 */

// include the admin part of the module first
$admin_ecas_module_include = drupal_get_path('module', 'ecas') . '/includes/ecas.admin.inc';
include_once($admin_ecas_module_include);

/*
if (!is_dir(constant('FPFIS_COMMON_LIBRARIES_PATH'))) {  
  watchdog(
    'ecas',
    'The FPFIS_COMMON_LIBRARIES_PATH constant mentions a non-existing directory: :value. Thus, the ecas module will not be included.',
    array(':value' => constant('FPFIS_COMMON_LIBRARIES_PATH')),
    WATCHDOG_WARNING
  );
  return TRUE;
}
*/

$fpfis_common_include = constant('FPFIS_COMMON_LIBRARIES_PATH') . '/FPFIS_Common/fpfis_common.php';
/*
if (!is_file($fpfis_common_include)) {
  watchdog(
    'ecas',
    'Unable to find the :lib_name library in the :dir_path directory . Thus, the ecas module will not be included.',
    array(':dir_path' => constant('FPFIS_COMMON_LIBRARIES_PATH'), ':lib_name' => 'FPFIS_Common'),
    WATCHDOG_WARNING
  );
  return TRUE;
}
*/
include_once($fpfis_common_include);

// the FPFIS_Common is supposed to provide the FPFIS_ECAS_PATH constant
$phpcas_client_include = constant('FPFIS_ECAS_PATH');
/*
if (!is_file($phpcas_client_include)) {
  watchdog(
    'ecas',
    'Unable to find the :lib_name library at :dir_path . Thus, the ecas module will not be included.',
    array(':dir_path' => constant('FPFIS_ECAS_PATH'), ':lib_name' => 'phpcas'),
    WATCHDOG_WARNING
  );
  return TRUE;
}
*/
include_once($phpcas_client_include);

// finally, include the module code
$ecas_module_include = drupal_get_path('module', 'ecas') . '/includes/ecas.inc';
include_once($ecas_module_include);
define('ECAS_MODULE_CODE_AVAILABLE', TRUE);
