<?php

/**
 * @file
 * This is the main file of the ECAS module.
 *
 * This module allows users to authenticate to Drupal with their ECAS account.
 *
 * Note that this module depends on the presence of:
 * - the "FPFIS_Common" library
 * - the phpcas client library
 *
 * Both will be included from the FPFIS_COMMON_LIBRARIES_PATH.
 */

define('ECAS_MIN_PHPCAS_VERSION', "1.3.3");

// Include the admin part of the module first.
$admin_ecas_module_include = drupal_get_path('module', 'ecas') . '/includes/ecas.admin.inc';
include_once $admin_ecas_module_include;

$fpfis_common_include = constant('FPFIS_COMMON_LIBRARIES_PATH') . '/FPFIS_Common/fpfis_common.php';
include_once $fpfis_common_include;

// The FPFIS_Common is supposed to provide the FPFIS_ECAS_PATH constant.
$phpcas_client_include = variable_get('FPFIS_ECAS_PATH', constant('FPFIS_ECAS_PATH'));
include_once $phpcas_client_include;

// Finally, include the module code.
$ecas_module_include = drupal_get_path('module', 'ecas') . '/includes/ecas.inc';
include_once $ecas_module_include;
define('ECAS_MODULE_CODE_AVAILABLE', TRUE);
