<?php
/**
 * @file
 * Code for the solr_config feature.
 */

include_once 'solr_config.features.inc';

function solr_config_enable() {
  // add solr facet blocks to the search context
  $blocks = module_invoke_all('block_info');
  foreach($blocks as $key => $value) {
    if(is_string($value['info'])) {
      if(substr($value['info'], 0, 5) == 'Facet') {
		_add_block_context('search',$value['info'],'facetapi',$key, 'sidebar_first');
      }
    }
  }


}