<?php
/**
 * @file
 * Code for the newsletters feature.
 */

include_once('newsletters.features.inc');

/*
* hook_enable
*/
function newsletters_enable() {
  // add simplenews block to the site_wide context
  //_add_block_context('site_wide', '0', 'simplenews', '0', 'sidebar_first');
	
  // set by default newsletter format as HTML
  db_update('simplenews_category')
    ->fields(array('format' => 'html'))
    ->execute(); 
}


/*
* hook_disable
*/
function newsletters_disable() {
  // remove simplenews block to the site_wide context
  _remove_block_context('site_wide', '0');
  
  // disable the content type simplenews
  _disable_content_type('simplenews');
}


/*
* hook_menu
*/
function newsletters_menu() {
  $items['my_subscriptions'] = array(
    'title' => t('Newsletters'),
    'access callback' => TRUE,
    'page callback' => '_my_subscriptions',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 20,
  );
  return $items;
}

/*
* display the subcriptions management page
*/
function _my_subscriptions() {
  $block = module_invoke('simplenews', 'block_view', '0');
  return $block['content'];
}

