<?php

/**
 * @file
 * Code for the newsletters feature.
 */
include_once('newsletters.features.inc');

/*
 * hook_enable
 */

function newsletters_enable() {
    // add simplenews block to the site_wide context
    //_add_block_context('site_wide', '0', 'simplenews', '0', 'sidebar_first');
    // set by default newsletter format as HTML
    db_update('simplenews_category')
            ->fields(array('format' => 'html'))
            ->execute();

    //Add breadcrumb configuration
    db_insert('custom_breadcrumb')
            ->fields(array(
                'titles' => 'newsletter [simplenew:simplenews_term_alias]', // titles of the elements to display in the breadcrumb
                'paths' => '[simplenews:simplenews_term_alias]/', // path of the elements to display in the breadcrumb
                'visibility_php ' => '',
                'node_type' => 'simplenews', //the content type targeted by this rule
            ))
            ->execute();

    //Activation message
    drupal_set_message('Newsletters feature is now active on your site.');
}

/*
 * hook_disable
 */

function newsletters_disable() {
    // remove simplenews block to the site_wide context
    _remove_block_context('site_wide', '0');

    // disable the content type simplenews
    _disable_content_type('simplenews');
}

/*
 * hook_menu
 */

function newsletters_menu() {
    $items['my_subscriptions'] = array(
        'title' => t('Newsletters'),
        'access callback' => TRUE,
        'page callback' => '_my_subscriptions',
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'weight' => 20,
    );
    return $items;
}

/*
 * display the subcriptions management page
 */

function _my_subscriptions() {
    $block = module_invoke('simplenews', 'block_view', '0');
    return $block['content'];
}

/**
 * Implementation of hook_token_value().
 */
function newsletter_token_values($type, $object = NULL, $options = array()) {
    $values = array();
    $current_path = "";
    switch ($type) {        
        case 'all':
        case 'simplenews':
            $node = $object['node'];
            if ($node || (arg(0) == 'node' && arg(2) != 'edit')) {
                $system_path = 'node/' . arg(1);
                $current_path = drupal_get_path_alias($system_path);
            }
            $values["simplenews_term_alias"] = $current_path; //return the path alias
            break;
    }
    return $values;
}

/*
 *  allow to link all content types to the related_content field of the simplenews content
 */

function newsletters_field_create_field($field) {
    if ($field["field_name"] == 'field_related_contents') {
        $types = node_type_get_types();

        foreach ($types as $type => $value) {
            if ($type != 'simplenews')
                simplenews_related_content_type($type, 'add');
        }
    }
}