<?php
/**
 * @file
 * Code for the NextEuropa Core feature.
 */

include_once 'nexteuropa_core.features.inc';
include_once 'nexteuropa_core.tokens.inc';

/**
 * Implements hook_init()
 */
function nexteuropa_core_init() {

}

/**
 * Implements hook_migrate_api().
 */
function nexteuropa_core_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'NextEuropa' => array(
        'title' => t('Stage initial content, users and terms.'),
      ),
    ),    
    'migrations' => array(
      'NextEuropaCoreUserTasks' => array(
        'class_name' => 'NextEuropaCoreUserTasksMigration',
        'group_name' => 'NextEuropa',
      ),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function nexteuropa_core_form_taxonomy_overview_terms_alter(&$form, $form_state) {
  $form['#submit'][] = 'nexteuropa_core_form_taxonomy_overview_terms_submit';
}

/**
 * Implements form #submit callback.
 *
 * @see: nexteuropa_core_form_taxonomy_overview_terms_alter()
 */
function nexteuropa_core_form_taxonomy_overview_terms_submit($form, &$form_state) {
  module_load_include('inc', 'pathauto');

  // Re-create taxonomy terms URL aliases when terms are reshuffled
  // using a vocabulary's overview page, such as admin/structure/taxonomy/:vocabulary-name/list
  // This is necessary when using [term:parents-uri] custom token in path alias creation.
  // @see: nexteuropa_core_token_info_alter()
  foreach ($form_state['values'] as $key => $value) {
    if (strstr($key, 'tid:') !== FALSE) {
      $term = taxonomy_term_load($value['tid']);
      $uri = entity_uri('taxonomy_term', $term);
      pathauto_create_alias('taxonomy_term', 'update', $uri['path'], array('term' => $term), $term->vocabulary_machine_name);
    }
  }
}
