#!/bin/bash
current_script="$(readlink -f $0)"
script_dir="$(dirname "${current_script}")"

source "${HOME}/.bash_profile"
source "${script_dir}/lib/functions.sh"

function usage {
	output "Usage: $0 <drupal-directory> <target> <source-theme> <target-theme>"
	output '    drupal-directory is a Drupal base directory, i.e. a directory hosting the index.php file'
	output '    target is either a space-separated list of 1 to n subsites (as a single argument), or "@sites" for all known subsites'
	output '    All target sites using <source-theme> as their main theme will be switched to <target-theme>'
}

# Simple arguments check
drupal_path=$1
shift
target="$1"
shift
source_theme="$1"
shift
target_theme="$1"
[ -z "${drupal_path}" ] && usage && exit 50
[ -z "${target}" ] && usage && exit 48
[ -z "${source_theme}" ] && usage && exit 46
[ -z "${target_theme}" ] && usage && exit 44

if [ "${source_theme}" = "${target_theme}" ]; then
  echo "Target and source themes are the same, aborting."
  exit 42
fi

function do_action {
  subsite="${2}"
  theme_name=$(drush php-eval 'print $GLOBALS["theme_info"]->name;')
  if [ -z "${theme_name}" ]; then
    echo "Unable to retrieve the current theme name, aborting for site ${subsite}."
    subsite_state='nok'
    return
  fi

  if [ "${theme_name}" != "${source_theme}" ]; then
    echo "Current theme is \"${theme_name}\", leaving things untouched."
    return
  fi

  # Actual work
  echo "Current theme is \"${theme_name}\", switching to \"${target_theme}\"..."
  # Ensure the target theme is enabled
  run_drush --yes pm-enable "${target_theme}"
  run_drush --yes vset theme_default "${target_theme}"
  run_drush --yes cc all
}

loop_on_target_subsites "${drupal_path}" ${target} | timestamped_output
exit 0
