<?php
/**
 * @file
 * Code for the Links feature.
 */

include_once('links.features.inc');

/*
 * Hook enable 
 * Edit communities context to add a block
 */
function links_enable(){

  //Add block in context
  _add_block_context('communities','links-block','views','links-block', 'sidebar_first');
  _add_views_context('communities','links');
  _add_content_type_context('communities','links');
  
  drupal_set_message('Links feature is now active on your site.');

}


/*
 * Hook disable 
 * Edit communities context to remove block
 * Remove permissions
 */
function links_disable(){

  // Remove block
  _remove_block_context('communities', 'links-block');
  _remove_views_context('communities', 'links');
  _remove_content_type_context('communities','links');

  /*** Remove permissions ***/
  _disable_content_type('links');
  
  // Administrator
  $adm_rid = get_rid('administrator');
  user_role_revoke_permissions($adm_rid, array(
    'edit own links content',
    'edit any links content',
    'delete own links content',
    'delete any links content',
    'create links content',
  ));
    
  // Contributor
  $ctb_rid = get_rid('contributor');      
  user_role_revoke_permissions($ctb_rid, array(
    'edit own links content',
    'edit any links content',
    'delete own links content',
    'delete any links content',
    'create links content',
  ));
          
  // Disable permissions to OG roles ---------------------------------------------------------------  
  // Community Manager
  $cm_rid = get_og_rid('community_manager');
  og_role_revoke_permissions($cm_rid, array(
    'update own links content',
    'update any links content',
    'delete own links content',
    'delete any links content',
    'create links content',
  ));
    
  // Administrator Member
  $admm_rid = get_og_rid('administrator member');
  og_role_revoke_permissions($admm_rid, array(
    'update own links content',
    'update any links content',
    'delete own links content',
    'delete any links content',
    'create links content',
  ));
    
  drupal_flush_all_caches(); 
  drupal_set_message('Links feature is now disabled on your site.');
}


/*
* hook_node_insert
*/

 function links_node_insert($node) {
   if ($node->type == 'links' && $node->title == 'my link 1') {

    node_types_rebuild();

    drupal_set_message("Modifications occuring on node: " . $node->nid . '  -> Title: ' . $node->title . 'Updating permissions');
    //og_invalidate_cache();
    
    // Add permissions to roles ----------------------------------------------------------------------------------------------------------------------------------------------
    // Administrator
    $adm_rid = get_rid('administrator');
    user_role_grant_permissions($adm_rid, array(  
      'edit own links content',
      'edit any links content',
      'delete own links content',
      'delete any links content',
      'create links content',
    ));
    
    // Contributor
    $ctb_rid = get_rid('contributor'); 
    user_role_grant_permissions($ctb_rid, array(
      'edit own links content',
      'edit any links content',
      'delete own links content',
      'delete any links content',
      'create links content',
    ));
          
    // Add permissions to OG roles ---------------------------------------------------------------  
    // Community Manager
    $cm_rid = get_og_rid('community_manager');
    og_role_grant_permissions($cm_rid, array(
      'create links content',
      'update own links content',
      'update any links content',
      'delete own links content',
      'delete any links content',
    ));
      
    // Administrator Member
    $admm_rid = get_og_rid('administrator member');
    og_role_grant_permissions($admm_rid, array(
      'create links content',
      'update own links content',
      'update any links content',
      'delete own links content',
      'delete any links content',
    ));    
  }
}


/*
* hook_menu
*/
function links_menu() {
  $items = array();
 
  $items['community/%group_name/links'] = array(
    'title' => 'links',
    'page callback' => 'views_page',
    'page arguments' => array('links', 'page', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}