<?php
/**
 * @file
 * Code for the Multisite Charts feature.
 */

include_once 'multisite_charts.features.inc';


/**
 * Implements hook_requirements().
 */
function multisite_charts_requirements($phase) {
  $requirements = array();
  $requirements['multisite_charts']['title'] = t('Multisite Charts');
  if ($phase == 'runtime') {
    // Fusionchart SWF files
    $swf = glob(multisite_charts_get_library_path() . 'FusionCharts XT/Charts/*.swf');
    if (!empty($swf)) {
      $requirements['multisite_charts']['value'] = t('FusionCharts SWF files found.');
      $requirements['multisite_charts']['severity'] = REQUIREMENT_OK;
    }
    else {
      $requirements['multisite_charts']['value'] = t('FusionCharts SWF files not found.');
      $requirements['multisite_charts']['severity'] = REQUIREMENT_ERROR;
      $requirements['multisite_charts']['description'] = t('Please download these files from <a href="@url">http://www.fusioncharts.com</a> and copy them into the fusioncharts library directory as per instructions in the readme.txt file.', array('@url' => 'http://www.fusioncharts.com'));
    }

  }
  return $requirements;
}


/**
 * Implements hook_theme().
 */
function multisite_charts_theme($existing, $type, $theme, $path) {
  return array(
    'multisite_chart' => array(
      'variables' => array('info' => '', 'jsid' => NULL),
    ),
  );
}


/**
 * Chart rendering function
 *
 * @param array $info an array containing the chart data
 * @param string $jsid Name to be used for the id attribute in the DOM (used for javascript manipulation) optional
 * @return string the HTML to render the chart
 */
function theme_multisite_chart($variables) {
  $info = $variables['info'];
  $jsid = $variables['jsid'];
  static $chart_id; //incremental ID of each chart (static in case there is more then one chart on a page)
  if (!isset($chart_id)) {
    $chart_id = 1;
  }
  if (!isset($jsid)) {
    $jsid = 'Chart_' . $chart_id++;
  }

  $path = 'http://europa.eu/wel/fusioncharts/';
  $charts_path = $path . 'v0322/';

  include_once(multisite_charts_get_library_path() . 'Code/PHP/Includes/FusionCharts.php');
  //check that the fusioncharts package was installed
  if (!function_exists('renderChart')) {
    return t('Please install the Fusion Charts package from InfoSoft as per instructions in the readme.');
  }

  drupal_add_js($charts_path . 'FusionCharts.js');

  // Get the path of drupal instance
  $path_drupal = base_path();
  $swf_file = $charts_path . $info['type'] . '.swf';
  return renderChart($swf_file, '', $info['xml'], $jsid, $info['width'], $info['height']);
}

/**
 * Get the charts library path
 *
 * @return string
 */
function multisite_charts_get_library_path() {
  global $conf;

  $path = 'sites/all/libraries/FusionCharts/';
  $lpath = libraries_get_path('FusionCharts');
  if (isset($conf['fusion_charts_path'])) {
    $path = $conf['fusion_charts_path'];
  }
  elseif ($lpath) {
    $path = $lpath . '/';
  }
  return $path;
}

/**
 * Implements hook_node_view().
 */
function multisite_charts_node_view($node, $view_mode, $langcode) {
  if ('chart'==$node->type) {
    switch ($view_mode) {
      case 'full':
      case 'teaser':
        $chart_type_items = field_get_items('node', $node, 'field_chart_type');
        $chart_width_items = field_get_items('node', $node, 'field_chart_width');
        $chart_height_items = field_get_items('node', $node, 'field_chart_height');
        $chart_data_items = field_get_items('node', $node, 'field_chart_xml_data_source');

        $info = array();
        $info['type'] = $chart_type_items[0]['value'];
        if ('full'==$view_mode) {
          $info['width'] = $chart_width_items[0]['value'];
          $info['height'] = $chart_height_items[0]['value'];
        }
        else {
          $info['width'] = 400;
          $info['height'] = 300;
        }

        $info['xml'] = $chart_data_items[0]['xml'];

        $chart_out = theme('multisite_chart', array('info' => $info));
        $node->content['chart_area']['#markup'] = $chart_out;
        $node->content['chart_area']['#weight'] = 30;
        break;
    }
  }
}

