<?php

/**
 * @file
 * Code for the Links feature.
 */

include_once 'links_core.features.inc';

/**
 * Implements hook_token_info().
 */
function links_core_token_info() {
  $info['types']['Breadcrumb_links'] = array(
    'name' => t('Breadcrumb_links'),
    'description' => t('Tokens related to Breadcrumb.'),
  );
  $info['tokens']['Breadcrumb_links']["links_title"] = array(
    'name' => t("links Breadcrumb title"),
    'description' => t("The Breadcrumb title of the links."),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function links_core_tokens($type, $tokens, $data = array(), $options = array()) {
  $replacements = array();
  // Tokens for e_libray_core Breadcrumb.
  if ($type == 'Breadcrumb_links') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'links_title':
                    $replacements[$original] = t("links");
          break;
      }
    }
  }
  return $replacements;
}
