<?php
/**
 * @file
 * Nexteuropa_multilingual module file.
 */

include_once 'nexteuropa_multilingual.tokens.inc';

/**
 * Implements hook_module_implements_alter().
 */
function nexteuropa_multilingual_module_implements_alter(&$implementations, $hook) {
  // Make the following hooks exposed by nexteuropa_multilingual ran as last.
  $hooks = array(
    'language_switch_links_alter',
  );
  if (in_array($hook, $hooks)) {
    $group = $implementations['nexteuropa_multilingual'];
    unset($implementations['nexteuropa_multilingual']);
    $implementations['nexteuropa_multilingual'] = $group;
  }
}

/**
 * Implements hook_language_switch_links_alter().
 */
function nexteuropa_multilingual_language_switch_links_alter(array &$links, $type, $path) {

  // Implement language switcher behavior as per NEXTEUROPA-20.
  if (($node = menu_get_object('node'))) {
    $handler = entity_translation_get_handler('node', $node);
    $translations = $handler->getTranslations();
    if (empty($translations->original)) {
      $handler->initTranslations();
      $handler->saveTranslations();
    }
    foreach ($links as $key => $link) {
      if (!isset($translations->data[$key])) {
        unset($links[$key]);
      }
    }
  }
}

/**
 * Implements hook_language_negotiation_info().
 */
function nexteuropa_multilingual_language_negotiation_info() {
  $file = drupal_get_path('module', 'nexteuropa_multilingual') . '/nexteuropa_multilingual.callbacks.inc';
  $providers = array();
  $providers['nexteuropa_multilingual_url_suffix'] = array(
    'types' => array(
      LANGUAGE_TYPE_CONTENT,
      LANGUAGE_TYPE_INTERFACE,
      LANGUAGE_TYPE_URL,
    ),
    'callbacks' => array(
      'language' => 'nexteuropa_multilingual_language_negotiation_provider_callback',
      'url_rewrite' => 'nexteuropa_multilingual_language_negotiation_url_rewrite_callback',
      'switcher' => 'nexteuropa_multilingual_language_negotiation_switcher_url',
    ),
    'file' => $file,
    'weight' => -8,
    'name' => t('NextEuropa URL suffix'),
    'description' => t('Determine the language from the URL path suffix.'),
    'config' => 'admin/config/regional/language/configure/nexteuropa-url-suffix',
  );
  return $providers;
}


/**
 * Implements hook_menu().
 */
function nexteuropa_multilingual_menu() {
  $items['admin/config/regional/language/configure/nexteuropa-url-suffix'] = array(
    'title' => 'NextEuropa Language suffix delimiter',
    'description' => 'Settings to choose the language suffix delimiter in the url',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nexteuropa_multilingual_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Form callback.
 *
 * @see: nexteuropa_multilingual_menu()
 */
function nexteuropa_multilingual_form($form, &$form_state) {
  $form['nexteuropa_multilingual_language_suffix_delimiter'] = array(
    '#type' => 'textfield',
    '#maxlength' => 3,
    '#title' => t('Language suffix delimiter'),
    '#default_value' => variable_get('nexteuropa_multilingual_language_suffix_delimiter', '_'),
    '#description' => t('A character that separates language suffix from the actual URL, for example an underscore or a hyphen.'),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_language_types_info_alter().
 */
function nexteuropa_multilingual_language_types_info_alter(&$language_types) {
  $defined_providers = language_negotiation_info();
  if (isset($defined_providers['nexteuropa_multilingual_url_suffix'])) {
    // Put the locale-url-suffix as priority provider for language type url.
    array_unshift($language_types[LANGUAGE_TYPE_URL]['fixed'], 'nexteuropa_multilingual_url_suffix');
  }
}

/**
 * Implements hook_form_alter().
 */
function nexteuropa_multilingual_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'locale_languages_configure_form':
      $language_negotiation = variable_get('language_negotiation_language');
      // Disable URL method if URL-suffix method is enabled.
      if (isset($language_negotiation['nexteuropa_multilingual_url_suffix'])) {
        $form['language']['enabled']['locale-url']['#disabled'] = TRUE;
        $form['language_content']['enabled']['locale-url']['#disabled'] = TRUE;
      }
      break;
  }

  if (isset($form_state['build_info']['base_form_id']) && $form_state['build_info']['base_form_id'] == 'node_form') {
    $language_default = language_default();
    // Hide all languages except neutral language and default language
    // in node source form.
    if (isset($form_state['node'])) {
      if ($form_state['node']->language == LANGUAGE_NONE || $form_state['node']->language == $language_default->language) {
        // Check if node source or new node.
        if (isset($form['language']['#options'])) {
          foreach ($form['language']['#options'] as $lg => $language) {
            if ($lg != $language_default->language && $lg != LANGUAGE_NONE) {
              unset($form['language']['#options'][$lg]);
            }
          }
        }
      }
    }

    $warning_message = '<div class="alert alert-warning" role="alert" id="warning_languages_message">'
     . token_replace(variable_get('warning_message_languages'), array('node' => $form_state['node']))
     . '</div>';

    $form['warning_message_languages'] = array(
      '#markup' => $warning_message,
      '#weight' => 105,
      '#attached' => array(
        'css' => array(drupal_get_path('module', 'nexteuropa_multilingual') . '/nexteuropa_multilingual.css'),
      ),
    );
  }

  if ($form_id == 'workbench_moderation_moderate_form' || $form_id == 'workbench_moderation_node_unpublish_form') {
    $warning_message = '<div class="alert alert-warning" role="alert" id="warning_languages_message">'
     . token_replace(variable_get('warning_message_languages'), array('node' => $form_state['build_info']['args'][0]))
     . '</div>';

    $form['warning_languages_message'] = array(
      '#markup' => $warning_message,
      '#weight' => 105,
      '#attached' => array(
        'css' => array(drupal_get_path('module', 'nexteuropa_multilingual') . '/nexteuropa_multilingual.css'),
      ),
    );
  }

}

/**
 * Implements hook_tokens_alter().
 */
function nexteuropa_multilingual_tokens_alter(array &$replacements, array $context) {
  if ($context['type'] == 'node' && !empty($context['data']['node'])) {
    $node = $context['data']['node'];
    // IPG url rules : only the default language (should be english) title
    // must be used to generate the content url even for non translated content.
    $wrapper = entity_metadata_wrapper('node', $node);
    $original_language = $node->translations->original;
    $entity_properties = $wrapper->getPropertyInfo();
    // Check if the title module is used to manage the title as a field.
    if (isset($entity_properties['title_field'])) {
      $replacements['[node:source:title]'] = $wrapper->language($original_language)->title_field->raw();
    }
    else {
      $replacements['[node:source:title]'] = $wrapper->language($original_language)->label();
    }
  }
}

/**
 * Implements hook_language_fallback_candidates_alter().
 *
 * Change the language fallback order.
 */
function nexteuropa_multilingual_language_fallback_candidates_alter(array &$fallback_candidates) {
  // First we get our url parameters.
  $parameters = drupal_get_query_parameters();

  // Add the default language as first fallback.
  $language_default = language_default();
  $array_key = array_search($language_default->language, $fallback_candidates);
  if ($array_key !== FALSE) {
    unset($fallback_candidates[$array_key]);
  }
  array_unshift($fallback_candidates, $language_default->language);

  // Add the 2nd language as first fallback.
  if (isset($parameters['2nd-language'])) {
    $array_key = array_search($parameters['2nd-language'], $fallback_candidates);
    if ($array_key !== FALSE) {
      unset($fallback_candidates[$array_key]);
    }
    array_unshift($fallback_candidates, $parameters['2nd-language']);
  }
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function nexteuropa_multilingual_pathauto_alias_alter(&$alias, array &$context) {
  // Force all aliases to be saved as language neutral.
  // All content translations will have a unique alias.
  $context['language'] = LANGUAGE_NONE;
}

/**
 * Implements hook_preprocess_field().
 */
function nexteuropa_multilingual_preprocess_field(&$variables) {
  if (!empty($variables['label']) && isset($variables['label_hidden']) && $variables['label_hidden'] == FALSE) {
    if (isset($variables['element']['#object']->nid)) {
      $element = $variables['element'];
      // Get the field object and the field instance.
      $instance = field_info_instance($element['#entity_type'], $element['#field_name'], $element['#bundle']);
      $field = field_info_field($element['#field_name']);

      // The field language property respects the IPG language fallback,
      // but not its label and its value (for select list field).
      // Translate label.
      $variables['label'] = i18n_field_translate_property($instance, 'label', $element['#language']);
      // Translate field value (for select list field).
      if (isset($variables['items']['0']['#markup']) && $translated_value = i18n_field_translate_allowed_values($field, $element['#language'])) {
        foreach ($variables['items'] as $key => $item) {
          $variables['items'][$key]['#markup'] = $translated_value[$key];
        }
      }
    }
  }
}

/**
 * Implements hook_field_group_pre_render_alter().
 */
function nexteuropa_multilingual_field_group_pre_render_alter(&$element, &$group, $form) {
  // Field group label translation does not fit to the IPG language fallback.
  if (!empty($element['#title']) && isset($form['#entity_type'])) {
    $entity = NULL;
    $entity_map = array('user' => 'account' , 'taxonomy_term' => 'term');
    $entity_type = $form['#entity_type'];
    if (isset($form['#' . $entity_type])) {
      $entity = $form['#' . $entity_type];
    }
    elseif (isset($form['#' . $entity_map[$entity_type]])) {
      $entity = $form['#' . $entity_map[$entity_type]];
    }

    if ($entity) {
      $language_fallback = entity_translation_get_existing_language($entity_type, $entity);
      $element['#title'] = locale($group->label, '', $language_fallback);
      $group->label_language = $language_fallback;
    }
  }
}
