<?php
/**
 * @file
 * Provides functionality for the EC mapeditor tile layer.
 */

/**
 * Implements hook_layer_content_alter().
 *
 * See MapLayerController->buildContent();
 */
function ec_mapeditor_tile_layer_content_alter(&$content, $wrapper, $entity) {
  $layers = array();

  // Fetches map data from tile layer.
  if ($entity->type == 'tile_layer') {
    $settings = drupal_json_decode($wrapper->settings->value());
    $layers[] = array(
      'layer_settings' => $settings,
      'label' => $wrapper->title->value(),
      'id' => _ec_mapeditor_layer_id($wrapper->title->value()),
    );
    $content['#attached']['js'][] = array(
      'data' => array(
        'tile_layers' => $layers,
      ),
      'type' => 'setting',
    );
  }
  return $content;
}

/**
 * Implements hook_layer_info().
 *
 * Registers the name of the map layer sub module and which custom form
 * elements it wants to add to the map layer forms.
 */
function ec_mapeditor_tile_layer_info() {
  return array(
    'tile_layer' => array(
      'form_elements' => array('tiles', 'attribution'),
      'custom_js' => base_path() . drupal_get_path('module', 'ec_mapeditor_tile') . "/js/tile_layer.js?v=" . rand(0, 33333),
    ),
  );
}
