<?php
/**
 * @file
 * Code for the EC Profiles feature.
 */

include_once('ec_profiles.features.inc');

function ec_profiles_modules_enabled($modules) {
  if (in_array('ec_profiles', $modules)) { 
    drupal_set_message(t('EC Profiles feature is now active on your site.'));

    //Get role_id for the role
    $role_id = array_search('authenticated user', user_roles(TRUE));  

    user_role_grant_permissions($role_id, array(
      'access user profiles',
    ));
  }
}
function ec_profiles_disable() {
  
  
  //Get role_id for the role
  $role_id = array_search('authenticated user', user_roles(TRUE));
  
  user_role_revoke_permissions($role_id, array(
    'access user profiles',
  ));

  drupal_set_message(t('EC Profiles feature is now disabled on your site.'));	
}
