<?php

/**
 * @file
 * Code for the Multisite Business Indicators feature.
 */

include_once 'multisite_business_indicators_core.features.inc';

/**
 * Implements hook_permission().
 */
function multisite_business_indicators_core_permission() {
  return array(
    'access business indicators' => array(
      'title' => t('Access business indicators overview page'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function multisite_business_indicators_core_menu() {
  $items['admin/reports/business-indicators'] = array(
    'title' => 'Business Indicators',
    'description' => 'Access business indicators overview page and blocks.',
    'page callback' => 'multisite_business_indicators_core_page_callback_overview',
    'access arguments' => array('access business indicators'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements menu page callback.
 *
 * @see: multisite_business_indicators_core_menu()
 */
function multisite_business_indicators_core_page_callback_overview() {
  return '';
}

/**
 * Implements hook_libraries_info().
 */
function multisite_business_indicators_core_libraries_info() {

  $libraries['FusionCharts'] = array(
    'name' => 'FusionCharts',
    'vendor url' => 'http://www.fusioncharts.com',
    'download url' => 'http://www.fusioncharts.com/download/trials/',
    'version arguments' => array(
      'file' => 'Version.txt',
      'pattern' => '@FusionCharts\sXT\s\(v([0-9a-zA-Z\.]+)\)@',
      'lines' => 5,
      'cols' => 300,
    ),
    'files' => array(
      'js' => array('FusionCharts.js'),
      'php' => array('Code/PHP/Includes/FusionCharts.php'),
    ),
  );
  return $libraries;
}
