<?php

/**
 * @file
 * Code for the Links feature.
 */

include_once 'links_og.features.inc';
include_once 'links_og.views_alter.inc';

/**
 * Implements hook_menu().
 */
function links_og_menu() {
  $items = array();

  $items['community/%group_name/links'] = array(
    'title' => 'Links',
    'page callback' => 'views_page',
    'page arguments' => array('links', 'page', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}
