<?php

/**
 * @file
 * Code for the Links feature.
 */

include_once 'links_og.features.inc';
include_once 'links_og.views_alter.inc';

/**
 * Implements hook_modules_enabled().
 */
function links_og_modules_enabled($modules) {
  if (in_array('links_og', $modules)) {
    // Force feature revert to update og permissions.
    features_revert(array('links_og' => array('og_features_permission')));
  }
}

/**
 * Implements hook_menu().
 */
function links_og_menu() {
  $items = array();

  $items['community/%group_name/links'] = array(
    'title' => 'Links',
    'page callback' => 'views_page',
    'page arguments' => array('links', 'page', 1),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}
