<?php

/*
* hook_enable
*/
function survey_og_enable() {
  multisite_drupal_toolbox_add_views_context("communities", "surveys_list");
  //multisite_drupal_toolbox_add_block_context('communities', 'surveys_list-block_1', 'views', 'surveys_list-block_1', 'sidebar_first');
  multisite_drupal_toolbox_add_content_type_context('communities', 'webform');
  multisite_drupal_toolbox_add_path_context('communities', 'urvey_analysis/*');
  
  // override drupal variable defined in core feature
  variable_set('pathauto_node_webform_pattern', 'community/[node:group_audience]/survey/[node:title]');
  
  drupal_flush_all_caches();
}


/*
 * Hook disable 
 */
function survey_og_disable() {

  // Remove block
  multisite_drupal_toolbox_remove_views_context("communities", "surveys_list");
  //multisite_drupal_toolbox_remove_block_context('communities', 'surveys_list-block_1');
  multisite_drupal_toolbox_remove_content_type_context('communities', 'webform');
  
  // delete drupal variables
  variable_del('pathauto_node_webform_pattern');
}
