<?php
/**
 * @file
 * Code for the Survey feature.
 */

include_once('survey_og.features.inc');
include_once('survey_og.views_alter.inc');

/*
* hook_menu
*/
function survey_og_menu() {
  $items = array();
 
  $items['community/%group_name/survey'] = array(
    'title' => 'Survey',
    'page callback' => 'views_page',
    'page arguments' => array('surveys_list', 'page_1', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}



