<?php

/**
 * @file
 * Code for the Nexteuropa Notices feature.
 */

include_once 'nexteuropa_notices.features.inc';

/**
 * Implements hook_post_features_enable_feature().
 */
function nexteuropa_notices_post_features_enable_feature() {
  // Grant notices bean permissions for Administrator roles.
  $admin_rid = user_role_load_by_name('administrator');
  if ($admin_rid && isset($admin_rid->rid)) {
    user_role_grant_permissions($admin_rid->rid, array(
      'create any notice bean',
      'edit any notice bean',
      'view any notice bean',
      'delete any notice bean',
    ));
  }
  // Grant notices bean permissions for anonymous user role.
  user_role_grant_permissions('1', array(
    'view any notice bean',
  ));
  // Grant notices bean permissions for authenticated user role.
  user_role_grant_permissions('2', array(
    'view any notice bean',
  ));

  // Ensure bean entity is translatable.
  $entity_types = variable_get("entity_translation_entity_types", array());
  if (!empty($entity_types)) {
    $entity_types['bean'] = 'bean';
    variable_set("entity_translation_entity_types", $entity_types);
  }
}

/**
 * Implements hook_page_build().
 */
function nexteuropa_notices_page_build(&$page) {
  $path = drupal_get_path('module', 'nexteuropa_notices');
  $page['content']['#attached']['css'][] = array(
    'type' => 'file',
    'data' => $path . '/nexteuropa_notices.css',
  );
  $page['content']['#attached']['js'][] = array(
    'type' => 'file',
    'data' => $path . '/nexteuropa_notices.css',
    'scope' => 'footer',
    'weight' => 100,
  );
}

/**
 * Implements hook_preprocess_block().
 */
function nexteuropa_notices_preprocess_block(&$variables) {
  if (isset($variables['block']->module) && $variables['block']->module == 'bean') {
    foreach ($variables['elements']['bean'] as $content) {
      if (isset($content['#bundle']) && $content['#bundle'] == 'notice') {
        $variables['classes_array'][] = 'notice';
      }
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function nexteuropa_notices_preprocess_field(&$variables) {
  if (isset($variables['element']['#field_name']) && $variables['element']['#field_name'] == 'field_close_button') {
    if (isset($variables['element']['#items'][0]['value']) && $variables['element']['#items'][0]['value'] == 1) {
      $variables['items'][0]['#markup'] = '<div class="notice__btn-close"><button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-remove"></span></button></div>';
    }
  }
}
