<?php
/**
 * @file
 * Code for the Nexteuropa Notices feature.
 */

include_once 'nexteuropa_notices.features.inc';

/**
 * Implements hook_block_view_alters().
 */
function nexteuropa_notices_block_view_alter(&$data, $block) {
  static $js_included;
  if ($js_included && $js_included === TRUE) {
    return;
  }

  if (isset ($block->module) && $block->module == 'bean') {
    if (isset ($data['content']['bean'])) {
      foreach ($data['content']['bean'] as $key => $content) {
        if (isset($content['#bundle']) && $content['#bundle'] == 'notice') {
          if (isset ($content['field_close_button']['#items'][0]['value'])
            && $content['field_close_button']['#items'][0]['value'] == 1) {
            // Include JS here.
            // drupal_add_js ()
            $js_included = TRUE;
          }
        }
      }
    }
  }
}
