<?php

/**
 * @file
 * Code for the E-library feature.
 */

include_once 'e_library_og.features.inc';
include_once 'e_library_og.views_alter.inc';

/**
 * Implements hook_menu().
 */
function e_library_og_menu() {
  $items = array();
  $items['community/%group_name/e_library'] = array(
    'title' => 'E-Library',
    'page callback' => 'views_page',
    'page arguments' => array('e_library', 'page', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );
  return $items;
}
