<?php

/**
 * @file
 * Multisite dynamic_basetheme definition module.
 */

define('MULTISITE_DYNAMIC_BASETHEME_JQUERY_VERSION', '1.7');
define('MULTISITE_DYNAMIC_BASETHEME_JMUTLI_LOAD_ALWAYS', '1');
define('MULTISITE_DYNAMIC_BASETHEME_THEME_DEFAULT_KEY', '');

/**
 * Implements hook_form_BASE_FORM_ID_alter() for system_theme_settings().
 */
function multisite_dynamic_basetheme_form_system_theme_settings_alter(&$form, $form_state) {
  // Get current theme object.
  if (isset($form_state['build_info']['args'][0])) {
    $theme_key = $form_state['build_info']['args'][0];
    $themes = list_themes();
    $theme_object = $themes[$theme_key];

    if (isset($theme_object->base_theme)) {
      $form['base_theme_fieldset'] = array(
        '#type' => 'fieldset',
        '#title' => t('Base theme'),
        '#weight' => -100,
      );

      $default_value = (theme_get_setting('ec_resp_base_theme_of_subtheme', $theme_key)) ? theme_get_setting('ec_resp_base_theme_of_subtheme', $theme_key) : MULTISITE_DYNAMIC_BASETHEME_THEME_DEFAULT_KEY;

      $form['base_theme_fieldset']['ec_resp_base_theme_of_subtheme'] = array(
        '#type' => 'select',
        '#title' => t('Current base theme'),
        '#default_value' => $default_value,
        '#options' => multisite_dynamic_basetheme_get_base_theme_list($theme_key),
        '#description' => t('Select the base theme for this subtheme. Default correspond to the theme defined in the info file.'),
      );
      $form['#submit'][] = 'multisite_dynamic_basetheme_form_system_theme_settings_submit';

      // @todo $settings is unused in its scope.
      $var = 'theme_' . $theme_key . '_settings';
      $settings = variable_get($var);
    }
  }
}

/**
 * Submit function of 'system_theme_settings' form.
 *
 * Rebuild the themes information if ec_resp_base_theme_of_subtheme has changed.
 */
function multisite_dynamic_basetheme_form_system_theme_settings_submit($form, &$form_state) {
  $old_value = $form['base_theme_fieldset']['ec_resp_base_theme_of_subtheme']['#default_value'];
  $new_value = $form_state['values']['ec_resp_base_theme_of_subtheme'];
  if ($old_value !== $new_value) {
    _multisite_dynamic_basetheme_rebuild_system_theme();

    if ($new_value == MULTISITE_DYNAMIC_BASETHEME_THEME_DEFAULT_KEY) {
      $theme_key = $form_state['build_info']['args'][0];
      $theme_info_file = drupal_parse_info_file(drupal_get_path('theme', $theme_key) . "/$theme_key.info");
      $new_value = $theme_info_file['base theme'];
    }
    _multisite_dynamic_basetheme_jquery_modules_handle($new_value);
  }
}

/**
 * Handle jquery modules.
 */
function _multisite_dynamic_basetheme_jquery_modules_handle($base_theme) {
  // Enable-disable jquery modules.
  if (empty($base_theme)) {
    return;
  }
  // Enable-disable jquery modules only for multisite base theme changes.
  if (strpos($base_theme, 'ec_resp') !== 0 && _multisite_dynamic_basetheme_is_multisite_base_theme($base_theme) === FALSE) {
    return;
  }
  if ($base_theme == 'ec_resp') {
    // Assume ec_resp > 1.6, i.e. require jquery_update.
    if (!module_exists('jquery_update')) {
      module_enable(array('jquery_update'));
      variable_set('jquery_update_jquery_version', MULTISITE_DYNAMIC_BASETHEME_JQUERY_VERSION);
      variable_del('jqmulti_load_always');
    }
    if (module_exists('jqmulti')) {
      module_disable(array('jqmulti'));
    }
  }
  elseif ($base_theme <= 'ec_resp_16') {
    if (!module_exists('jqmulti')) {
      module_enable(array('jqmulti'));
    }
    if (module_exists('jquery_update')) {
      module_disable(array('jquery_update'));
      variable_set('jqmulti_load_always', MULTISITE_DYNAMIC_BASETHEME_JMUTLI_LOAD_ALWAYS);
      variable_del('jquery_update_jquery_version');
    }
  }
}

/**
 * Rebuild theme information.
 */
function _multisite_dynamic_basetheme_rebuild_system_theme() {
  drupal_static_reset("theme_get_setting");
  system_rebuild_theme_data();
  drupal_theme_rebuild();
}

/**
 * Return true if the theme is a multisite base theme.
 *
 * @param object $theme
 *   Theme object.
 *
 * @return bool
 *   true if the paramter is a multisite base theme.
 */
function _multisite_dynamic_basetheme_is_multisite_base_theme($theme) {
  if (is_object($theme)) {
    return isset($theme->info['multisite']) && $theme->info['multisite'] == 1;
  }
  return FALSE;
}

/**
 * Return list of available base theme (theme with 'multisite = 1').
 *
 * @return array
 *    available multisite base themes.
 */
function multisite_dynamic_basetheme_get_base_theme_list($theme_key = FALSE) {
  $options = array();
  $themes = list_themes();

  // Get all available themes.
  foreach ($themes as $theme_id => $theme_obj) {
    if (_multisite_dynamic_basetheme_is_multisite_base_theme($theme_obj)) {
      $options[$theme_id] = $theme_obj->info['name'] . " ($theme_id)";
    }
  }

  // Get the original base theme of $theme_key from info file.
  if ($theme_key) {
    $theme_info_file = drupal_parse_info_file(drupal_get_path('theme', $theme_key) . "/$theme_key.info");
    $theme_base_key = $theme_info_file['base theme'];

    // Check if the defined base theme exist and that is a multisite base theme.
    if (!isset($themes[$theme_base_key])) {
      $theme_base_name = t("BASE THEME NOT FOUND");
    }
    elseif (!_multisite_dynamic_basetheme_is_multisite_base_theme($themes[$theme_base_key])) {
      $theme_base_name = t("NOT A MULTISITE BASE THEME");
    }
    else {
      $theme_base_name = $themes[$theme_base_key]->info['name'];
    }

    $options_default[MULTISITE_DYNAMIC_BASETHEME_THEME_DEFAULT_KEY] = t("Default: @base_theme (@base_theme_key)", array("@base_theme" => $theme_base_name, "@base_theme_key" => $theme_base_key));
    $options = $options_default + $options;
    unset($options[$theme_base_key]);
  }

  return $options;
}

/**
 * Implements hook_system_info_alter().
 *
 * Rewrite 'base theme' of all subtheme with the setting
 * "ec_resp_base_theme_of_subtheme" (if defined).
 */
function multisite_dynamic_basetheme_system_info_alter(&$info, $file, $type) {
  if ($type == "theme" && isset($file->info['base theme'])) {
    $theme_key = $file->name;
    if ($new_base_theme = theme_get_setting('ec_resp_base_theme_of_subtheme', $theme_key)) {
      // If base theme is defined on sub-theme settings.
      if ($new_base_theme = theme_get_setting('ec_resp_base_theme_of_subtheme', $theme_key)) {
        // Cannot use theme_list in hook_system_info_alter: infinite loop in
        // case of MAINTENANCE_MODE defined.
        // Information is 'manually' retrieved,to check the basetheme coherence.
        if (drupal_get_path('theme', $new_base_theme) != '') {
          // Check if new_base_theme is a multisite base theme.
          $new_base_theme_obj = new stdClass();
          $new_base_theme_obj->info = drupal_parse_info_file(drupal_get_path('theme', $new_base_theme) . "/$new_base_theme.info");
          if (_multisite_dynamic_basetheme_is_multisite_base_theme($new_base_theme_obj)) {
            $info['base theme'] = $new_base_theme;
          }
        }
      }
    }
  }
}
