ReadSpeaker.ui=function(){var a=null,c=[],l=[],n=!1,k=null,j=function(d){$rs.focus&&("function"==typeof $rs.focus&&d)&&$rs.focus(d)},g=function(){"iconon"==rspkr.st.get("hlicon")&&n&&(l.pop().hide(),n=!1)},p=function(){var d=0,a=0,b=null,f=52,e=null,c=null,g=null,i=function(d){d=d||b;$rs.addClass(d,rspkr.ui.rsbtnClass+" rspopup");rspkr.cfg.item("general.useCompactPopupButton")&&$rs.addClass(d,"rscompact")},h=function(d){$rs.unregEvent(b,"mouseout",q);window.clearTimeout(e);var a;a=b.clientWidth+10;
var f,r;c=rspkr.ui.showPlayer(g,b,!0);f=c.getWidth();r=parseInt($rs.offset(b).left);rspkr.ui.viewport.width+$rs.scrollLeft(document)-r<f&&(a=parseInt($rs.css(b,"left"))-(f-(a-10)),$rs.css(b,"left",a+"px"));n=!1;$rs.unregEvent(g,"click",h);$rs.regEvent(g,"click",c.restart);d.originalEvent&&d.originalEvent.preventDefault&&d.originalEvent.preventDefault();return d.originalEvent.returnValue=!1},q=function(){e||(e=window.setTimeout(function(){k()},rspkr.cfg.item("general.popupCloseTime")||2E3))},r=function(){e&&
(window.clearTimeout(e),e=null)},j=function(d,a){var q=$rs.offset(document.body),e=document.createElement("div");e.id=rspkr.getID();e.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");i(e);$rs.css(e,{display:"block",position:"absolute",top:0,left:0});document.body.appendChild(e);f=$rs.outerWidth(e)+3;document.body.removeChild(e);$rs.css(b,{top:a-q.top+"px",left:d-q.left+"px",width:f+"px"})},k=function(){$rs.css(b,{display:"none",top:0,left:0});r();l.splice(null,1);n=!1;b.parentElement.removeChild(b)},
b=document.createElement("div");b.id=rspkr.getID();b.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");i();document.body.appendChild(b);var g=$rs.findIn(b,"a.rsbtn_play"),t;g.href=(t=rspkr.c.findFirstRSButton())?t.href:"";$rs.regEvent(g,"click",h);return{setPos:j,show:function(e){r(e);if(e&&"none"==$rs.css(b,"display")){var c=e.pageX,g=e.pageY;e.originalEvent.cancelBubble&&(e.originalEvent.cancelBubble=!0);e.originalEvent.stopPropagation&&e.originalEvent.stopPropagation();a=g>rspkr.ui.pointerY?
g-$rs.scrollTop(document)+36>rspkr.ui.viewport.height-46?g-56:g+20:10>g-$rs.scrollTop(document)-56?g+20:g-56;d=10>c-$rs.scrollLeft(document)?c+10:c-$rs.scrollLeft(document)>rspkr.ui.viewport.width-(f+10)?rspkr.ui.viewport.width+$rs.scrollLeft(document)-(f+10):c+0;j(d,a)}$rs.regEvent(b,"mouseout",q);$rs.regEvent(b,"mouseover",r);q(null);i();$rs.css(b,"display","block")},hide:k,id:null}},h={update:function(d,c,b){"hlspeed"===d&&c!==b&&(d=d.replace("hl",""),rspkr.c.converter[d]&&"function"==typeof rspkr.c.converter[d]&&
(c=rspkr.c.converter[d](c)),rspkr.c.data[d]=c,a.stop(),rspkr.pl.releaseAdapter())}},i=function(d,a,b,f,e,c){$rs.css(d,"background-color","rgb("+a+","+b+","+f+")");f<e?(f+=10,window.setTimeout(function(){i(d,a,b,f,e,c)},50)):c&&"function"===typeof c&&c.apply(d,[])};return{meta:{revision:"1316"},initrun:!1,init:function(){evt=rspkr.Common.addEvent;ui=rspkr.ui;evt("onModsLoaded",ui.initGlobalCallbacks);evt("onReady",ui.addClickEvents);evt("onReady",ui.processDeferred);evt("onSelectedText",ui.showPopupIcon);
evt("onDeselectedText",g);evt("onSettingsChanged",h.update);evt("onAfterSyncInit",ui.updateFocus);this.initrun=!0;rspkr.Common.dispatchEvent("onUIInitialized");rspkr.log("[rspkr.ui] Initialized!")},addFocusHandler:function(d,a,b){var f=a,e=b,e=e||d;void 0===f&&(f=!0);$rs.focusIn&&"function"==typeof $rs.focusIn&&($rs.focusIn(d,function(){$rs.addClass(e,"rsfocus");!0===f&&(k=d);rspkr.Common.dispatchEvent("onFocusIn",window,[d,e])}),$rs.focusOut(d,function(){$rs.removeClass(e,"rsfocus");rspkr.Common.dispatchEvent("onFocusOut",
window,[d,e])}))},focus:function(d){j(d)},updateFocus:function(){k&&(rspkr.log("[rspkr.ui.updateFocus] "+k.outerHTML),j(k))},showOverlay:function(d,c){var b=d,f;f=c||a.getContainer();var e=$rs.findIn(f,".rsbtn_status");0===e.length&&(e=document.createElement("span"),e.className="rsbtn_status_overlay",e.innerHTML='<span class="rsbtn_status"></span>',$rs.findIn(f,".rsbtn_exp").appendChild(e),e=$rs.findIn(f,".rsbtn_status"));"nosound"===b?(b='<a class="rsbtn_nosound">'+rspkr.cfg.getPhrase("nosound")+
"</a>",e.innerHTML=b,(b=$rs.findIn(f,".rsbtn_nosound"))&&$rs.regEvent(b,"click",function(){return a.nosound()})):e.innerHTML=b},settings:h,rsbtnClass:"",addClickEvents:function(){rspkr.log("[rspkr.ui] Attempting to add click events.");var d=$rs.get("."+rspkr.ui.rsbtnClass+" a.rsbtn_play");$rs.isArray(d)||(d=[d]);for(var a=0,b=d.length;a<b;a++){$rs.unregEvent(d[a],"click",ReadSpeakerDefer.clickhandler);$rs.regEvent(d[a],"click",function(b){window.readpage(this);b=b.originalEvent;b.preventDefault&&
b.preventDefault();return b.returnValue=!1});rspkr.ui.addFocusHandler(d[a],!0,d[a].parentNode);if(-1!==d[a].getAttribute("href").search(/readclass=/)){var f=d[a].getAttribute("href").match(/readclass=[^&]+/gi)[0].replace("readclass=","");rspkr.HL.Restore.Storage.readClass.push(f)}else if(-1!==d[a].getAttribute("href").search(/readid=/)){for(var f=[],e=d[a].getAttribute("href").match(/readid=[^&]+/gi)[0].replace("readid=","").split(","),c=0;c<e.length;c++)f.push(e[c]);rspkr.HL.Restore.Storage.readId.push(f)}rspkr.log("[rspkr.ui] Added click event to: "+
d[a])}},initGlobalCallbacks:function(){rspkr.log("[rspkr.ui] Initiating global callbacks");rspkr.ui.rsbtnClass=rspkr.cfg.item("ui.rsbtnClass")||"rsbtn";window.readpage=function(a,c){rspkr.ui.initrun&&rspkr.ui.showPlayer(a,c)};window.rshlexit=function(d){(void 0===d||"false"===d)&&a.stop()};window.rshlinit=rspkr.HL.sync.init;window.rshlsetContent=rspkr.HL.sync.setContent;window.rshlsetId=rspkr.HL.sync.setId;window.rshlsync=function(a,c){for(var b=a.split(","),f=c.split(","),e=0,g=a.length;e<g;e++)rspkr.HL.sync.execute(b[e],
f[e])};$rs.regEvent(document.body,"mousedown",rspkr.ui.setPointerPos);$rs.regEvent(document.body,"mouseup",function(a){rspkr.c.data.setSelectedText(a);return!0});$rs.regEvent(window,"mouseup",function(a){rspkr.c.data.setSelectedText(a);return!0});$rs.regEvent(document.body,"keydown",rspkr.ui.setPointerPos);$rs.regEvent(document.body,"keyup",function(a){rspkr.c.data.setSelectedText(a)})},showPopupIcon:function(a){if("iconon"==rspkr.st.get("hlicon")&&!n){var c=l.push(new p)-1;l[c].id=c;l[c].show(a);
n=!0}},processDeferred:function(){document.removeEventListener?document.removeEventListener("click",window.ReadSpeakerDefer.clickhandler):document.detachEvent&&document.detachEvent("onclick",window.ReadSpeakerDefer.clickhandler);if(ReadSpeakerDefer.deferred){var a=ReadSpeakerDefer.deferred,c=null;if("a"!=a.tagName.toLowerCase()){for(c=a;"body"!=c.tagName.toLowerCase()&&!(c=c.parentNode,"a"==c.tagName.toLowerCase()););a=c}ReadSpeakerDefer.isRSLink(a)&&(rspkr.log("[rspkr.ui] Activating deferred element: "+
a),$rs.removeClass(a.parentNode,"rsdeferred"),rspkr.ui.showPlayer(a));ReadSpeakerDefer.deferred=null}},showPlayer:function(d,g,b){rspkr.log("[rspkr.ui.showPlayer]");var b=b||!1,f;if("string"==typeof d)a:{f=$rs.get("a");for(var e=0,i=f.length;e<i;e++)if(f[e].href&&f[e].href==d){f=f[e];break a}f=!1}else f=d;e=null;rspkr.c.data.setParams("string"==typeof d?d:f.href);g&&!b?(e=$rs.get(g),$rs.addClass(e,rspkr.ui.rsbtnClass+" rsfloating")):e=$rs.closest(f,"div."+rspkr.ui.rsbtnClass);var h;a:{d=e;for(h in c)if(c[h].getContainer&&
c[h].getContainer()==d){h=c[h];break a}h=new rspkr.ui.Player(d);c.push(h)}a&&a!=h&&(a.close(!0),rspkr.c.dispatchEvent("onUIClosePlayer",a.getContainer(),[0<rspkr.c.data.selectedText.length?"textsel":"nosel"]));d=(d=a)?d.getID():null;rspkr.c.dispatchEvent("onUIShowPlayer",window,[d,h.getID()]);h.show();return a=h},pointerX:0,pointerY:0,setPointerPos:function(a){rspkr.ui.pointerX=a.pageX;rspkr.ui.pointerY=a.pageY;return!0},viewport:{width:$rs.width(window),height:$rs.height(window)},popups:l,hl:function(a,
c){window.setTimeout(function(){i(a,255,255,100,255,c)},200)},scroll:{INTERVAL:null,STEPS:25,scrollToElm:function(a){this.initScroll(a)},scrollToAnchor:function(a){for(var c=$rs.get("a"),b=null,f=0;f<c.length;f++){var e=c[f];if(e.name&&e.name==a){b=e;break}}this.initScroll(b)},initScroll:function(a){if(a){for(var c=a.offsetTop,b=a;b.offsetParent&&b.offsetParent!=document.body;)b=b.offsetParent,c+=b.offsetTop;c-=50;clearInterval(rspkr.u.scroll.INTERVAL);var b=rspkr.u.scroll.getCurrentYPos(),f=parseInt((c-
b)/rspkr.u.scroll.STEPS);rspkr.u.scroll.INTERVAL=setInterval(function(){rspkr.u.scroll.scrollWindow(f,c,a)},10)}else document.location.hash=a},getCurrentYPos:function(){return document.body&&document.body.scrollTop?document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:window.pageYOffset?window.pageYOffset:0},scrollWindow:function(a,c,b){var f=rspkr.u.scroll.getCurrentYPos(),e=f<c;window.scrollTo(0,f+a);a=rspkr.u.scroll.getCurrentYPos();
if(e!=a<c||f==a)window.scrollTo(0,c),clearInterval(rspkr.u.scroll.INTERVAL),"string"==typeof b&&(location.hash=b)}},activePlayer:a}}();
ReadSpeaker.ui.Slider=function(){var a=this,c={handleClass:"",width:0,height:0,left:0,top:0,steps:-1,stepsize:-1,dir:"h",initval:-1,drop:null,start:null,dragging:null,click:null,labelDragHandle:"",labelStart:"",labelEnd:""},l={rsid:void 0,parent:void 0,ref:void 0},n=5,k=void 0,j=void 0,g=void 0,p=void 0,h=void 0,i=void 0,d=void 0,m=!1;this.initElement=function(a){if(!m){"string"==typeof a&&(a=document.getElementById(a));a.innerHTML+='<a href="javascript:void(0);" role="slider" class="keyLink" style="display:block; border:0;">&nbsp;</a>';
var f=a.getElementsByTagName("a"),f=f[f.length-1],e=-1<c.steps?c.steps:100;f.relatedElement=a;$rs.setAttr(f,"title",c.labelDragHandle);$rs.setAttr(f,"aria-label",c.labelDragHandle);$rs.setAttr(f,"aria-orientation","h"==c.dir?"horizontal":"vertical");$rs.setAttr(f,"aria-valuemin",0);$rs.setAttr(f,"aria-valuemax",e);$rs.setAttr(f,"aria-valuenow",c.initval||0);$rs.regEvent(a,"mousedown",this.startDragMouse);$rs.regEvent(f,"keyup",this.startDragKeys);$rs.regEvent(f,"dragstart",function(a){a.originalEvent&&
a.originalEvent.preventDefault&&a.originalEvent.preventDefault();return a.originalEvent.returnValue=!1});$rs.regEvent(a,"touchstart",this.touchStart);$rs.regEvent(l.parent,"mousedown",this.mouseClick)}};this.mouseClick=function(b){if(!m&&!$rs.hasClass(l.ref,"dragged")){var f=a.findPos(b.target),e=b.clientX-(f.left-c.left),b=b.clientY-(f.top-c.top);g=f.left;p=f.top;f=a.getCurrentVal({left:e,top:b});"function"==typeof c.click&&c.click(f,l);return!1}};this.findPos=function(a){var c=curTop=0;if(a.offsetParent){do c+=
a.offsetLeft,curTop+=a.offsetTop;while(a=a.offsetParent);return{left:c,top:curTop}}};this.startDragMouse=function(b){rspkr.log("[rspkr.ui.Slider] startDragMouse");if(!m){a.startDrag(this);var c=b||window.event;k=c.clientX;j=c.clientY;$rs.regEvent(document.body,"mousemove",a.dragMouse);$rs.regEvent(document.body,"mouseup",a.releaseElement)}b.preventDefault&&b.preventDefault();return!1};this.startDragKeys=function(b){b=b||window.event;rspkr.log("[rspkr.ui.Slider] startDragKeys1 "+b.keyCode);13==b.keyCode&&
!m&&(rspkr.log("[rspkr.ui.Slider] startDragKeys"),a.startDrag(this.relatedElement),h=i=0,$rs.regEvent(document.body,"keydown",a.dragKeys),$rs.regEvent(document.body,"keypress",a.switchKeyEvents),$rs.addClass(this.relatedElement,"rskeycontrolled"));b.preventDefault&&b.preventDefault();return b.returnValue=!1};this.touchStart=function(b){b=b.originalEvent;rspkr.log("[rspkr.ui.Slider] touchStart");m||(a.startDrag(b.target),k=b.touches[0].pageX,j=b.touches[0].pageY,$rs.regEvent(b.target,"touchmove",a.touchMove),
$rs.regEvent(b.target,"touchend",a.releaseElement));return!1};this.startDrag=function(b){rspkr.log("[rspkr.ui.Slider] startDrag");d&&a.releaseElement();g=b.offsetLeft;p=b.offsetTop;d=b;$rs.addClass(d,"dragged");"function"==typeof c.start&&c.start(l)};this.dragMouse=function(b){b=b||window.event;a.setPosition(b.clientX-k,b.clientY-j);a.valueChanged=!0;return!1};this.touchMove=function(b){b=b.originalEvent;b.preventDefault();a.setPosition(b.touches[0].pageX-k,b.touches[0].pageY-j);a.valueChanged=!0;
return!1};this.dragKeys=function(b){b=b||window.event;switch(b.keyCode){case 37:case 63234:a.valueChanged=!0;h-=n;break;case 38:case 63232:a.valueChanged=!0;i-=n;break;case 39:case 63235:a.valueChanged=!0;h+=n;break;case 40:case 63233:a.valueChanged=!0;i+=n;break;case 13:case 27:return a.releaseElement(),!1;case 9:return a.releaseElement(),!0;default:return rspkr.log("[rspkr.ui.Slider] return TRUE"),!0}!0===a.valueChanged&&(rspkr.c.dispatchEvent("onUISliderMove"),a.setPosition(h,i));b.originalEvent&&
b.originalEvent.preventDefault&&b.originalEvent.preventDefault();b.returnValue=!1;rspkr.log("[rspkr.ui.Slider] ready to return!");return!1};this.setPosition=function(b,f){var e,h=!1;e=b;var i=g,j=c.left,k=c.width,q="left";"v"==c.dir&&(e=f,i=p,j=c.top,k=c.height,q="top");e=i+e;-1<c.stepsize&&((e+j)%c.stepsize?e=c.stepsize*Math.ceil(e/c.stepsize)+j:h=!0);e>k+j?e=k+j:e<j&&(e=j);h||(d.style[q]=e+"px","function"==typeof c.dragging&&c.dragging(a.getCurrentVal(),l))};this.switchKeyEvents=function(){$rs.unregEvent(document.body,
"keydown",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.regEvent(document.body,"keypress",a.dragKeys)};this.releaseElement=function(){rspkr.log("[rspkr.ui.Slider] releaseElement");$rs.unregEvent(document.body,"mousemove",a.dragMouse);$rs.unregEvent(document.body,"mouseup",a.releaseElement);$rs.unregEvent(document.body,"keypress",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.unregEvent(document.body,"keydown",a.dragKeys);$rs.unregEvent(d,"touchmove",
a.touchMove);$rs.unregEvent(d,"touchend",a.releaseElement);$rs.removeClass(d,"dragged");$rs.removeClass(d,"rskeycontrolled");$rs.removeClass(d,"rsmousecontrolled");var b=a.getCurrentVal();d=null;"function"==typeof c.drop&&!0===a.valueChanged&&c.drop(b,l);return a.valueChanged=!1};this.getCurrentVal=function(a){var f=c.width,e="left",d=c.left;"v"==c.dir&&(f=c.height,e="top",d=c.top);var g=-1<c.steps?c.steps:100,f=-1<c.stepsize?c.stepsize:f/g,a=a?a[e]:$rs.css(l.ref,e).replace(/px/i,"");pos=Math.round(a)-
d;a=Math.round(pos/f);"v"==c.dir&&(a=g-a);rspkr.log("[rspkr.ui.Slider] currentval: "+a);return a};return{init:function(b,f){"string"==typeof b&&(b=document.getElementById(b));if(b){var e=b.id||"data-readspeaker-slider-id-"+Math.floor(2E4*Math.random());b.setAttribute("data-readspeaker-slider-id-","data-readspeaker-slider-parent-"+e);var d={width:function(){return $rs.width(b)},height:function(){return $rs.height(b)}};if("object"==typeof f)for(var g in f)f.hasOwnProperty(g)&&void 0!==c[g]&&(c[g]=f[g]);
g=!1;var h;"rsbtn_volume_slider"===b.className&&("jquery"===rspkr.l.f.currentLib()&&1.5>parseFloat(jQuery.fn.jquery))&&(h=b.parentNode.style.display,b.parentNode.style.display="block",g=!0);c.width=d.width();c.height=d.height();g&&(b.parentNode.style.display=h);-1<c.steps&&(c.stepsize=("h"==c.dir?c.width:c.height)/c.steps);d=document.createElement("span");d.setAttribute("data-readspeaker-slider-id-",e);d.className=c.handleClass||"rsbtn_progress_handle rsimg";b.appendChild(d);l.rsid=e;l.parent=b;l.ref=
d;n=-1<c.stepsize?c.stepsize:n;e=$rs.css(d,"left");null!==e&&(c.left=parseInt(e.replace(/px/i,"")));e=$rs.css(d,"top");null!==e&&(c.top=parseInt(e.replace(/px/i,"")));-1<c.initval&&this.jumpTo(c.initval);c.labelStart&&(e=document.createElement("span"),e.className="slider-label-start",e.innerHTML=c.labelStart,b.appendChild(e));c.labelEnd&&(e=document.createElement("span"),e.className="slider-label-end",e.innerHTML=c.labelEnd,b.appendChild(e));a.initElement(d)}},jumpTo:function(a){if(isNaN(a))return!1;
var d=101,e=a;-1<c.steps&&(a=Math.round(a),d=c.steps+1);if(-1<a&&a<d){var g=c.width,h=c.left,i="left";"v"==c.dir&&(g=c.height,h=c.top,i="top",a=d-1-a);l.ref.style[i]=g/(d-1)*a+h+"px";$rs.setAttr($rs.findIn(l.ref,"a.keyLink"),"aria-valuenow",e)}},getInstance:function(){return l},getContainer:function(){return l.parent},getAttr:function(a){return $rs.getAttr(l.parent,"data-readspeaker-"+a)},setAttr:function(a,c){$rs.setAttr(l.parent,"data-readspeaker-"+a,c)},releaseElement:function(){a.releaseElement()},
startDragKeys:function(b,c){a.startDragKeys.call(b,c)},disabled:function(){if(arguments)m=arguments[0];else return m}}};
ReadSpeaker.ui.Player=function(a){var c=rspkr.getID(),l=this,n=[],k=0,j=!1,g={_play:null,_pause:null,_stop:null,_vol:null,_settings:null,_dl:null,_closer:null,_powered:null,_get:function(b,c){var d,b="_"+b;d=a?this[b]&&0<this[b].length?this[b]:this[b]=$rs.findIn(a,c):null;return d==[]?null:d},play:function(){return this._get("play",".rsbtn_play")},pause:function(){return this._get("pause",".rsbtn_pause")},stop:function(){return this._get("stop",".rsbtn_stop")},vol:function(){return this._get("vol",
".rsbtn_volume")},settings:function(){return this._get("settings",".rsbtn_settings")},dl:function(){return this._get("dl",".rsbtn_dl")},powered:function(){return this._get("powered",".rsbtn_powered")},closer:function(){return this._get("closer",".rsbtn_closer")},nosound:function(){return this._get("nosound",".rsbtn_nosound")},setPlayPause:function(a){rspkr.log("[rspkr.ui.Player.setPlayPause("+a+")]");a=a?$rs.getAttr(this.pause(),"data-rsphrase-play"):$rs.getAttr(this.pause(),"data-rsphrase-pause");
$rs.setAttr(this.pause(),"title",rspkr.c.decodeEntities(a));$rs.findIn(this.pause(),".rsbtn_btnlabel").innerHTML=a}},p=!1,h=[],i={play:function(){rspkr.c.dispatchEvent("onUIBeforePlay");rspkr.log("[rspkr.ui.handlers.play]");h.progress&&h.progress.disabled(!1);$rs.removeClass(a,"rsstopped rspaused");$rs.addClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");$rs.addClass(a,"rsplaying");g.setPlayPause(!1);rspkr.pl.play();h.progress&&("0"!=h.progress.getAttr("current")&&rspkr.pl.setProgress(h.progress.getAttr("current")/
1E3),window.setTimeout(function(){rspkr.pl.getProgress.apply(rspkr.pl,[!0,m,l])},500));rspkr.c.dispatchEvent("onUIAfterPlay");rspkr.cfg.execCallback("cb.ui.play",a)},pause:function(){rspkr.log("[rspkr.ui.handlers.pause]");$rs.removeClass(a,"rsstopped rsplaying");$rs.addClass(a,"rspaused");g.setPlayPause(!0);rspkr.pl.pause();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIPause");rspkr.cfg.execCallback("cb.ui.pause",a);rspkr.log("ReadSpeaker.ui.pause")},stop:function(){rspkr.log("[rspkr.ui.handlers.stop]");
h.progress&&h.progress.disabled(!0);$rs.removeClass(a,"rspaused rsplaying");$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");$rs.addClass(a,"rsstopped");g.setPlayPause(!0);h.progress&&(h.progress.jumpTo(0),h.progress.setAttr("current",0),d(0));rspkr.pl.stop();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIStop",a);rspkr.cfg.execCallback("cb.ui.stop",a);rspkr.log("ReadSpeaker.ui.stop")},vol:function(b){var c=$rs.findIn(a,".rsbtn_volume_container"),d=$rs.findIn(a,".rsbtn_volume"),
b=b.originalEvent,e=function(a){var b=a.originalEvent,b=$rs.closest(b.srcElement||b.originalTarget,".rsbtn_volume_container");if("none"===$rs.css(c,"display"))return!1;if("click"===a.type){if(void 0===b||$rs.isArray(b)&&!b.length)$rs.css(c,"display","none"),$rs.unregEvent(document.body,"click",e)}else"keyup"===a.type&&27===a.keyCode&&($rs.css(c,"display","none"),$rs.unregEvent(document.body,"keyup",e))};$rs.css(c,"left",d.offsetLeft+"px");$rs.css(c,"display","none"==$rs.css(c,"display")?"block":"none");
"block"===$rs.css(c,"display")&&($rs.regEvent(document.body,"click",e),$rs.regEvent(document.body,"keyup",e));b&&b.stopPropagation&&b.stopPropagation();b.cancelBubble=!0;return!1},settings:function(){this.pause();rspkr.ui.Lightbox.show(rspkr.st.getHTML(),rspkr.st.getButtons(),!0,function(a){rspkr.c.dispatchEvent("onSettingsLoaded",window,[]);rspkr.cfg.execCallback("cb.ui.settingsopened",a)})},close:function(b){var b=b||!1,c=rspkr.pl;b||rspkr.cfg.execCallback("cb.ui.beforeclose",a);c.hasOwnProperty("getProgress")&&
rspkr.pl.getProgress(!1);c.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter();h.progress&&(h.progress.jumpTo(0),h.progress.setAttr("current",0));$rs.removeClass(a,"rsstopped rsplaying rspaused rsexpanded");$rs.hasClass(a,"rsfloating")&&$rs.removeClass(a,rspkr.ui.rsbtnClass);g.setPlayPause(!0);$rs.hasClass(a,"rspopup")&&($rs.removeClass(a,"rspopup"),$rs.css(a,"display","none"),a.parentNode.removeChild(a));$rs.css(a,"width","auto");b||(rspkr.c.dispatchEvent("onUIClosePlayer",a,["userclick"]),
rspkr.cfg.execCallback("cb.ui.close",a),rspkr.log("ReadSpeaker.ui.close: "+a));rspkr.ui.focus($rs.findIn($rs.get(a),".rsbtn_play"))},dl:function(){this.pause();var a=rspkr.c.data.getSaveData("dialog"),b=!1;rspkr.log("[rspkr.ui.handlers.dl] Savelink: "+a);rspkr.u.Lightbox.show(this.getDlDialog(),this.getDlButtons(),!0,function(){var c=$rs.get("#rsdl_button_accept"),d=$rs.get("#rsdl_button_decline");c&&$rs.regEvent(c,"click",function(){rspkr.u.Lightbox.hide();b="iOS"!==rspkr.c.data.browser.OS&&0<rspkr.c.data.selectedHTML.length?
!0:"iOS"!==rspkr.c.data.browser.OS&&!0===rspkr.cfg.item("general.usePost")?!0:!1;if(!0===b){var d=null;if(document.getElementById("dliframe"))d=document.getElementById("dliframe");else{if(document.selection)try{d=document.createElement('<iframe name="dliframe">')}catch(e){d=document.createElement("iframe")}else d=document.createElement("iframe");d.name="dliframe";d.setAttribute("id","dliframe");d.setAttribute("style","display: none; position: absolute;");d.style.display="none";var f=document.getElementsByTagName("body"),
g=null;0<f.length&&(g=f.item(0));if(g)g.appendChild(d);else return}d.src=a;return!1}$rs.setAttr(c,"href",a);return!0});d&&($rs.regEvent(d,"click",rspkr.u.Lightbox.hide),setTimeout(function(){rspkr.ui.focus(d)},200))})},getDlDialog:function(){var a=rspkr.cfg.item("ui.dldialog").join("\n"),b={};b.rsTERMS_OF_USE_HEADINGrs=rspkr.cfg.getPhrase("touheading");b.rsTERMS_OF_USE_BODYrs=rspkr.cfg.getPhrase("toubody");return rspkr.st.r().replaceTokens(a,b)},getDlButtons:function(){var a=rspkr.cfg.item("ui.dlbuttons").join("\n"),
b={};b.rsTERMS_OF_USE_ACCEPTrs=rspkr.cfg.getPhrase("touaccept");b.rsTERMS_OF_USE_DECLINErs=rspkr.cfg.getPhrase("toudecline");return rspkr.st.r().replaceTokens(a,b)},nosound:function(){var a=rspkr.c.data.getSaveData("link");$rs.setAttr(g.nosound(),"href",a);return!0}},d=function(b){var b=100<b?100:b,c=$rs.findIn(a,".rsbtn_progress_played");"object"===typeof c&&$rs.css(c,"width",b+"%");rspkr.cfg.execCallback("cb.ui.progresschanged",a,[b])},m=function(c){if(c.length){var e=parseInt(c[0]),c=parseInt(c[1]),
f=0==c?0:Math.round(100*(e/c)),g=$rs.findIn(a,".rsbtn_current_time"),i=$rs.findIn(a,".rsbtn_total_time"),j,k;p||(h.progress.jumpTo(f),d(f),g&&(g.innerHTML=j=b(e)),i&&(i.innerHTML=k=b(c)),rspkr.cfg.execCallback("cb.ui.timeupdated",a,[j,k]));h.progress.setAttr("current",e);h.progress.setAttr("buffered",c);rspkr.log("[rspkr.player.updateProgress] current time: "+e+" total time: "+c);0<e&&$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading")}},b=function(a){var a=a/1E3,b=parseInt(a%60),
c=parseInt(a/60%60),a=parseInt(a/60/60%60);return(10>a?"0"+a:a.toString())+":"+(10>c?"0"+c:c.toString())+":"+(10>b?"0"+b:b.toString())},f=function(){p=!0},e=function(a){a=a/100*h.progress.getAttr("buffered")/1E3;rspkr.pl.setProgress(a);p=!1},u=function(a){e(a)},s=function(b){b=0>b?0:20*b;h.vol&&h.vol.jumpTo(b/20);rspkr.pl.setVolume(b);rspkr.cfg.execCallback("cb.ui.volumechanged",a,[b]);return!1},v=function(a,b){rspkr.log("[rspkr.ui.Player] focus("+a.className+")");if("keyLink"===a.className){var c=
"";-1!==b.className.indexOf("volume_handle")?c="vol":-1!==b.className.indexOf("progress_handle")&&(c="progress");h[c].startDragKeys(a,{keyCode:13})}},w=function(a,b){rspkr.log("[rspkr.ui.Player] focus("+a.className+")");if("keyLink"===a.className){var c="";-1!==b.className.indexOf("volume_handle")?c="vol":-1!==b.className.indexOf("progress_handle")&&(c="progress");h[c].releaseElement();p=!1}};return{init:function(){n.push([this.show,[]])},show:function(){$rs.rsid(a);a.id=c=a.id||rspkr.getID();ui=
rspkr.ui;$rs.hasClass(a,rspkr.ui.rsbtnClass)||$rs.addClass(a,rspkr.ui.rsbtnClass);if(0==$rs.findIn(a,".rsbtn_exp").length){var b=null,d=rspkr.cfg,l=$rs.hasClass(a,"rspopup")?d.item("ui.popupplayer"):d.item("ui.player"),d=rspkr.cfg.getPhrases(rspkr.c.data.getParam("lang")),b=document.createElement("span");b.className="rsbtn_exp rsimg rspart";b.innerHTML+=l.join("\n");a.appendChild(b);"fallback"===rspkr.pl.adapter&&rspkr.ui.showOverlay("nosound",a);if(d){g.pause()&&($rs.setAttr(g.pause(),"data-rsphrase-pause",
d.pause),$rs.setAttr(g.pause(),"data-rsphrase-play",d.play),$rs.setAttr(g.pause(),"title",rspkr.c.decodeEntities(d.pause)));g.stop()&&$rs.setAttr(g.stop(),"title",rspkr.c.decodeEntities(d.stop));g.vol()&&$rs.setAttr(g.vol(),"title",rspkr.c.decodeEntities(d.volume));g.settings()&&$rs.setAttr(g.settings(),"title",rspkr.c.decodeEntities(d.settings));g.dl()&&$rs.setAttr(g.dl(),"title",rspkr.c.decodeEntities(d.download));if(g.powered()){var b=$rs.findIn(g.powered(),".rsbtn_btnlabel"),l=d.speechenabled.match(/.*href="([^"]*)"/i).pop(),
m=document.createElement("p");m.innerHTML=d.speechenabled;m=m.innerText||m.textContent;b&&(b.innerHTML=d.speechenabled);$rs.setAttr(g.powered(),"title",m);$rs.setAttr(g.powered(),"data-readspeaker-href",l);$rs.regEvent(g.powered(),"click",function(){window.open($rs.getAttr(this,"data-readspeaker-href"))})}g.closer()&&$rs.setAttr(g.closer(),"title",rspkr.c.decodeEntities(d.closeplayer))}d=rspkr.c.data.browser;(!/safari/i.test(d.name)||!/iphone|ipad|ios/i.test(d.OS))&&$rs.addClass(a,"rs-no-touch")}$rs.addClass(a,
"rsexpanded");if(!j){g.stop()&&($rs.regEvent(g.stop(),"click",function(){i.stop()}),ui.addFocusHandler(g.stop()));g.pause()&&($rs.regEvent(g.pause(),"click",function(){$rs.hasClass(a,"rsplaying")?i.pause():($rs.hasClass(a,"rsstopped")||$rs.hasClass(a,"rspaused"))&&i.play()}),ui.addFocusHandler(g.pause()));g.closer()&&($rs.regEvent(g.closer(),"click",function(){i.close()}),ui.addFocusHandler(g.closer()));g.vol()&&($rs.regEvent(g.vol(),"click",function(a){i.vol(a)}),ui.addFocusHandler(g.vol()));g.dl()&&
($rs.regEvent(g.dl(),"click",function(){return i.dl()}),ui.addFocusHandler(g.dl()));g.settings()&&($rs.regEvent(g.settings(),"click",function(){i.settings()}),ui.addFocusHandler(g.settings()));if($rs.findIn(a,".rsbtn_powered")&&(d=$rs.findIn(a,".rsbtn_powered .rsbtn_btnlabel a")))d.innerHTML='<span class="rsbtn_label_read">Read</span><span class="rsbtn_label_speaker">Speaker</span><span class="rsbtn_label_icon rsimg"></span>';d=rspkr.cfg;$rs.isArray($rs.findIn($rs.get(a),".rsbtn_progress_container"))||
(h.progress=new rspkr.ui.Slider,h.progress.init($rs.findIn($rs.get(a),".rsbtn_progress_container"),{handleClass:d.item("ui.progressHandleClass")||"rsbtn_progress_handle rsimg",dir:d.item("ui.progressDir")||"h",start:f,drop:e,click:u,labelDragHandle:d.getPhrase("sliderseek")}),h.progress.setAttr("current",0),h.progress.setAttr("buffered",0),b=$rs.findIn($rs.get(a),".rsbtn_progress_handle a"),ui.addFocusHandler(b,!1,b.parentNode));$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))||(h.vol=new rspkr.ui.Slider,
h.vol.init($rs.findIn(a,".rsbtn_volume_slider"),{handleClass:d.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:d.item("ui.volumeDir")||"v",steps:5,initval:5,drop:s,click:s,labelDragHandle:d.getPhrase("slidervolumedesc")}),b=$rs.findIn($rs.get(a),".rsbtn_volume_handle a"),ui.addFocusHandler(b,!1,b.parentNode));rspkr.Common.addEvent("onFocusIn",v);rspkr.Common.addEvent("onFocusOut",w);rspkr.cfg.execCallback("cb.ui.open",a);j=!0}h.progress&&"0"!=h.progress.getAttr("current")&&(rspkr.pl.releaseAdapter(),
h.progress.setAttr("current",0));"fallback"!==rspkr.pl.adapter&&(i.play(),rspkr.ui.focus(g.pause()));d=(d=a)||a;d=$rs.clone(d,!0,!0);d.id=rspkr.getID();document.body.appendChild(d);$rs.css(d,{position:"absolute",top:"0",left:"0",display:"block",width:"auto"});$rs.css(d,"float","none");$rs.addClass(d,"rsexpanded");b=$rs.outerWidth(d)+3;d.style.display="none";document.body.removeChild(d);k=b;$rs.css(a,"width",k+(/[Ee]xplorer/.test(ReadSpeaker.c.data.browser.name)?1:0)+"px")},close:function(a){i.close(a)},
stop:function(){i.stop()},nosound:function(){return i.nosound()},restart:function(){rspkr.log("[rspkr.ui.restart]");i.stop();window.setTimeout(function(){i.play()},500);return!1},updateProgress:function(a){m(a)},setProgress:function(a){e(a)},getContainer:function(){return a},getID:function(){return c},getWidth:function(){return k}}};
ReadSpeaker.ui.Lightbox=function(){var a=null,c=null,l=null,n=null,k=null,j=null,g,p=function(){$rs.css(j,"display","none");var a=$rs.height(window),d=$rs.height(document),c=parseInt($rs.css(document.documentElement,"width")),b=$rs.width(document),f=$rs.absOffset(document.body),e=0,h=0;isNaN(c)&&(c=$rs.width(window));f.left&&(h=f.left);f.top&&(e=f.top);$rs.css(k,{width:(b>c?b:c)+"px",height:(d>a?d:a)+"px",top:"-"+e+"px",left:"-"+h+"px"});$rs.css(j,"display","block");a=$rs.outerWidth(j);d=$rs.outerHeight(j);
c=$rs.width(window);b=$rs.height(window);d=g+80+50<b?g+80:b-50;j.style.height=d+"px";$rs.get("#rslightbox_content").style.height=d-80+"px";d>b?(j.style.top=$rs.scrollTop(document)+"px",j.style.marginTop="10px"):(j.style.top=b/2+"px",j.style.marginTop=-(d/2-$rs.scrollTop(document))+"px");a>c?(j.style.left=$rs.scrollLeft(document)+"px",j.style.marginLeft="0"):(j.style.left="50%",j.style.marginLeft=-(a/2-$rs.scrollLeft(document))+"px")},h=function(a){27===a.keyCode&&rspkr.ui.Lightbox.hide()};return{init:function(){var g=
rspkr.pub.Config;a=g.item("ui.overlay.overlayStyles");c=g.item("ui.overlay.contentStyles");l=g.item("ui.overlay.contentTemplate");rspkr.log("[rspkr.ui.Lightbox] Heartbeat!")},show:function(i,d,m,b){i=i||"";m=m||!1;k?(k.style.display="",j.style.display=""):(k=document.createElement("div"),k.id="rslightbox_overlay",j=document.createElement("div"),j.id="rslightbox_contentcontainer",j.innerHTML=rspkr.st.r().replaceTokens(l.join("\n"),{rsLIGHTBOX_CLOSE_LABELrs:rspkr.cfg.getPhrase("close")}),$rs.setAttr(k,
"style",a.join(";")),$rs.setAttr(j,"style",c.join(";")),document.body.appendChild(k),document.body.appendChild(j),rspkr.evt("onSettingsLoaded",{func:rspkr.st.r().handlers.changed.addButtonEvents,context:rspkr.st.r().handlers.changed,params:[this]}));var f=$rs.get("rslightbox_closer");rspkr.ui.addFocusHandler(f,!1);$rs.regEvent(f,"click",rspkr.ui.Lightbox.hide);$rs.regEvent(k,"click",rspkr.ui.Lightbox.hide);$rs.regEvent(document.body,"keyup",h);if((f=document.documentElement)&&document.all)f.style.overflowX=
f.style.overflowY="hidden";if(i!=n||m)$rs.get("#rslightbox_content").innerHTML="",$rs.css("#rslightbox_content","height","auto"),/^http/i.test(i)?$rs.findIn("#rslightbox_content","iframe").length||(d=document.createElement("iframe"),d.src=i,d.className="rslightbox-iframe",$rs.get("#rslightbox_content").appendChild(d)):("<"==i.substr(0,1)&&($rs.get("#rslightbox_content").innerHTML=i),$rs.get("#rslightbox_buttons").innerHTML=d),n=i;g=$rs.get("#rslightbox_content").clientHeight;i=$rs.findIn("#rslightbox_content",
".rsform-row");for(m=0;m<i.length;m++){d=$rs.findIn(i[m],"input, a, select");$rs.isArray(d)||(d=[d]);for(f=0;f<d.length;f++)rspkr.ui.addFocusHandler(d[f],!1,i[m])}var e=$rs.findIn("#rslightbox_content","input");$rs.isArray(e)&&0<e.length?setTimeout(function(){rspkr.ui.focus(e[0])},200):$rs.isArray(e)||setTimeout(function(){rspkr.ui.focus(e)},200);p();$rs.regEvent(window,"resize",p);"function"==typeof b&&b.apply(this,[j])},hide:function(){k.style.display="none";j.style.display="none";$rs.unregEvent(window,
"resize",p);$rs.unregEvent($rs.get("#rslightbox_closer"),"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(k,"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(document.body,"keyup",h);var a;if((a=document.documentElement)&&document.all)a.style.overflowX=a.style.overflowY="auto";rspkr.ui.updateFocus()}}}();
