<?php

/**
 * @file
 * Multisite Create button module.
 */

/**
 * Implements hook_block_info().
 */
function multisite_create_button_block_info() {
  $blocks['create-content-button'] = array(
    'info' => t('Create content button'),
  );

  $blocks['og-contextual-links'] = array(
    'info' => t('OG Contextual Links'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function multisite_create_button_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'create-content-button':
      $block['subject'] = t('Create content');
      $block['content'] = _multisite_create_button_contextual_links();
      break;

    case 'og-contextual-links':
      $block['subject'] = t('Create content');
      $block['content'] = _multisite_create_button_contextual_links();
      break;
  }

  return $block;
}

/**
 * Helper function to fetch the links.
 */
function _multisite_create_button_contextual_links() {
  global $theme_key;
  $element = NULL;
  $content = system_admin_menu_block(menu_get_item('node/add'));
  $context = og_context();
  $profile = drupal_get_profile();
  $options = array();
  if ($profile == 'multisite_drupal_standard') {
    if (!empty($content) && $context) {
      $options = array(
        '#' => t('Create content'),
      );
      foreach ($content as $content_type) {
        $options[url($content_type['link_path'], array('absolute' => TRUE))] = $content_type['link_title'];
      }
      $element = og_node_create_links('node', $context['gid'], 'og_group_ref');
      if ($element) {
        $element['og_node_create_links']['#theme'] = 'dropdown';
      }
    }
    $element['#options'] = $options;
  }

  if ($profile == 'multisite_drupal_communities') {
    if ($context) {
      // Use different theme components for the different themes.
      if ($theme_key == 'ec_resp') {
        $links = og_node_create_links('node', $context['gid'], 'og_group_ref');
        if ($links) {
          $links['og_node_create_links']['#theme'] = 'dropdown';
        }
      }
      else {
        $types = array_keys(node_type_get_types());
        foreach ($types as $type_name) {
          // Show only the options to create content for this community.
          $instance = field_info_instance('node', 'og_group_ref', $type_name);
          if (empty($instance['settings']['behaviors']['prepopulate']['status'])) {
            // Instance doesn't allow prepopulating.
            continue;
          }
          $names[$type_name] = node_type_get_name($type_name);
        }
        if (empty($names)) {
          return;
        }
        // Sort names.
        asort($names);
        // Build links with queries.
        $query = array(
          'og_group_ref' => $context['gid'],
        );

        $query += drupal_get_destination();

        $options = array(
          '#' => t('Create content'),
        );
        foreach ($names as $content_type) {
          // Links for the select options, for each content type.
          $options[url('node/add/' . drupal_strtolower($content_type), array('absolute' => TRUE, 'query' => $query))] = $content_type;
        }
        $links = array(
          '#theme' => array('select__create_content_button'),
          '#title' => t('Create content'),
          '#options' => $options,
          '#attributes' => array(
            'onChange' => 'if (this.value) window.location.href=this.value;',
          ),
        );
      }
      $element = $links;
    }
  }
  return $element;
}
