<?php

/**
 * @file
 * Provides Google Translator ui controller.
 */

/**
 * DGT connector translator ui controller.
 *
 * Everything now is based on TMGMTPoetryTranslatorUIController,
 * Later this should extend TMGMTDefaultTranslatorUIController and
 * TMGMTPoetryTranslatorUIController should be deprecated.
 */
class TmgmtDgtConnectorTranslatorUIController extends TMGMTPoetryTranslatorUIController {

}
