<?php
/**
 * @file
 * Drupal needs this blank file.
 */
 
/**
* CKEditor plugins hook
*/
function text_collapse_ckeditor_plugin() {
  return array(
      'collapse' => array(
          'name' => 'collapse',
          'desc' => 'Collapse - ' . t('Inserts [collapsed][/collapsed] tags'),
          'path' => drupal_get_path('module', 'text_collapse') . '/plugins/collapse/',
          'buttons' => array
          (
              'collapse' => array('label' => 'Insert collapsible block', 'icon' => 'button.png' ),
          )
      )
  );
}

/**
* WYSYWIG plugins hook
*/
function text_collapse_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor': {
      return array(
        'collapse' => array(
          'name' => 'collapse',
          'desc' => 'Collapse - ' . t('Inserts [collapsed][/collapsed] tags'),
          'path' => drupal_get_path('module', 'text_collapse') . '/plugins/collapse/',
          'internal' => FALSE,
          'load' => TRUE,
          'buttons' => array
          (
              'collapse' => t('Insert collapsible block'),
          )
        )
      );
      break;
    }
  }
}