<?php

/**
 * @file
 * Manage language switcher at site level.
 */

/**
 * Implements hook_block_info().
 */
function language_selector_site_block_info() {
  $block = array();
  $block['language_selector_site'] = array(
    'info' => t('Language selector (Site)'),
  );
  return $block;
}

/**
 * Implements hook_block_view().
 */
function language_selector_site_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'language_selector_site':
      $block['content'] = language_selector_site_block_content();
      break;
  }

  return $block;
}

/**
 * Manage content of the block.
 */
function language_selector_site_block_content() {
  global $language;

  $block = array(
    'code' => array(
      '#type' => 'markup',
      '#markup' => $language->language,
    ),
    'label' => array(
      '#type' => 'markup',
      '#markup' => $language->native,
    ),
  );

  return $block;
}

/**
 * Implements hook_preprocess_block().
 *
 * Default implementation of language selector.
 */
function language_selector_site_preprocess_block(&$variables) {
  if (isset($variables['block']->bid) && $variables['block']->bid === 'language_selector_site-language_selector_site') {

    // Initialize variables.
    $code = '<span class="language-selector-site__code">' . $variables['elements']['code']['#markup'] . '</span>';
    $label = '<span class="language-selector-site__label">' . $variables['elements']['label']['#markup'] . '</span>';
    $options = array(
      'html' => TRUE,
      'attributes' => array(
        'class' => array('language-selector-site__link'),
      ),
      'query' => array(drupal_get_destination()),
    );

    // Add class to block.
    $variables['classes_array'][] = 'language-selector-site';

    // Add content to block.
    $variables['content'] = l($code . ' ' . $label, 'splash', $options);
  }
}
