<?php

/**
 * @file
 * Code for the Events feature.
 */

include_once 'events_og.features.inc';
include_once 'events_og.views_alter.inc';

/**
 * Implements hook_menu().
 */
function events_og_menu() {
  $items = array();

  $items['community/%group_name/calendar'] = array(
    'title' => 'Events',
    'page callback' => 'views_page',
    'page arguments' => array('calendar', 'month', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}
