<?php
/**
 * @file
 * Code for the Multisite Maps feature.
 */

include_once 'multisite_maps.features.inc';


/**
 * Implements hook_requirements().
 */
function multisite_maps_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    // FusionMaps SWF files
    $swf = glob(multisite_maps_get_library_path() . 'FusionMaps XT/Maps/*.swf');
    if (!empty($swf)) {
      $requirements['multisite_maps']['severity'] = REQUIREMENT_OK;
      $requirements['multisite_maps']['value'] = t('FusionMaps SWF files found.');
    }
    else {
      $requirements['multisite_maps']['severity'] = REQUIREMENT_ERROR;
      $requirements['multisite_maps']['value'] = t('FusionMaps SWF files not found.');
      $requirements['multisite_maps']['description'] = t('Please download these files from <a href="@url">http://www.fusioncharts.com</a> and copy them into the FusionMaps library directory as per instructions in the readme.txt file.', array('@url' => 'http://www.fusioncharts.com'));
    }
    $requirements['multisite_maps']['title'] = t('FusionMaps');
  }
  return $requirements;
}


/**
 * Implements hook_theme().
 */
function multisite_maps_theme($existing, $type, $theme, $path) {
  return array(
    'multisite_map' => array(
      'variables' => array('info' => '', 'jsid' => NULL),
    ),
  );
}


/**
 * Map rendering function
 *
 * @param array $info an array containing the map data
 * @param string $jsid Name to be used for the id attribute in the DOM (used for javascript manipulation) optional
 * @return string the HTML to render the map
 */
function theme_multisite_map($variables) {
  $info = $variables['info'];
  $jsid = $variables['jsid'];
  static $map_id; //incremental ID of each map (static in case there is more then one map on a page)
  if (!isset($map_id)) {
    $map_id = 1;
  }
  if (!isset($jsid)) {
    $jsid = 'Map_' . $map_id++;
  }

  $path = 'http://www.cc.cec/fpfis/fusionmaps/';//'http://ec.europa.eu/wel/maps/fusion_maps/'; //multisite_maps_get_library_path() . 'FusionMaps XT/';
  $maps_path = $path . 'Maps/';

  include_once(multisite_maps_get_library_path() . 'Code/PHP/Includes/FusionMaps.php');
  //check that the fusionmaps package was installed
  if (!function_exists('renderChart')) {
    return t('Please install the Fusion Maps package from InfoSoft as per instructions in the readme.');
  }

  drupal_add_js($path . '/JSClass/FusionMaps.js');//$maps_path . 'FusionCharts.js');

  // Get the path of drupal instance
  $path_drupal = base_path();
  $swf_file = /*$path_drupal .*/ $maps_path . $info['type'] . '.swf';

  // I remove white spaces between xml tags and line breaks from the variable.
  $xml_data_source = escape($info['xml']);
  $xml_data_source = str_replace('\r\n', ' ', $xml_data_source);

  return renderChart($swf_file, '', $xml_data_source, $jsid, $info['width'], $info['height'], 0, 0, 0);
}

// replace any non-ascii character with its hex code.
function escape($value) {
    $search = array("\\", "\x00", "\n", "\r", "'", '"', "\x1a");
    $replace = array("\\\\", "\\0", "\\n", "\\r", "'", '\"', "\\Z");

    return str_replace($search, $replace, $value);
}

/**
 * Get the maps library path
 *
 * @return string
 */
function multisite_maps_get_library_path() {
  global $conf;
  $path = 'sites/all/libraries/FusionMaps XT/';
  $lpath = libraries_get_path('FusionMaps XT/');
  if (isset($conf['fusion_maps_path'])) {
    $path = $conf['fusion_maps_path'];
  }
  elseif ($lpath) {
    $path = $lpath . '/';
  }
  return $path;
}

/**
 * Implements hook_node_view().
 */
function multisite_maps_node_view($node, $view_mode, $langcode) {
  if ('map'==$node->type) {
    switch ($view_mode) {
      case 'full':
      case 'teaser':
        $map_type_items = field_get_items('node', $node, 'field_map_type');
        $map_width_items = field_get_items('node', $node, 'field_map_width');
        $map_height_items = field_get_items('node', $node, 'field_map_height');
        $map_data_items = field_get_items('node', $node, 'field_map_xml_data_source');

        $info = array();
        $info['type'] = $map_type_items[0]['value'];
        if ('full'==$view_mode) {
          $info['width'] = $map_width_items[0]['value'];
          $info['height'] = $map_height_items[0]['value'];
        }
        else {
          $info['width'] = 400;
          $info['height'] = 300;
        }

        $info['xml'] = $map_data_items[0]['xml'];

        $map_out = theme('multisite_map', array('info' => $info));
        $node->content['map_area']['#markup'] = $map_out;
        $node->content['map_area']['#weight'] = 30;
        break;
    }
  }
  // If a map is rendered with field collection
  if (isset($node->content['field_embedded_maps'][0]['entity']['field_collection_item'])) {
    $fci =& $node->content['field_embedded_maps'][0]['entity']['field_collection_item'];
    $keys = array_keys($fci);
    $key = $keys[0];

    if (isset($fci[$key]['#entity']->field_maps_regions[LANGUAGE_NONE])) {
      $fci_ke =& $fci[$key]['#entity'];
      // I get the item 'field_maps_category' from the current node. I receive an array of the item found.
      $item_category = $fci_ke->field_maps_category[LANGUAGE_NONE];
      // I access to the '#markup' position of the returned array to get the value of the item.
      $category = $item_category[0]['value'];

      // I get the item 'field_maps_map' from the current node. I receive an array of the item found.
      $item_map = $fci_ke->field_maps_map[LANGUAGE_NONE];
      // I access to the '#markup' position of the returned array to get the value of the item.
      $map = $item_map[0]['value'];

      // I get the item 'field_maps_regions' from the current node. I receive an array of the item found.
      $item_regions = $fci_ke->field_maps_regions[LANGUAGE_NONE];

      // I get the item 'field_maps_settings' from the current node. I receive an array of the item found.
      $item_settings = $fci_ke->field_maps_settings[LANGUAGE_NONE];
      // I access to the '#markup' position of the returned array to get the value of the item.
      $settings_labels = $item_settings[0]['value'];

      if ($settings_labels == TRUE) {
        $settings_labels = 1;
      }
      else $settings_labels = 0;

      if ($item_regions) {
        // Create the xml data of the FusionMap object with all the selected regions
        $xml_data = '<map animation="0" showBevel="0" showCanvasBorder="0" showShadow="1" fillColor="CAD3DB" borderColor="FFFFFF" useHoverColor="0" hoverColor="E6EAEE" showLabels="' . $settings_labels . '" includeNameInLabels="' . $settings_labels . '"><data>';
        for ($i=0; $i<sizeof($item_regions); $i++) {
          $xml_data .= '<entity id="' . $item_regions[$i]['value'] . '" color="FF0033" />';
        }
        $xml_data .= '</data></map>';

        $info = array();
        $info['type'] = $map;
        $info['width'] = 400;
        $info['height'] = 400;
        $info['xml'] = $xml_data;
        $jsid = 'myMapId';
        $map_out = theme('multisite_map', array('info' => $info, 'jsid' => $jsid));
        $node->content['field_map_container'][0]['#markup'] = '<div id="mapContainer" align="center">' . $map_out . '</div>';
        $node->content['field_map_container']['#weight'] = $node->content['body']['#weight']+1;
        _multisite_maps_load_css();
      }
    }
  }
}

/**
 * Implements hook_node_validate().
 */
function multisite_maps_node_validate($node, $form, &$form_state) {
  $map_type_items = field_get_items('node', $node, 'field_map_type');
  $info['type'] = $map_type_items[0]['value'];
  // The value of the categories of maps are numbers. They aren't valid options.
  if (is_numeric($info['type']) == TRUE) {
      form_set_error('Error', t('Map type is not a valid option. Please, select a valid map type.'));
  }
}


/**
 * Helper to load CSS file
 */
function _multisite_maps_load_css() {
  $pathModule = drupal_get_path('module', 'multisite_maps');
  drupal_add_css($pathModule . '/css/multisite_maps.css');
}

/**
 * Helper to load JS files
 */
function _multisite_maps_load_js() {
  $pathModule = drupal_get_path('module', 'multisite_maps');
  $library_path = libraries_get_path('FusionCharts');
  drupal_add_js( array( 'multisite_maps' => array( 'base_path' => base_path(), 'library_path' => $library_path )), 'setting' );
  drupal_add_js($library_path . '/FusionMaps XT/Maps/FusionMaps.js');
  drupal_add_js($library_path . '/FusionMaps XT/Maps/FusionCharts.js');
  drupal_add_js($pathModule . '/scripts/multisite_maps.js');
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function multisite_maps_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['field_embedded_maps'][LANGUAGE_NONE][0])) {

    _multisite_maps_load_css();
    _multisite_maps_load_js();

    $fem =& $form['field_embedded_maps'][LANGUAGE_NONE][0];
    if (isset($fem['field_maps_category']) && (isset($fem['field_maps_map']) && (isset($fem['field_maps_regions'])))) {
      if (isset($fem['field_maps_category'][LANGUAGE_NONE]['#default_value'][0])) {
        $id_maps_category = $fem['field_maps_category'][LANGUAGE_NONE]['#default_value'][0];
      }
      else {
        $id_maps_category = 0;
      }

      if (arg(2) == 'edit') {
        $fs_fem_e =& $form_state['field']['field_embedded_maps'][LANGUAGE_NONE]['entity'][0];
        if (($fs_fem_e->field_maps_regions) && ($fs_fem_e->field_maps_regions[LANGUAGE_NONE][0] != '_none')) {
          if (isset( $fs_fem_e->field_maps_map[LANGUAGE_NONE][0]['value'])) {
            drupal_add_js(array('select_maps_map' => _multisite_maps_get_maps($fs_fem_e->field_maps_category[LANGUAGE_NONE][0]['value'])), 'setting');
            drupal_add_js(array('field_maps_map' => $fs_fem_e->field_maps_map[LANGUAGE_NONE][0]['value']), 'setting');
          }
          if (isset($fs_fem_e->field_maps_regions[LANGUAGE_NONE])) {
            drupal_add_js(array('field_maps_regions' => $fs_fem_e->field_maps_regions[LANGUAGE_NONE]), 'setting');
          }
          drupal_add_js('jQuery(document).ready(function () { jQuery.testing(); });',  array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
        }
      }

      $form['field_embedded_maps'][LANGUAGE_NONE][0]['field_maps_category'][LANGUAGE_NONE]['#ajax'] = array(
            'event' => 'change',
            'wrapper' => 'maps_map_wrapper',
            'callback' => '_multisite_maps_load_map_select_list',
            'method' => 'replace',
            'progress' => array('type' => 'throbber', 'message' => t('Loading maps...')),
          );

      // Add wrapper and initialize 'Maps' select list
      $options_maps_category = _multisite_maps_get_maps($id_maps_category);
      $fmm =& $fem['field_maps_map'][LANGUAGE_NONE];
      $fmm['#options'] = NULL;
      $fmm['#properties']['empty_option'] = array('' => '- None -');
      $fmm['#prefix'] = '<div id="maps_map_wrapper">';
      $fmm['#suffix'] = '</div>';

      // Add wrapper and initialize 'Regions' select list
      $fmr =& $fem['field_maps_regions'][LANGUAGE_NONE];
      $fmr['#prefix'] = '<div id="maps_regions_wrapper">';
      $fmr['#suffix'] = '</div>';
      $fmr['#multiple'] = TRUE;
      $fmr['#options'] = NULL;

    }

  }
}


/**
 * Function invoked by 'field_maps_category'. It returns the selec list 'field_maps_map'
 */
function _multisite_maps_load_map_select_list($form, $form_state) {
  $fem =& $form['field_embedded_maps'][LANGUAGE_NONE][0];
  $id_maps_category = $fem['field_maps_category'][LANGUAGE_NONE]['#value'];
  $fem['field_maps_map'][LANGUAGE_NONE]['#options'] = _multisite_maps_get_maps($id_maps_category);

  return $fem['field_maps_map'];
}

/**
 * Function that returns the list of maps of each own category.
 */
function _multisite_maps_get_maps($id_cat) {
  $empty_value[''] = '- ' . t('Select a map') . ' -';
  switch ($id_cat) {
    case 1: return $empty_value+_multisite_maps_get_World_and_Continents();
    case 2: return $empty_value+_multisite_maps_get_US_and_Counties();
    case 3: return $empty_value+_multisite_maps_get_US_Regions();
    case 4: return $empty_value+_multisite_maps_get_Europe_and_Countries();
    case 5: return $empty_value+_multisite_maps_get_Europe_by_Regions();
    case 6: return $empty_value+_multisite_maps_get_UK();
    case 7: return $empty_value+_multisite_maps_get_North_America();
    case 8: return $empty_value+_multisite_maps_get_South_America();
    case 9: return $empty_value+_multisite_maps_get_Central_America();
    case 10: return $empty_value+_multisite_maps_get_Canada_Provinces_and_Territories();
    case 11: return $empty_value+_multisite_maps_get_Asia();
    case 12: return $empty_value+_multisite_maps_get_Middle_East();
    case 13: return $empty_value+_multisite_maps_get_Oceania();
    case 14: return $empty_value+_multisite_maps_get_Africa_and_Countries();
    case 15: return $empty_value+_multisite_maps_get_Africa_Regions();
    case 16: return $empty_value+_multisite_maps_get_Egypt();
    case 17: return $empty_value+_multisite_maps_get_Brazil_States();
    case 18: return $empty_value+_multisite_maps_get_Caribbeans_Islands();
    case 19: return $empty_value+_multisite_maps_get_Mexico();
    case 20: return $empty_value+_multisite_maps_get_Bulgaria_Provinces();
    case 21: return $empty_value+_multisite_maps_get_Denmark_Regions();
    case 22: return $empty_value+_multisite_maps_get_Hungary_Regions();
    case 23: return $empty_value+_multisite_maps_get_Czech_Republic_District();
    case 24: return $empty_value+_multisite_maps_get_Albania_Counties();
    case 25: return $empty_value+_multisite_maps_get_Estonia_Counties();
    case 26: return $empty_value+_multisite_maps_get_Romania_Regions();
    case 27: return $empty_value+_multisite_maps_get_Poland_Voivodeships();
    case 28: return $empty_value+_multisite_maps_get_Norway_Regions();
    case 29: return $empty_value+_multisite_maps_get_Norway_Counties();
    case 30: return $empty_value+_multisite_maps_get_Slovakia_Regions();
    case 31: return $empty_value+_multisite_maps_get_Belgium_Regions();
    case 32: return $empty_value+_multisite_maps_get_Czech_Republic_Regions();
    case 33: return $empty_value+_multisite_maps_get_France_Arrondisemants();
    case 34: return $empty_value+_multisite_maps_get_Germany_States();
    case 35: return $empty_value+_multisite_maps_get_Italy_Regions();
    case 36: return $empty_value+_multisite_maps_get_Sweden_Counties();
    case 37: return $empty_value+_multisite_maps_get_Switzerland_Cantons();
    case 38: return $empty_value+_multisite_maps_get_Austria_States();
    case 39: return $empty_value+_multisite_maps_get_Portugal_Districts();
    case 40: return $empty_value+_multisite_maps_get_Austria_States();
    case 41: return $empty_value+_multisite_maps_get_New_Zealand_Provinces();
    case 42: return $empty_value+_multisite_maps_get_USA_States_Area_Code();
    case 43: return $empty_value+_multisite_maps_get_USA_Congressional();
    case 44: return $empty_value+_multisite_maps_get_USA_DMA();
    case 45: return $empty_value+_multisite_maps_get_TimeZone();
    default: return NULL;
  }
}

function _multisite_maps_get_World_and_Continents() {
  return array(
        'FCMap_World' => 'World',
        'FCMap_WorldWithAntarctica' => 'World with Antarctica',
        'FCMap_WorldwithCountries' => 'World with countries',
        'FCMap_World8' => 'World 8 Regions',
        'FCMap_World8WithAntarctica' => 'World 8 Regions with Antarctica Map',
        'FCMap_Europe' => 'Europe',
        'FCMap_NorthAmerica' => 'North America',
        'FCMap_CentralAmerica' => 'Central America',
        'FCMap_SouthAMerica' => 'South America',
        'FCMap_Asia' => 'Asia',
        'FCMap_Africa' => 'Africa',
        'FCMap_MiddleEast' => 'Middle East',
        'FCMap_Oceania' => 'Oceania',
        'FCMap_Asia3' => 'Asia (No Mid-east)',
        'FCMap_NorthAmerica_WOCentral' => 'North America (no Central)',
  );
}

function _multisite_maps_get_US_and_Counties() {
  return array(
        'FCMap_USA' => 'USA (States)',
        'FCMap_ALaska' => 'Alaska',
        'FCMap_Alabama' => 'Alabama',
        'FCMap_Arizona' => 'Arizona',
        'FCMap_Arkansas' => 'Arkansas',
        'FCMap_California' => 'California',
        'FCMap_Colorado' => 'Colorado',
        'FCMap_Connecticut' => 'Connecticut',
        'FCMap_Delaware' => 'Delaware',
        'FCMap_DistrictofColumbia' => 'District of Columbia',
        'FCMap_Florida' => 'Florida',
        'FCMap_Georgia' => 'Georgia',
        'FCMap_Hawaii' => 'Hawaii',
        'FCMap_Idaho' => 'Idaho',
        'FCMap_Illinois' => 'Illinois',
        'FCMap_Indiana' => 'Indiana',
        'FCMap_Iowa' => 'Iowa',
        'FCMap_Kentucky' => 'Kentucky',
        'FCMap_Kansas' => 'Kansas',
        'FCMap_Louisiana' => 'Louisiana',
        'FCMap_Maine' => 'Maine',
        'FCMap_Maryland' => 'Maryland',
        'FCMap_Massachusetts' => 'Massachusetts',
        'FCMap_Michigan' => 'Michigan',
        'FCMap_Minnesota' => 'Minnesota',
        'FCMap_Mississippi' => 'Mississippi',
        'FCMap_Missouri' => 'Missouri',
        'FCMap_Montana' => 'Montana',
        'FCMap_Nebraska' => 'Nebraska',
        'FCMap_Nevada' => 'Nevada',
        'FCMap_NewHampshire' => 'New Hampshire',
        'FCMap_NewJersey' => 'New Jersey',
        'FCMap_NewMexico' => 'New Mexico',
        'FCMap_NewYork' => 'New York',
        'FCMap_NorthCarolina' => 'North Carolina',
        'FCMap_NorthDakota' => 'North Dakota',
        'FCMap_Ohio' => 'Ohio',
        'FCMap_Oklahoma' => 'Oklahoma',
        'FCMap_Oregon' => 'Oregon',
        'FCMap_Pennsylvania' => 'Pennsylvania',
        'FCMap_RhodeIsland' => 'Rhode Island',
        'FCMap_SouthCarolina' => 'South Carolina',
        'FCMap_SouthDakota' => 'South Dakota',
        'FCMap_Tennessee' => 'Tennessee',
        'FCMap_Texas' => 'Texas',
        'FCMap_Utah' => 'Utah',
        'FCMap_Washington' => 'Washington',
        'FCMap_Vermont' => 'Vermont',
        'FCMap_Virginia' => 'Virginia',
        'FCMap_WestVirginia' => 'West Virginia',
        'FCMap_Wisconsin' => 'Wisconsin',
        'FCMap_Wyoming' => 'Wyoming',
  );
}

function _multisite_maps_get_US_Regions() {
  return array(
        'FCMap_USARegion' => 'USA (All Regions)',
        'FCMap_USACentralRegion' => 'USA Central Region',
        'FCMap_USANorthEastRegion' => 'USA North East Region',
        'FCMap_USANorthWestRegion' => 'USA North West Region',
        'FCMap_USASouthEastRegion' => 'USA South East Region',
        'FCMap_USASouthWestRegion' => 'USA South West Region',
  );
}

function _multisite_maps_get_Europe_and_Countries() {
  return array(
        'FCMap_Europewithcountries' => 'Europe (All Countries)',
        'FCMap_Europe2' => 'Europe (With all islands)',
        'FCMap_Albania' => 'Albania',
        'FCMap_Andorra' => 'Andorra',
        'FCMap_Austria' => 'Austria',
        'FCMap_Belarus' => 'Belarus',
        'FCMap_Belgium' => 'Belgium',
        'FCMap_BosniaHerzegovina' => 'Bosnia-Herzegovina',
        'FCMap_Bulgaria' => 'Bulgaria',
        'FCMap_Croatia' => 'Croatia',
        'FCMap_Cyprus' => 'Cyprus',
        'FCMap_Cyprus2' => 'Cyprus (Regions)',
        'FCMap_CzechRepublic' => 'Czech Republic',
        'FCMap_Denmark' => 'Denmark',
        'FCMap_DenmarkRegion' => 'Denmark (Regions)',
        'FCMap_England' => 'England',
        'FCMap_Estonia' => 'Estonia',
        'FCMap_Finland' => 'Finland',
        'FCMap_France' => 'France',
        'FCMap_FranceDepartment' => 'France (Departments)',
        'FCMap_Germany' => 'Germany',
        'FCMap_Greece' => 'Greece',
        'FCMap_Hungary' => 'Hungary',
        'FCMap_HungaryRegions' => 'Hungary (Regions)',
        'FCMap_Iceland' => 'Iceland',
        'FCMap_Ireland' => 'Ireland',
        'FCMap_Italy' => 'Italy',
        'FCMap_KosovoDistricts' => 'Kosovo Districts',
        'FCMap_Latvia' => 'Latvia',
        'FCMap_Liechtenstein' => 'Liechtenstein',
        'FCMap_Lithuania' => 'Lithuania',
        'FCMap_Luxembourg' => 'Luxembourg',
        'FCMap_Macedonia' => 'Macedonia',
        'FCMap_Malta' => 'Malta',
        'FCMap_Moldova' => 'Moldova',
        'FCMap_Monaco' => 'Monaco',
        'FCMap_Montenegro' => 'Montenegro',
        'FCMap_Netherlands' => 'Netherlands',
        'FCMap_Norway' => 'Norway',
        'FCMap_NorwayRegion' => 'Norway (Regions)',
        'FCMap_PolandCounties' => 'Poland (Counties)',
        'FCMap_Poland' => 'Poland',
        'FCMap_Portugal' => 'Portugal',
        'FCMap_Romania' => 'Romania',
        'FCMap_SanMarino' => 'San Marino',
        'FCMap_Scotland' => 'Scotland',
        'FCMap_Serbia' => 'Serbia',
        'FCMap_SerbiaWokosovo' => 'Serbia(W/o Kosovo)',
        'FCMap_Slovakia' => 'Slovakia',
        'FCMap_Slovenia' => 'Slovenia',
        'FCMap_Spain' => 'Spain (Autonomous)',
        'FCMap_SpainProvinces' => 'Spain (Provinces)',
        'FCMap_Sweden' => 'Sweden',
        'FCMap_Switzerland' => 'Switzerland',
        'FCMap_Turkey' => 'Turkey',
        'FCMap_UK' => 'UK',
        'FCMap_Ukraine' => 'Ukraine',
        'FCMap_VaticanCity' => 'Vatican City',
  );
}

function _multisite_maps_get_Europe_by_Regions() {
  return array(
        'FCMap_EuropeRegion' => 'Europe (All Regions)',
        'FCMap_CentralEuropeanRegion' => 'Central European Region',
        'FCMap_EastEuropeanRegion' => 'East European Region',
        'FCMap_WestEuropeanRegion' => 'West European Region',
        'FCMap_NorthEuropeanRegion' => 'North European Region',
        'FCMap_SouthEuropeanRegion' => 'South European Region',
  );
}

function _multisite_maps_get_UK() {
  return array(
        'FCMap_UK' => 'UK',
        'FCMap_UK7' => 'UK (With Islands)',
        'FCMap_EnglandRegion' => 'England (Region)',
        'FCMap_ScotlandRegion' => 'Scotland (Region)',
        'FCMap_Wales' => 'Wales',
        'FCMap_NorthernIreland' => 'Northern Ireland',
  );
}

function _multisite_maps_get_North_America() {
  return array(
        'FCMap_Antigua' => 'Antigua',
        'FCMap_Bahamas' => 'Bahamas',
        'FCMap_Barbados' => 'Barbados',
        'FCMap_Canada' => 'Canada',
        'FCMap_CaymanIslands' => 'CaymanIsland',
        'FCMap_Cuba' => 'Cuba',
        'FCMap_Dominica' => 'Dominica',
        'FCMap_DominicanRepublic' => 'Dominican Republic',
        'FCMap_Greenland' => 'Greenland',
        'FCMap_Grenada' => 'Grenada',
        'FCMap_Haiti' => 'Haiti',
        'FCMap_Jamaica' => 'Jamaica',
        'FCMap_Mexico' => 'Mexico',
        'FCMap_PuertoRico' => 'Puerto Rico',
        'FCMap_SaintKittsandNevis' => 'Saint Kitts & Nevis',
        'FCMap_SaintLucia' => 'Saint Lucia',
        'FCMap_SaintVincentandtheGrenadines' => 'Saint Vincent & The Grenadines',
        'FCMap_TrinidadandTobago' => 'Trinidad & Tabogo',
  );
}

function _multisite_maps_get_South_America() {
  return array(
        'FCMap_Antigua' => 'Antigua',
        'FCMap_Bahamas' => 'Bahamas',
        'FCMap_Barbados' => 'Barbados',
        'FCMap_Canada' => 'Canada',
        'FCMap_CaymanIslands' => 'CaymanIsland',
        'FCMap_Cuba' => 'Cuba',
        'FCMap_Dominica' => 'Dominica',
        'FCMap_DominicanRepublic' => 'Dominican Republic',
        'FCMap_Greenland' => 'Greenland',
        'FCMap_Grenada' => 'Grenada',
        'FCMap_Haiti' => 'Haiti',
        'FCMap_Jamaica' => 'Jamaica',
        'FCMap_Mexico' => 'Mexico',
        'FCMap_PuertoRico' => 'Puerto Rico',
        'FCMap_SaintKittsandNevis' => 'Saint Kitts & Nevis',
        'FCMap_SaintLucia' => 'Saint Lucia',
        'FCMap_SaintVincentandtheGrenadines' => 'Saint Vincent & The Grenadines',
        'FCMap_TrinidadandTobago' => 'Trinidad & Tabogo',
  );
}

function _multisite_maps_get_Central_America() {
  return array(
        'FCMap_CentralAmericawithCaribbean' => 'Central America (with Caribbean)',
        'FCMap_CentralAmerica2' => 'Central America (with Virgin Islands)',
        'FCMap_Belize' => 'Belize',
        'FCMap_CostaRica' => 'Costa Rica',
        'FCMap_ElSalvador' => 'El Salvador',
        'FCMap_Guatemala' => 'Guatemala',
        'FCMap_Honduras' => 'Honduras',
        'FCMap_Nicaragua' => 'Nicaragua',
        'FCMap_Panama' => 'Panama',
  );
}

function _multisite_maps_get_Canada_Provinces_and_Territories() {
  return array(
        'FCMap_Alberta' => 'Alberta',
        'FCMap_BritishColumbia' => 'British Columbia',
        'FCMap_Manitoba' => 'Manitoba',
        'FCMap_NewBrunswick' => 'New Brunswick',
        'FCMap_NewfoundlandandLabrador' => 'Newfoundland & Labrador',
        'FCMap_NorthWestTerritories' => 'Northwest Territories',
        'FCMap_NovaScotia' => 'Nova Scotia',
        'FCMap_Nunavut' => 'Nunavut',
        'FCMap_Ontario' => 'Ontario',
        'FCMap_PrinceEdwardIsland' => 'Prince Edward Island',
        'FCMap_Quebec' => 'Quebec',
        'FCMap_Saskatchewan' => 'Saskatchewan',
        'FCMap_YukonTerritory' => 'Yukon Territory',
  );
}

function _multisite_maps_get_Asia() {
  return array(
        'FCMap_Armenia' => 'Armenia',
        'FCMap_Azerbaijan' => 'Azerbaijan',
        'FCMap_Bangladesh' => 'Bangladesh',
        'FCMap_Bhutan' => 'Bhutan',
        'FCMap_Brunei' => 'Brunei',
        'FCMap_Burma' => 'Burma',
        'FCMap_Cambodia' => 'Cambodia',
        'FCMap_China' => 'China',
        'FCMap_China2' => 'China (With Direct-controlled municipalities and Special administrative regions)',
        'FCMap_AsiaGeorgia' => 'Asia Georgia',
        'FCMap_EastTimor' => 'East Timor',
        'FCMap_HongKong' => 'Hong Kong',
        'FCMap_India' => 'India',
        'FCMap_Indonesia' => 'Indonesia',
        'FCMap_Japan' => 'Japan',
        'FCMap_KAzakhstan' => 'Kazakhstan',
        'FCMap_Laos' => 'Laos',
        'FCMap_Macau' => 'Macau',
        'FCMap_Malaysia' => 'Malaysia',
        'FCMap_Mongolia' => 'Mongolia',
        'FCMap_Nepal' => 'Nepal',
        'FCMap_NorthKorea' => 'North Korea',
        'FCMap_Philippines' => 'Philippines',
        'FCMap_Russia' => 'Russia',
        'FCMap_Singapore' => 'Singapore',
        'FCMap_SouthKorea' => 'South Korea',
        'FCMap_SriLanka' => 'SriLanka',
        'FCMap_Taiwan' => 'Taiwan',
        'FCMap_Thailand' => 'Thailand',
        'FCMap_Tibet' => 'Tibet',
        'FCMap_Vietnam' => 'Vietnam',
  );
}

function _multisite_maps_get_Middle_East() {
  return array(
        'FCMap_Afghanistan' => 'Afghanistan',
        'FCMap_Bahrain' => 'Bahrain',
        'FCMap_Iran' => 'Iran',
        'FCMap_Iraq' => 'Iraq',
        'FCMap_Israel' => 'Israel',
        'FCMap_Jordan' => 'Jordan',
        'FCMap_Kuwait' => 'Kuwait',
        'FCMap_Kyrgyzstan' => 'Kyrgyzstan',
        'FCMap_Lebanon' => 'Lebanon',
        'FCMap_Oman' => 'Oman',
        'FCMap_Pakistan' => 'Pakistan',
        'FCMap_Qatar' => 'Qatar',
        'FCMap_SaudiArabia' => 'Saudi Arabia',
        'FCMap_Syria' => 'Syria',
        'FCMap_Tajikistan' => 'Tajikistan',
        'FCMap_Turkmenistan' => 'Turkmenistan',
        'FCMap_UAE' => 'United Arab Emirates',
        'FCMap_Uzbekistan' => 'Uzbekistan',
        'FCMap_Yemen' => 'Yemen',
  );
}

function _multisite_maps_get_Oceania() {
  return array(
        'FCMap_Oceania' => 'Oceania',
        'FCMap_Australia' => 'Australia',
        'FCMap_Australia2' => 'Australia (W/Capital)',
        'FCMap_Fiji' => 'Fiji',
        'FCMap_Kiribati' => 'Kiribati',
        'FCMap_MarshallIsland' => 'Marshall Islands',
        'FCMap_Micronesia' => 'Micronesia',
        'FCMap_Nauru' => 'Nauru',
        'FCMap_NewCaledonia' => 'New Caledonia',
        'FCMap_NewZealand' => 'New Zealand',
        'FCMap_Palau' => 'Palau',
        'FCMap_PapuaNewGuinea' => 'Papua New Guinea',
        'FCMap_Samoa' => 'Samoa',
        'FCMap_SolomonIsland' => 'Solomon Islands',
        'FCMap_Tonga' => 'Tonga',
        'FCMap_Tuvalu' => 'Tuvalu',
        'FCMap_Vanuatu' => 'Vanuatu',
  );
}

function _multisite_maps_get_Africa_and_Countries() {
  return array(
        'FCMap_Algeria' => 'Algeria',
        'FCMap_Angola' => 'Angola',
        'FCMap_Benin' => 'Benin',
        'FCMap_Botswana' => 'Botswana',
        'FCMap_BurkinaFaso' => 'Burkina Faso',
        'FCMap_Burundi' => 'Burundi',
        'FCMap_Cameroon' => 'Cameroon',
        'FCMap_CapeVerde' => 'Cape Verde',
        'FCMap_CentralAfricanRepublic' => 'Central African Republic',
        'FCMap_Chad' => 'Chad',
        'FCMap_Comoros' => 'Comoros',
        'FCMap_Congo' => 'Congo',
        'FCMap_CoteDivoire' => 'Cote Divoire',
        'FCMap_DemocraticRepublicofCongo' => 'Democratic Republic of the Congo',
        'FCMap_Djibouti' => 'Djibouti',
        'FCMap_Egypt' => 'Egypt',
        'FCMap_EquatorialGuinea' => 'Equatorial Guinea',
        'FCMap_Eritrea' => 'Eritrea',
        'FCMap_Ethiopia' => 'Ethiopia',
        'FCMap_Gabon' => 'Gabon',
        'FCMap_Gambia' => 'Gambia',
        'FCMap_Ghana' => 'Ghana',
        'FCMap_Guinea' => 'Guinea',
        'FCMap_GuineaBissau' => 'Guinea-Bissau',
        'FCMap_Kenya' => 'Kenya',
        'FCMap_Lesotho' => 'Lesotho',
        'FCMap_Liberia' => 'Liberia',
        'FCMap_Libya' => 'Libya',
        'FCMap_Madagascar' => 'Madagascar',
        'FCMap_MadagascarRegions' => 'Madagascar (Regions)',
        'FCMap_Malawi' => 'Malawi',
        'FCMap_Mali' => 'Mali',
        'FCMap_Mauritania' => 'Mauritania',
        'FCMap_Mauritius' => 'Mauritius',
        'FCMap_Morocco' => 'Morocco',
        'FCMap_Mozambique' => 'Mozambique',
        'FCMap_Namibia' => 'Namibia',
        'FCMap_Niger' => 'Niger',
        'FCMap_Nigeria' => 'Nigeria',
        'FCMap_Rwanda' => 'Rwanda',
        'FCMap_SaoTomeandPrincipe' => 'Sao Tome and Principe',
        'FCMap_Senegal' => 'Senegal',
        'FCMap_Seychelles' => 'Seychelles',
        'FCMap_SierraLeone' => 'Sierra Leone',
        'FCMap_Somalia' => 'Somalia',
        'FCMap_SouthAfrica' => 'South Africa',
        'FCMap_Sudan' => 'Sudan',
        'FCMap_SudanWoSouthSudan' => 'Sudan(W/o South Sudan)',
        'FCMap_SouthSudan' => 'South Sudan',
        'FCMap_Swaziland' => 'Swaziland',
        'FCMap_Tanzania' => 'Tanzania',
        'FCMap_Togo' => 'Togo',
        'FCMap_Tunisia' => 'Tunisia',
        'FCMap_Uganda' => 'Uganda',
        'FCMap_WesternSahara' => 'Western Sahara',
        'FCMap_Zambia' => 'Zambia',
        'FCMap_Zimbabwe' => 'Zimbabwe',
  );
}

function _multisite_maps_get_Africa_Regions() {
  return array(
        'FCMap_AfricaRegion' => 'Africa (All Regions)',
        'FCMap_EasternAfrica' => 'Eastern Africa',
        'FCMap_CentralAfrica' => 'Central Africa',
        'FCMap_NorthernAfrica' => 'Northern Africa',
        'FCMap_SouthernAfrica' => 'Southern Africa',
        'FCMap_WesternAfrica' => 'Western Africa',
  );
}

function _multisite_maps_get_Egypt() {
  return array(
        'FCMap_Alexandria' => 'Alexandria',
        'FCMap_Alminya' => 'Alminya',
        'FCMap_Alsharqeyah' => 'Alsharqeyah',
        'FCMap_Aswan' => 'Aswan',
        'FCMap_Asyut' => 'Asyut',
        'FCMap_Bahera' => 'Bahera',
        'FCMap_Baniswaif' => 'Baniswaif',
        'FCMap_Cairo' => 'Cairo',
        'FCMap_Daqahliya' => 'Daqahliya',
        'FCMap_Domyat' => 'Domyat',
        'FCMap_Fayoum' => 'Fayoum',
        'FCMap_Gharbiya' => 'Gharbiya',
        'FCMap_Giza' => 'Giza',
        'FCMap_Helwan' => 'Helwan',
        'FCMap_Ismailia' => 'Ismailia',
        'FCMap_KafrAlsheikh' => 'Kafr Alsheikh',
        'FCMap_Luxer' => 'Luxer',
        'FCMap_Matrouh' => 'Matrouh',
        'FCMap_Monofiya' => 'Monofiya',
        'FCMap_NorthSinai' => 'North Sinai',
        'FCMap_PortSaid' => 'Port Said',
        'FCMap_Qalyoubiya' => 'Qalyoubiya',
        'FCMap_Qina' => 'Qina',
        'FCMap_RedSea' => 'Red Sea',
        'FCMap_SixOctober' => 'Six October',
        'FCMap_SouthSinai' => 'South Sinai',
        'FCMap_Suez' => 'Suez',
        'FCMap_Suhaj' => 'Suhaj',
        'FCMap_WadyGadid' => 'Wady Gadid',
  );
}

function _multisite_maps_get_Brazil_States() {
  return array(
        'FCMap_Acre' => 'Acre',
        'FCMap_Alagoas' => 'Alagoas',
        'FCMap_Amapa' => 'Amapa',
        'FCMap_Amazonas' => 'Amazonas',
        'FCMap_Bahia' => 'Bahia',
        'FCMap_Ceara' => 'Ceara',
        'FCMap_DistritoFederal' => 'Distrito Federal',
        'FCMap_EspiritoSanto' => 'Espirito Santo',
        'FCMap_Goias' => 'Goias',
        'FCMap_Maranhao' => 'Maranhao',
        'FCMap_MatoGrosso' => 'Mato Grosso',
        'FCMap_MatoGrossodoSul' => 'Mato Grossodo Sul',
        'FCMap_MinasGerais' => 'Minas Gerais',
        'FCMap_Para' => 'Para',
        'FCMap_Paraiba' => 'Paraiba',
        'FCMap_Parana' => 'Parana',
        'FCMap_Pernambuco' => 'Pernambuco',
        'FCMap_Piaui' => 'Piaui',
        'FCMap_RiodeJaneiro' => 'Rio de Janeiro',
        'FCMap_RioGrandedoNorte' => 'Rio Grande do Norte',
        'FCMap_RioGrandedoSul' => 'Rio Grande do Sul',
        'FCMap_Rondonia' => 'Rondonia',
        'FCMap_Roraima' => 'Roraima',
        'FCMap_SaoPaulo' => 'Sao Paulo',
        'FCMap_SantaCatarina' => 'Santa Catarina',
        'FCMap_Sergipe' => 'Sergipe',
        'FCMap_Tocantins' => 'Tocantins',
  );
}

function _multisite_maps_get_Caribbeans_Islands() {
  return array(
        'FCMap_CaribbeansRegion' => 'Caribbean Regions',
        'FCMap_Anguilla' => 'Anguilla',
        'FCMap_Aruba' => 'Aruba',
        'FCMap_Bonaire' => 'Bonaire',
        'FCMap_BritishVirginIsland' => 'British Virgin Island',
        'FCMap_Curacao' => 'Curacao',
        'FCMap_Guadaloupe' => 'Guadaloupe',
        'FCMap_Martinique' => 'Martinique',
        'FCMap_Monserrat' => 'Montserrat',
        'FCMap_SaintBarthelemey' => 'Saint Barthelemy',
        'FCMap_SaintEustatius' => 'Saint Eustatius',
        'FCMap_SaintMartin' => 'Saint Martin',
        'FCMap_TurksandCaicos' => 'Turks and Caicos',
        'FCMap_USVirginIsland' => 'US Virgin Island',
  );
}

function _multisite_maps_get_Mexico() {
  return array(
        'FCMap_Aguascalientes' => 'Aguascalientes',
        'FCMap_BajaCalifornia' => 'Baja California',
        'FCMap_BajaCaliforniaSur' => 'Baja California Sur',
        'FCMap_Campeche' => 'Campeche',
        'FCMap_Colima' => 'Colima',
        'FCMap_MexicoDistritoFederal' => 'Mexico Distrito Federal',
        'FCMap_Guanajuato' => 'Guanajuato',
        'FCMap_Nayarit' => 'Nayarit',
        'FCMap_QueretarodeArteaga' => 'Queretaro de Arteaga',
        'FCMap_QuintanaRoo' => 'Quintana Roo',
        'FCMap_Sonora' => 'Sonora',
        'FCMap_Tamaulipas' => 'Tamaulipas',
        'FCMap_Zacatecas' => 'Zacatecas',
  );
}

function _multisite_maps_get_Bulgaria_Provinces() {
  return array(
        'FCMap_Blagoevgrad' => 'Blagoevgrad',
        'FCMap_Burgas' => 'Burgas',
        'FCMap_Dobrich' => 'Dobrich',
        'FCMap_Gabrovo' => 'Gabrovo',
        'FCMap_GradSofia' => 'GradSofia (Sofia City)',
        'FCMap_Haskovo' => 'Haskovo',
        'FCMap_Kardzhali' => 'Kardzhali',
        'FCMap_Kyustendil' => 'Kyustendil',
        'FCMap_Lovech' => 'Lovech',
        'FCMap_BulgariaMontana' => 'Bulgaria Montana',
        'FCMap_Pazardzhik' => 'Pazardzhik',
        'FCMap_Pernik' => 'Pernik',
        'FCMap_Pleven' => 'Pleven',
        'FCMap_Plovdiv' => 'Plovdiv',
        'FCMap_Razgrad' => 'Razgrad',
        'FCMap_Ruse' => 'Ruse',
        'FCMap_Shumen' => 'Shumen',
        'FCMap_Silistra' => 'Silistra',
        'FCMap_Sliven' => 'Sliven',
        'FCMap_Smolyan' => 'Smolyan',
        'FCMap_Sofia' => 'Sofia (Province)',
        'FCMap_StaraZagora' => 'Stara Zagora',
        'FCMap_Targovishte' => 'Targovishte',
        'FCMap_Varna' => 'Varna',
        'FCMap_VelikoTarnovo' => 'Veliko Tarnovo',
        'FCMap_Vidin' => 'Vidin',
        'FCMap_Vratsa' => 'Vratsa',
        'FCMap_Yambol' => 'Yambol',
  );
}

function _multisite_maps_get_Denmark_Regions() {
  return array(
        'FCMap_Hovedstaden' => 'Hovedstaden',
        'FCMap_Midtjylland' => 'Midtjylland',
        'FCMap_Nordjylland' => 'Nordjylland',
        'FCMap_Sjaelland' => 'Sjaelland',
        'FCMap_Syddanmark' => 'Syddanmark',
  );
}

function _multisite_maps_get_Hungary_Regions() {
  return array(
        'FCMap_CentralHungary' => 'Central Hungary',
        'FCMap_CentralTransdanubia' => 'Central Transdanubia',
        'FCMap_NorthernGreatPlain' => 'Northern Great Plain',
        'FCMap_NorthernHungary' => 'Northern Hungary',
        'FCMap_SouthernGreatPlain' => 'Southern Great Plain',
        'FCMap_SouthernTransdanubia' => 'Southern Transdanubia',
        'FCMap_WesternTransdanubia' => 'Western Transdanubia',
  );
}

function _multisite_maps_get_Czech_Republic_District() {
  return array(
        'FCMap_CzechRepublicDistricts' => 'Czech Republic Districts',
  );
}

function _multisite_maps_get_Albania_Counties() {
  return array(
        'FCMap_Berat' => 'Berat',
        'FCMap_Diber' => 'Diber',
        'FCMap_Durres' => 'Durres',
        'FCMap_Elbasan' => 'Elbasan',
        'FCMap_Fier' => 'Fier',
        'FCMap_Gjirokaster' => 'Gjirokaster',
        'FCMap_Korce' => 'Korce',
        'FCMap_Kukes' => 'Kukes',
        'FCMap_Lezhe' => 'Lezhe',
        'FCMap_Shkoder' => 'Shkoder',
        'FCMap_Tirana' => 'Tirana',
        'FCMap_Vlore' => 'Vlore',
  );
}

function _multisite_maps_get_Estonia_Counties() {
  return array(
        'FCMap_Harjumaa' => 'Harjumaa',
        'FCMap_Hiiumaa' => 'Hiiumaa',
        'FCMap_Ida-Virumaa' => 'Ida-Virumaa',
        'FCMap_Jarvamaa' => 'Jarvamaa',
        'FCMap_Jogevamaa' => 'Jogevamaa',
        'FCMap_Laanemaa' => 'Laanemaa',
        'FCMap_LaaneVirumaa' => 'Laane-Virumaa',
        'FCMap_Parnumaa' => 'Parnumaa',
        'FCMap_Polvamaa' => 'Polvamaa',
        'FCMap_Raplamaa' => 'Raplamaa',
        'FCMap_Saaremaa' => 'Saaremaa',
        'FCMap_Tartumaa' => 'Tartumaa',
        'FCMap_Valgamaa' => 'Valgamaa',
        'FCMap_Viljandimaa' => 'Viljandimaa',
        'FCMap_Vorumaa' => 'Vorumaa',
  );
}

function _multisite_maps_get_Romania_Regions() {
  return array(
        'FCMap_RomaniaRegion' => 'Romania Region',
        'FCMap_BucurestiIlfov' => 'Bucuresti-Iifov',
        'FCMap_Centru' => 'Centru',
        'FCMap_NordEst' => 'Nord-Est',
        'FCMap_NordVest' => 'Nord-Vest',
        'FCMap_SudEst' => 'Sud-Est',
        'FCMap_SudMuntenia' => 'Sud-Muntenia',
        'FCMap_SudVestOltenia' => 'Sud-Vest Oltenia',
        'FCMap_Vest' => 'Vest',
  );
}

function _multisite_maps_get_Poland_Voivodeships() {
  return array(
        'FCMap_Dolnoslaskie' => 'Dolnoslaskie',
        'FCMap_KujawskoPomorskie' => 'Kujawsko-Pomorskie',
        'FCMap_Lodzkie' => 'Lodzkie',
        'FCMap_Lubelskie' => 'Lubelskie',
        'FCMap_Lubuskie' => 'Lubuskie',
        'FCMap_Malopolskie' => 'Malopolskie',
        'FCMap_Mazowieckie' => 'Mazowieckie',
        'FCMap_Opolskie' => 'Opolskie',
        'FCMap_Podkarpackie' => 'Podkarpackie',
        'FCMap_Podlaskie' => 'Podlaskie',
        'FCMap_Pomorskie' => 'Pomorskie',
        'FCMap_Slaskie' => 'Slaskie',
        'FCMap_Swietokrzyskie' => 'Swietokrzyskie',
        'FCMap_WarminskoMazurskie' => 'Warminsko-Mazurskie',
        'FCMap_Wielkopolskie' => 'Wielkopolskie',
        'FCMap_Zachodniopomorskie' => 'Zachodniopomorskie',
  );
}

function _multisite_maps_get_Norway_Regions() {
  return array(
        'FCMap_NorwayRegion' => 'Norway (Regions)',
        'FCMap_EasternNorway' => 'Eastern Norway',
        'FCMap_NorthernNorway' => 'Northern Norway',
        'FCMap_SouthernNorway' => 'Southern Norway',
        'FCMap_Trondelag' => 'Trondelag',
        'FCMap_WesternNorway' => 'Western Norway',
  );
}

function _multisite_maps_get_Norway_Counties() {
  return array(
        'FCMap_Akershus' => 'Akershus',
        'FCMap_AustAgder' => 'Aust-Agder',
        'FCMap_Buskerud' => 'Buskerud',
        'FCMap_Finnmark' => 'Finnmark',
        'FCMap_Hedmark' => 'Hedmark',
        'FCMap_Hordaland' => 'Hordaland',
        'FCMap_MoreogRomsdal' => 'More og Romsdal',
        'FCMap_NordTrondelag' => 'Nord-Trondelag',
        'FCMap_Nordland' => 'Nordland',
        'FCMap_Oppland' => 'Oppland',
        'FCMap_Oslo' => 'Oslo',
        'FCMap_Rogaland' => 'Rogaland',
        'FCMap_SognogFjordane' => 'Sogn og Fjordane',
        'FCMap_SorTrondelag' => 'Sor-Trondelag',
        'FCMap_Telemark' => 'Telemark',
        'FCMap_Troms' => 'Troms',
        'FCMap_VestAgder' => 'Vest-Agder',
        'FCMap_Vestfold' => 'Vestfold',
        'FCMap_Ostfold' => 'Ostfold',
  );
}

function _multisite_maps_get_Slovakia_Regions() {
  return array(
        'FCMap_BanskaBystrica' => 'Banska Bystrica',
        'FCMap_Bratislava' => 'Bratislava',
        'FCMap_Kosice' => 'Kosice',
        'FCMap_Nitra' => 'Nitra',
        'FCMap_Presov' => 'Presov',
        'FCMap_Trencin' => 'Trencin',
        'FCMap_Trnava' => 'Trnava',
        'FCMap_Zilina' => 'Zilina',
  );
}

function _multisite_maps_get_Belgium_Regions() {
  return array(
        'FCMap_Antwerp' => 'Antwerpen',
        'FCMap_Brussels' => 'Brussels',
        'FCMap_EastFlanders' => 'East Flanders',
        'FCMap_FlemishBrabant' => 'Flemish Brabant',
        'FCMap_Hainaut' => 'Hainaut',
        'FCMap_Liege' => 'Liege',
        'FCMap_LimburgBGomeenten' => 'Limburg',
        'FCMap_BelgiumLuxembourg' => 'Luxembourg',
        'FCMap_Namur' => 'Namur',
        'FCMap_WalloonBrabant' => 'Walloon Brabant',
        'FCMap_WestFlanders' => 'West Flanders',
  );
}

function _multisite_maps_get_Czech_Republic_Regions() {
  return array(
        'FCMap_CentralBohemianRegion' => 'Central Bohemian',
        'FCMap_HradecKralove' => 'Hradec Kralove',
        'FCMap_KarlovyVaryRegion' => 'Karlovy Vary',
        'FCMap_Liberec' => 'Liberec Region',
        'FCMap_MoraviaSilesia' => 'Moravia-Silesia',
        'FCMap_OlomoucRegion' => 'Olomouc',
        'FCMap_PardubiceRegion' => 'Pardubice',
        'FCMap_PlzenRegion' => 'Plzen',
        'FCMap_Prague' => 'Prague',
        'FCMap_SouthBohemia' => 'South Bohemia',
        'FCMap_SouthMoravia' => 'South Moravia',
        'FCMap_UstinadLabem' => 'Usti nad Labem',
        'FCMap_Vysocina' => 'Vysocina',
        'FCMap_Zlin' => 'Zlin',
  );
}

function _multisite_maps_get_France_Arrondisemants() {
  return array(
        'FCMap_IledeFrance' => 'Ile de France',
        'FCMap_Paris' => 'Paris',
        'FCMap_Lyon' => 'Lyon',
        'FCMap_Marseille' => 'Marseille',
  );
}

function _multisite_maps_get_Germany_States() {
  return array(
        'FCMap_BadenWurttemberg' => 'Baden-Wurttemberg',
        'FCMap_Bavaria' => 'Bavaria',
        'FCMap_Berlin' => 'Berlin',
        'FCMap_Brandenburg' => 'Brandenburg',
        'FCMap_Hesse' => 'Hesse',
        'FCMap_LowerSaxony' => 'Lower Saxony',
        'FCMap_MecklenburgVorpommern' => 'Mecklenburg-Vorpommern',
        'FCMap_NorthRhineWestphalia' => 'North Rhine-Westphalia',
        'FCMap_RhinelandPalatinate' => 'Rhineland-Palatinate',
        'FCMap_Saarland' => 'Saarland',
        'FCMap_SachsenAnhalt' => 'Sachsen-Anhalt',
        'FCMap_Saxony' => 'Saxony',
        'FCMap_SchleswigHolstein' => 'Schleswig-Holstein',
        'FCMap_Thuringia' => 'Thuringia',
  );
}

function _multisite_maps_get_Italy_Regions() {
  return array(
        'FCMap_Abruzzo' => 'Abruzzo',
        'FCMap_Apulia' => 'Apulia',
        'FCMap_Basilicata' => 'Basilicata',
        'FCMap_Calabria' => 'Calabria',
        'FCMap_Campania' => 'Campania',
        'FCMap_EmiliaRomagna' => 'Emilia Romagna',
        'FCMap_FriuliVeneziaGiulia' => 'Friuli Venezia Giulia',
        'FCMap_Lazio' => 'Lazio',
        'FCMap_Liguria' => 'Liguria',
        'FCMap_Lombardy' => 'Lombardy',
        'FCMap_Marche' => 'Marche',
        'FCMap_Molise' => 'Molise',
        'FCMap_Piedmont' => 'Piedmont',
        'FCMap_Sardinia' => 'Sardinia',
        'FCMap_Sicily' => 'Sicily',
        'FCMap_TrentinoAltoAdige/Sudtirol' => 'Trentino Alto Adige / Sudtirol',
        'FCMap_Tuscany' => 'Tuscany',
        'FCMap_Umbria' => 'Umbria',
        'FCMap_Veneto' => 'Veneto',
  );
}

function _multisite_maps_get_Sweden_Counties() {
  return array(
        'FCMap_Blekinge' => 'Blekinge',
        'FCMap_Dalarna' => 'Dalarna',
        'FCMap_Gavleborg' => 'Gavleborg',
        'FCMap_Halland' => 'Halland',
        'FCMap_Jamtland' => 'Jamtland',
        'FCMap_Jonkoping' => 'Jonkoping',
        'FCMap_Kalmar' => 'Kalmar',
        'FCMap_Kronoberg' => 'Kronoberg',
        'FCMap_Norrbotten' => 'Norrbotten',
        'FCMap_Orebro' => 'Orebro',
        'FCMap_Ostergotland' => 'Ostergotland',
        'FCMap_Skane' => 'Skane',
        'FCMap_Sodermanland' => 'Sodermanland',
        'FCMap_Stockholm' => 'Stockholm County',
        'FCMap_Uppsala' => 'Uppsala',
        'FCMap_Varmland' => 'Varmland',
        'FCMap_Vasterbotten' => 'Vasterbotten',
        'FCMap_Vasternorrland' => 'Vasternorrland',
        'FCMap_Vastmanland' => 'Vastmanland',
        'FCMap_VastraGotaland' => 'Vastra Gotaland',
  );
}

function _multisite_maps_get_Switzerland_Cantons() {
  return array(
        'FCMap_Aargau' => 'Aargau',
        'FCMap_AppenzellAusserrhoden' => 'Appenzell Ausserrhoden',
        'FCMap_AppenzellInnerrhoden' => 'Appenzell Innerrhoden',
        'FCMap_Bern' => 'Bern',
        'FCMap_BaselLandschaft' => 'Basel-Landschaft',
        'FCMap_Fribourg' => 'Fribourg',
        'FCMap_Geneva' => 'Geneva',
        'FCMap_Graubunden' => 'Graubunden',
        'FCMap_Jura' => 'Jura',
        'FCMap_Lucerne' => 'Lucerne',
        'FCMap_Neuchatel' => 'Neuchatel',
        'FCMap_Nidwalden' => 'Nidwalden',
        'FCMap_Obwalden' => 'Obwalden',
        'FCMap_Schaffhausen' => 'Schaffhausen',
        'FCMap_Schwyz' => 'Schwyz',
        'FCMap_Solothurn' => 'Solothurn',
        'FCMap_SaintGallen' => 'St. Gallen',
        'FCMap_Thurgau' => 'Thurgau',
        'FCMap_Ticino' => 'Ticino',
        'FCMap_Valais' => 'Valais',
        'FCMap_Vaud' => 'Vaud',
        'FCMap_Zurich' => 'Zurich',
  );
}

function _multisite_maps_get_Austria_States() {
  return array(
        'FCMap_Burgenland' => 'Burgenland',
        'FCMap_Karnten' => 'Karnten (Carinthia)',
        'FCMap_Niederosterreich' => 'Niederosterreich',
        'FCMap_Oberosterreich' => 'Oberosterreich',
        'FCMap_Salzburg' => 'Salzburg',
        'FCMap_Steiermark' => 'Steiermark (Styria)',
        'FCMap_Tirol' => 'Tirol (Tyrol)',
        'FCMap_Vorarlberg' => 'Vorarlberg',
        'FCMap_Wien' => 'Wien (Vienna)',
  );
}

function _multisite_maps_get_Portugal_Districts() {
  return array(
        'FCMap_Aveiro' => 'Aveiro',
        'FCMap_Beja' => 'Beja',
        'FCMap_Braga' => 'Braga',
        'FCMap_Braganca' => 'Braganca',
        'FCMap_CasteloBranco' => 'Castelo Branco',
        'FCMap_Coimbra' => 'Coimbra',
        'FCMap_Evora' => 'Evora',
        'FCMap_Faro' => 'Faro',
        'FCMap_Guarda' => 'Guarda',
        'FCMap_Lieria' => 'Lieria',
        'FCMap_Lisboa' => 'Lisboa',
        'FCMap_Portalegre' => 'Portalegre',
        'FCMap_Porto' => 'Porto',
        'FCMap_Santarem' => 'Santarem',
        'FCMap_Setubal' => 'Setubal',
        'FCMap_VianadoCastelo' => 'Vianado Castelo',
        'FCMap_VilaReal' => 'Vila Real',
        'FCMap_Viseu' => 'Viseu',
  );
}

function _multisite_maps_get_Australia_States() {
  return array(
        'FCMap_AustralianCapitalTerritory' => 'Australian Capital Territory',
        'FCMap_NewSouthWales' => 'New South Wales',
        'FCMap_NorthernTerritory' => 'Northern Territory',
        'FCMap_Queensland' => 'Queensland',
        'FCMap_SouthAustralia' => 'South Australia',
        'FCMap_Tasmania' => 'Tasmania',
        'FCMap_Victoria' => 'Victoria',
        'FCMap_WesternAustralia' => 'Western Australia',
  );
}

function _multisite_maps_get_New_Zealand_Provinces() {
  return array(
        'FCMap_Auckland' => 'Auckland',
        'FCMap_BayOfPlenty' => 'Bay Of Plenty',
        'FCMap_Canterbury' => 'Canterbury',
        'FCMap_Gisborne' => 'Gisborne',
        'FCMap_HawkesBay' => 'Hawkes Bay',
        'FCMap_ManawatuWanganui' => 'Manawatu Wanganui',
        'FCMap_Marlborough' => 'Marlborough',
        'FCMap_Nelson' => 'Nelson',
        'FCMap_Northland' => 'Northland',
        'FCMap_Otago' => 'Otago',
        'FCMap_Southland' => 'Southland',
        'FCMap_Taranaki' => 'Taranaki',
        'FCMap_Tasman' => 'Tasman',
        'FCMap_Waikato' => 'Waikato',
        'FCMap_Wellington' => 'Wellington',
        'FCMap_WestCoast' => 'West Coast',
  );
}

function _multisite_maps_get_USA_States_Area_Code() {
  return array(
        'FCMap_AlabamaAreaCode' => 'Alabama Area Code',
        'FCMap_AlaskaAreaCode' => 'Alaska Area Code',
        'FCMap_ArizonaAreaCode' => 'Arizona Area Code',
        'FCMap_ArkansasAreaCode' => 'Arkansas Area Code',
        'FCMap_BostonAreaCode' => 'Boston Area Code',
        'FCMap_CaliforniaAreaCode' => 'California Area Code',
        'FCMap_ChicagoAreaCode' => 'Chicago Area Code',
        'FCMap_ColoradoAreaCode' => 'Colorado Area Code',
        'FCMap_ConnecticutAreaCode' => 'Connecticut Area Code',
        'FCMap_DallasFortWorthAreaCode' => 'DallasFortWorth Area Code',
        'FCMap_DelawareAreaCode' => 'Delaware Area Code',
        'FCMap_DetroitAreaCode' => 'Detroit Area Code',
        'FCMap_DistrictofColumbiaAreaCode' => 'District of Columbia Area Code',
        'FCMap_FloridaAreaCode' => 'Florida Area Code',
        'FCMap_GeorgiaAreaCode' => 'Georgia Area Code',
        'FCMap_HawaiiAreaCode' => 'Hawaii Area Code',
        'FCMap_IdahoAreaCode' => 'Idaho Area Code',
        'FCMap_IllinoisAreaCode' => 'Illinois Area Code',
        'FCMap_IndianaAreaCode' => 'Indiana Area Code',
        'FCMap_IowaAreaCode' => 'Iowa Area Code',
        'FCMap_KansasAreaCode' => 'Kansas Area Code',
        'FCMap_KentuckyAreaCode' => 'Kentucky Area Code',
        'FCMap_LouisianaAreaCode' => 'Louisiana Area Code',
        'FCMap_MaineAreaCode' => 'Maine Area Code',
        'FCMap_MarylandAreaCode' => 'Maryland Area Code',
        'FCMap_MassachusettsAreaCode' => 'Massachusetts Area Code',
        'FCMap_MichiganAreaCode' => 'Michigan Area Code',
        'FCMap_MinnesotaAreaCode' => 'Minnesota Area Code',
        'FCMap_MississippiAreaCode' => 'Mississippi Area Code',
        'FCMap_MissouriAreaCode' => 'Missouri Area Code',
        'FCMap_MontanaAreaCode' => 'Montana Area Code',
        'FCMap_NebraskaAreaCode' => 'Nebraska Area Code',
        'FCMap_NevadaAreaCode' => 'Nevada Area Code',
        'FCMap_NewHampshireAreaCode' => 'New Hampshire Area Code',
        'FCMap_NewJerseyAreaCode' => 'New Jersey Area Code',
        'FCMap_NewMexicoAreaCode' => 'New Mexico Area Code',
        'FCMap_NewYorkareaAreaCode' => 'New York area Area Code',
        'FCMap_NewYorkAreaCode' => 'New York Area Code',
        'FCMap_NorthCarolinaAreaCode' => 'North Carolina Area Code',
        'FCMap_NorthDakotaAreaCode' => 'North Dakota Area Code',
        'FCMap_NorthernCaliforniaBayAreaCode' => 'Northern California Bay Area Code',
        'FCMap_OhioAreaCode' => 'Ohio Area Code',
        'FCMap_OklahomaAreaCode' => 'Oklahoma Area Code',
        'FCMap_OregonAreaCode' => 'Oregon Area Code',
        'FCMap_PennsylvaniaAreaCode' => 'Pennsylvania Area Code',
        'FCMap_PhoenixAreaCode' => 'Phoenix Area Code',
        'FCMap_RhodeIslandAreaCode' => 'Rhode Island Area Code',
        'FCMap_SeattleAreaCode' => 'Seattle Area Code',
        'FCMap_SouthCarolinaAreaCode' => 'South Carolina Area Code',
        'FCMap_SouthDakotaAreaCode' => 'South Dakota Area Code',
        'FCMap_SouthernCaliforniaLAAreaCode' => 'Southern California LA Area Code',
        'FCMap_TennesseeAreaCode' => 'Tennessee Area Code',
        'FCMap_TexasAreaCode' => 'Texas Area Code',
        'FCMap_UtahAreaCode' => 'Utah Area Code',
        'FCMap_VermontAreaCode' => 'Vermont Area Code',
        'FCMap_VirginiaAreaCode' => 'Virginia Area Code',
        'FCMap_WashingtonAreaCode' => 'Washington Area Code',
        'FCMap_WestVirginiaAreaCode' => 'West Virginia Area Code',
        'FCMap_WisconsinAreaCode' => 'Wisconsin Area Code',
        'FCMap_WyomingAreaCode' => 'Wyoming Area Code',
  );
}

function _multisite_maps_get_USA_Congressional() {
  return array(
        'FCMap_AlabamaCongressional' => 'Alabama Congressional',
        'FCMap_AlaskaCongressional' => 'Alaska Congressional',
        'FCMap_AmericanSamoaCongressional' => 'American Samoa Congressional',
        'FCMap_ArizonaCongressional' => 'Arizona Congressional',
        'FCMap_ArkansasCongressional' => 'Arkansas Congressional',
        'FCMap_CaliforniaCongressional' => 'California Congressional',
        'FCMap_ColoradoCongressional' => 'Colorado Congressional',
        'FCMap_ConnecticutCongressional' => 'Connecticut Congressional',
        'FCMap_DelawareCongressional' => 'Delaware Congressional',
        'FCMap_DistrictofColumbiaCongressional' => 'District of Columbia Congressional',
        'FCMap_FloridaCongressional' => 'Florida Congressional',
        'FCMap_GeorgiaCongressional' => 'Georgia Congressional',
        'FCMap_GuamCongressional' => 'Guam Congressional',
        'FCMap_HawaiiCongressional' => 'Hawaii Congressional',
        'FCMap_IdahoCongressional' => 'Idaho Congressional',
        'FCMap_IllinoisCongressional' => 'Illinois Congressional',
        'FCMap_IndianaCongressional' => 'Indiana Congressional',
        'FCMap_IowaCongressional' => 'Iowa Congressional',
        'FCMap_KansasCongressional' => 'Kansas Congressional',
        'FCMap_KentuckyCongressional' => 'Kentucky Congressional',
        'FCMap_LouisianaCongressional' => 'Louisiana Congressional',
        'FCMap_MaineCongressional' => 'Maine Congressional',
        'FCMap_MarylandCongressional' => 'Maryland Congressional',
        'FCMap_MassachusettsCongressional' => 'Massachusetts Congressional',
        'FCMap_MichiganCongressional' => 'Michigan Congressional',
        'FCMap_MinnesotaCongressional' => 'Minnesota Congressional',
        'FCMap_MississippiCongressional' => 'Mississippi Congressional',
        'FCMap_MissouriCongressional' => 'Missouri Congressional',
        'FCMap_MontanaCongressional' => 'Montana Congressional',
        'FCMap_NebraskaCongressional' => 'Nebraska Congressional',
        'FCMap_NevadaCongressional' => 'Nevada Congressional',
        'FCMap_NewHampshireCongressional' => 'New Hampshire Congressional',
        'FCMap_NewjerseyCongressional' => 'New Jersey Congressional',
        'FCMap_NewMexicoCongressional' => 'New Mexico Congressional',
        'FCMap_NewYorkCongressional' => 'New York Congressional',
        'FCMap_NorthCarolinaCongressional' => 'North Carolina Congressional',
        'FCMap_NorthDakotaCongressional' => 'North Dakota Congressional',
        'FCMap_OhioCongressional' => 'Ohio Congressional',
        'FCMap_OklahomaCongressional' => 'Oklahoma Congressional',
        'FCMap_OregonCongressional' => 'Oregon Congressional',
        'FCMap_PennsylvaniaCongressional' => 'Pennsylvania Congressional',
        'FCMap_PuertoRicoCongressional' => 'Puerto Rico Congressional',
        'FCMap_RhodeIslandCongressional' => 'Rhode Island Congressional',
        'FCMap_SouthCarolinaCongressional' => 'South Carolina Congressional',
        'FCMap_SouthDakotaCongressional' => 'South Dakota Congressional',
        'FCMap_TennesseeCongressional' => 'Tennessee Congressional',
        'FCMap_TexasCongressional' => 'Texas Congressional',
        'FCMap_USVirginIslandsCongressional' => 'US VirginIslands Congressional',
        'FCMap_UtahCongressional' => 'Utah Congressional',
        'FCMap_VermontCongressional' => 'Vermont Congressional',
        'FCMap_VirginiaCongressional' => 'Virginia Congressional',
        'FCMap_WashingtonCongressional' => 'Washington Congressional',
        'FCMap_WestVirginiaCongressional' => 'West Virginia Congressional',
        'FCMap_WisconsinCongressional' => 'Wisconsin Congressional',
        'FCMap_WyomingCongressional' => 'Wyoming Congressional',
  );
}

function _multisite_maps_get_USA_DMA() {
  return array(
        'FCMap_EastNorthCentralDMA' => 'East North Central DMA',
        'FCMap_EastSouthCentralDMA' => 'East South Central DMA',
        'FCMap_MiddleAtlanticDMA' => 'Middle Atlantic DMA',
        'FCMap_MountainDMA' => 'Mountain DMA',
        'FCMap_NewEnglandDMA' => 'New England DMA',
        'FCMap_PacificDMA' => 'Pacific DMA',
        'FCMap_SouthAtlanticDMA' => 'South Atlantic DMA',
        'FCMap_USADMA' => 'USA DMA',
        'FCMap_WestNorthCentralDMA' => 'West North Central DMA',
        'FCMap_WestSouthCentralDMA' => 'West South Central DMA',
  );
}

function _multisite_maps_get_TimeZone() {
  return array(
        'FCMap_USATimeZone' => 'USA Time Zone',
  );
}
