<?php

/**
 * @file
 * Code for the News feature.
 */

include_once 'news_og.features.inc';
include_once 'news_og.views_alter.inc';

/**
 * Implements hook_modules_enabled().
 */
function news_og_modules_enabled($modules) {
  if (in_array('news_og', $modules)) {

    // Force feature revert to update og permissions.
    features_revert(array('news_og' => array('og_features_permission')));
  }
}

/**
 * Implements hook_menu().
 */
function news_og_menu() {
  $items = array();

  $items['community/%group_name/news'] = array(
    'title' => 'News',
    'page callback' => 'views_page',
    'page arguments' => array('news', 'page', 1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-communities-menu',
    'weight' => 1,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function news_og_form_news_node_form_alter(&$form, &$form_state, $form_id) {
  $desc = $form['field_top_news'][LANGUAGE_NONE]['#description'];
  $form['field_top_news'][LANGUAGE_NONE]['#description'] = $desc . " " . t('(The visibility of the news must be set to public to appear on the site homepage)');
}
