<?php

/**
 * @file
 * Install, update and uninstall functions for the STARTERKIT module.
 *
 * @see https://webgate.ec.europa.eu/CITnet/confluence/display/MULTISITE/Custom+features
 */

include_once 'STARTERKIT.install.inc';

/**
 * Implements hook_enable().
 */
function STARTERKIT_enable() {

  // Add your custom block to the context
  multisite_drupal_toolbox_add_block_context($contextName,$blockTitle,$module,$delta, $region,$weight='-10');

  // Add a view to a context
  multisite_drupal_toolbox_add_views_context($contextName,$viewTitle);

  // Add your custom content type to the context
  multisite_drupal_toolbox_add_content_type_context($contextName, $contentType);

  // When a new feature provide a content type, you may want that this content type can be referred by a simplenews content
  multisite_drupal_toolbox_simplenews_related_content_type('YOUR_CONTENT_TYPE', 'add');

  // @todo study the confusion created by this function
  //multisite_drupal_toolbox_add_content_type_newsletters('wiki');

  // add type to linkchecker scan
  multisite_drupal_toolbox_content_type_linkchecker('wiki', 'add');

  // solR configuration add bundle
  multisite_drupal_toolbox_config_solr_bundle('YOUR_CONTENT_TYPE', 'add');

  // Verbosity
  drupal_set_message(t('STARTERKIT %v feature is now active on your site.', array('%v' => _STARTERKIT_get_version())));
}

/**
 * Implements hook_disable().
 */
function STARTERKIT_disable() {

  // Remove your custom block to the context
  multisite_drupal_toolbox_remove_block_context($contextName,$blockTitle);

  // Remove your view from the context
  multisite_drupal_toolbox_remove_views_context($contextName,$viewTitle);

  // If you add the content type you must also add the function multisite_drupal_toolbox_remove_content_type_context to disable the views:
  multisite_drupal_toolbox_remove_content_type_context($contextName,$contentType);

  // Add type to the simplenews related content
  multisite_drupal_toolbox_simplenews_related_content_type('YOUR_CONTENT_TYPE', delete);

  // Remove type to linkchecker scan
  multisite_drupal_toolbox_content_type_linkchecker('wiki', 'delete');

  // Remove your custom content type
  multisite_drupal_toolbox_disable_content_type('YOUR_CONTENT_TYPE');

  // solR configuration delete bundle
  multisite_drupal_toolbox_config_solr_bundle('YOUR_CONTENT_TYPE', 'delete');

  // Disable/Uninstall dependencies
  if( module_exists('MODULE')) {
    module_disable(array('MODULE'));
    drupal_uninstall_modules(array('MODULE'));
  }

    // Administrator
  $role_rid = multisite_drupal_toolbox_get_rid('your role here');
  user_role_revoke_permissions($role_rid, array(
    'your custom permission here',
  ));

  // Verbosity
  drupal_set_message(t('STARTERKIT %v feature is now inactive on your site.', array('%v' => _STARTERKIT_get_version())));



  }


/**
 * Implements hook_install().
 */
function STARTERKIT_install() {
  //Install scripts here

}

/**
 * Implements hook_uninstall().
 */
function STARTERKIT_uninstall() {
  //Uninstall scripts here
}