<?php
/**
 * @file
 * Code for the CCE_basic_config feature.
 */

include_once('cce_basic_config.features.inc');

/*
* hook_modules_enabled
*/
function cce_basic_config_modules_enabled($modules) {
  include_once DRUPAL_ROOT . '/includes/password.inc';

  if(in_array('cce_basic_config', $modules)) { 
    
    // add users acccounts -----------------------------------------------------------------------------------------------------------------------------------------------------
    $account = new StdClass();
    $account->is_new = TRUE;
    $account->status = TRUE;
    $account->name = 'administrator';
    $account->pass = user_hash_password('pass');
    $account->mail = 'administrator@test.com';
    $account->init = 'administrator@test.com';
    $account->roles[3] = 'administrator';
    $account->field_firstname['und'][0]['value'] = 'John';
    $account->field_lastname['und'][0]['value'] = 'Smith'; 
    user_save($account);  
    
    $account1 = new StdClass();
    $account1->is_new = TRUE;
    $account1->status = TRUE;
    $account1->name = 'contributor';
    $account1->pass = user_hash_password('pass');
    $account1->mail = 'contributor@test.com';
    $account1->init = 'contributor@test.com';
    $account1->roles[4] = 'contributor';
    $account1->field_firstname['und'][0]['value'] = 'John';
    $account1->field_lastname['und'][0]['value'] = 'Doe';  
    user_save($account1);  

    
    // affect dummy contents to the user 'administrator' ---------------------------------------------------------------------------------------------------------------
    $query = db_select('node', 'n');
    $query->condition('n.type', 'article', '=')
      ->fields('n', array('nid', 'title', 'uid'));
    $results = $query->execute()->fetchAll(PDO::FETCH_ASSOC);

    foreach($results as $result) {
      $node = node_load($result['nid']);
      $node->uid = $account->uid;
      node_save($node);
    }
    
  }
  
}

/*
* hook_enable
*/
function cce_basic_config_enable(){
  _add_block_context('site_wide','user-menu','system','user-menu', 'tools');
  _add_block_context('site_wide','form','search','form', 'tools');

}
