<?php
/**
 * @file
 * Code for the CCE_basic_config feature.
 */

include_once('cce_basic_config.features.inc');

/*
* hook_enable
*/
function cce_basic_config_enable() {
  include_once DRUPAL_ROOT . '/includes/password.inc';

  // add users acccounts -----------------------------------------------------------------------------------------------------------------------------------------------------
  $account = new StdClass();
  $account->is_new = TRUE;
  $account->status = TRUE;
  $account->name = 'administrator';
  $account->pass = user_hash_password('pass');
  $account->mail = 'administrator@test.com';
  $account->init = 'administrator@test.com';
  $account->roles[3] = 'administrator';
  $account->field_firstname['und'][0]['value'] = 'John';
  $account->field_lastname['und'][0]['value'] = 'Smith'; 
  user_save($account);  
    
  $account1 = new StdClass();
  $account1->is_new = TRUE;
  $account1->status = TRUE;
  $account1->name = 'contributor';
  $account1->pass = user_hash_password('pass');
  $account1->mail = 'contributor@test.com';
  $account1->init = 'contributor@test.com';
  $account1->roles[4] = 'contributor';
  $account1->field_firstname['und'][0]['value'] = 'John';
  $account1->field_lastname['und'][0]['value'] = 'Doe';  
  user_save($account1);  

    
  // affect dummy contents to the user 'administrator' ---------------------------------------------------------------------------------------------------------------
  $query = db_select('node', 'n');
  $query->condition('n.type', 'article', '=')
    ->fields('n', array('nid', 'title', 'uid'));
  $results = $query->execute()->fetchAll(PDO::FETCH_ASSOC);

  foreach($results as $result) {
    $node = node_load($result['nid']);
    $node->uid = $account->uid;
    node_save($node);
  }

	
  // add 2 blocks in site-wide context -------------------------------------------------------------------------------
  $context=module_invoke('context','load','site_wide'); 
  $blockToAdd1 = array(
    'module' => 'system',
    'delta' =>  'user-menu',
	'region' => 'tools',
	'weight' => 1,
  ); 
  $context->reactions['block']['blocks']['user-menu']=$blockToAdd1;	
  
  /*$blockToAdd2 = array(
    'module' => 'search',
    'delta' =>  'form',
    'region' => 'tools',
    'weight' => 2,
  ); 
  $context->reactions['block']['blocks']['form']=$blockToAdd2;	  */
	  
  $blockToAdd3 = array(
    'module' => 'locale',
    'delta' =>  'language',
	'region' => 'highlighted',
	'weight' => 1,
  ); 
  $context->reactions['block']['blocks']['language']=$blockToAdd3;		  
	  
  $blockToAdd4 = array(
    'module' => 'system',
    'delta' =>  'main-menu',
	'region' => 'featured',
	'weight' => 1,
  ); 
  $context->reactions['block']['blocks']['main-menu']=$blockToAdd4;		  
	  
  module_invoke('context','save',$context);	
  
  // _add_block_context('communities','multisite_og_button-og-contextual-links','multisite_og_button','og-contextual-links', 'sidebar_first','-9');
  // _add_block_context('site_wide','locale-language','locale','language','highlighted');	
  // _add_block_context('site_wide','system-main-menu','system','main-menu','featured');	  

}

function cce_basic_config_menu_alter(&$items) {
  // hide default search tab ---------------------------------------------------------------------------------------------  
  $items['search/node']['access callback'] = FALSE;
}
