<?php

/**
 * @file
 * Code for the Survey og install file.
 */

/**
 * Implements hook_enable().
 */
function survey_og_enable() {
  multisite_drupal_toolbox_add_views_context("communities", "surveys_list");

  multisite_drupal_toolbox_add_content_type_context('communities', 'webform');
  multisite_drupal_toolbox_add_path_context('communities', 'urvey_analysis/*');

  multisite_drupal_toolbox_add_path_context('communities_menu_item', 'community/*/survey/*');
  multisite_drupal_toolbox_add_views_context('communities_menu_item', 'surveys_list:page_1');

  // Override drupal variable defined in core feature.
  variable_set('pathauto_node_webform_pattern', 'community/[node:og_group_ref]/survey/[node:title]');

  drupal_flush_all_caches();
}


/**
 * Implements hook_disable().
 */
function survey_og_disable() {

  // Remove block.
  multisite_drupal_toolbox_remove_views_context("communities", "surveys_list");

  multisite_drupal_toolbox_remove_content_type_context('communities', 'webform');

  multisite_drupal_toolbox_remove_path_context('communities_menu_item', 'community/*/survey/*');
  multisite_drupal_toolbox_remove_views_context('communities_menu_item', 'surveys_list:page_1');

  // Delete drupal variables.
  variable_del('pathauto_node_webform_pattern');
}


/**
 * Add survey options on "communities_menu_item" context.
 */
function survey_og_update_7102() {
  multisite_drupal_toolbox_add_path_context('communities_menu_item', 'community/*/survey/*');
  multisite_drupal_toolbox_add_views_context('communities_menu_item', 'surveys_list:page_1');
}
