<?php
/**
 * @file
 * Install, update and uninstall functions for the sitemap module.
 *
 * @see https://webgate.ec.europa.eu/CITnet/confluence/display/MULTISITE/Custom+features
 */

include_once 'sitemap.install.inc';

/**
 * Implements hook_enable().
 */

function sitemap_enable() {
  $item = array(
    'link_path' => 'sitemap',
    'link_title' => t('Site map'),
    'menu_name' => 'main-menu',
    'weight' => '50'
  );
  menu_link_save($item);
  drupal_set_message(t('Sitemap %v feature is now active on your site.', array('%v' => _sitemap_get_version())));
}

/**
 * Implements hook_disable().
 */

function sitemap_disable() {
  menu_link_delete(NULL, 'sitemap');
  module_disable(array('xmlsitemap'), FALSE);
  drupal_uninstall_modules(array('xmlsitemap'), TRUE);
  //Activation message
  drupal_set_message(t('Sitemap %v feature is now inactive on your site.', array('%v' => _sitemap_get_version())));
}


/**
 * Implements hook_install().
 */
function sitemap_install() {
  //Install scripts here
}

/**
 * Implements hook_uninstall().
 */
function sitemap_uninstall() {
  //Uninstall scripts here
}