<?php
/**
 * @file
 * Install the feature e_library
 */

/**
 * hook_install
 */
function e_library_install() {
  //Nothing yet
}

/**
 * hook_uninstall
 */
function e_library_uninstall() {
  //Nothing yet
}


/**
* Add block to the context
*/
function e_library_enable(){
	multisite_drupal_toolbox_add_views_context('communities','e_library');
	multisite_drupal_toolbox_add_views_context('communities','e_library:page');
	multisite_drupal_toolbox_add_content_type_context('communities', 'document');
	
	//Activation message
	drupal_set_message('E-library feature is now active on your site.');
}


/**
* Remove block from the context
*/
function e_library_disable(){
	multisite_drupal_toolbox_remove_views_context('communities','e_library');
	multisite_drupal_toolbox_remove_views_context('communities','e_library:page');
	multisite_drupal_toolbox_remove_content_type_context('communities', 'document');
	multisite_drupal_toolbox_disable_content_type('document');
	
	//Activation message
	drupal_set_message('E-library feature is now disabled on your site.');
}
