<?php

/**
 * @file
 * Exposes API for configuration staging.
 */

/**
 * Very simple service container.
 *
 * Usage:
 * multisite_config_service('system')->getVariable('site_name').
 *
 * @param string $module
 *    Module name.
 *
 * @return mixed
 *    Configuration API object.
 */
function multisite_config_service($module) {
  $class = "\\Drupal\\{$module}\\Config";
  return class_exists($class) ? new $class() : new \Drupal\multisite_config\ConfigBase();
}
