ReadSpeaker.lib||(ReadSpeaker.lib={});
(function(x,G){function q(i,a,d,c){for(var e=0,da=a.length;e<da;e++)m(i,a[e],d,c)}function a(i,a,d){var c=a.dir,ca=W++;i||(i=function(i){return i===d});return a.first?function(a,b){for(;a=a[c];)if(1===a.nodeType)return i(a,b)&&a}:function(a,b){for(var d,g=ca+"."+f,h=g+"."+e;a=a[c];)if(1===a.nodeType){if((d=a[n])===h)return a.sizset;if("string"===typeof d&&0===d.indexOf(g)){if(a.sizset)return a}else{a[n]=h;if(i(a,b))return a.sizset=!0,a;a.sizset=!1}}}}function c(i,a){return i?function(d,c){var e=a(d,
c);return e&&i(!0===e?d:e,c)}:a}var e,f,g,h,H,t=x.document,u=t.documentElement,I=!1,X=!0,W=0,C=[].slice,E=[].push,n=("sizcache"+Math.random()).replace(".",""),A="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w#")+")|)|)[\\x20\\t\\r\\n\\f]*\\]",z="(?=[^\\x20\\t\\r\\n\\f])(?:\\\\.|"+A+"|"+":((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|((?:[^,]|\\\\,|(?:,(?=[^\\[]*\\]))|(?:,(?=[^\\(]*\\))))*))\\)|)".replace(2,
7)+"|[^\\\\(),])+",M=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),J=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,N=RegExp(z+"?(?=[\\x20\\t\\r\\n\\f]*,|$)","g"),Y=RegExp("^(?:(?!,)(?:(?:^|,)[\\x20\\t\\r\\n\\f]*"+z+")*?|[\\x20\\t\\r\\n\\f]*(.*?))(\\)|$)"),ea=RegExp(z.slice(19,-6)+"\\x20\\t\\r\\n\\f>+~])+|[\\x20\\t\\r\\n\\f]*([\\x20\\t\\r\\n\\f>+~])[\\x20\\t\\r\\n\\f]*","g"),fa=/^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,O=/[\x20\t\r\n\f]*[+~]/,ga=/:not\($/,ha=
/h\d/i,ia=/input|select|textarea|button/i,F=/\\(?!\\)/g,D={ID:/^#((?:\\.|[-\w]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[-\w]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[-\w]|[^\x00-\xa0])+)['"]?\]/,TAG:RegExp("^("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("[-","[-\\*")+")"),ATTR:RegExp("^"+A),PSEUDO:RegExp("^:((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|((?:[^,]|\\\\,|(?:,(?=[^\\[]*\\]))|(?:,(?=[^\\(]*\\))))*))\\)|)"),CHILD:RegExp("^:(only|nth|last|first)-child(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),POS:RegExp(":(nth|eq|gt|lt|first|last|even|odd)(?:\\((\\d*)\\)|)(?=[^-]|$)","ig"),needsContext:/^[\x20\t\r\n\f]*[>+~]|:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\)|)(?=[^-]|$)/i},P={},Q=[],R={},S=[],A=function(i){i.sizzleFilter=!0;return i},z=function(i){return function(a){return"input"===a.nodeName.toLowerCase()&&a.type===i}},Z=function(i){return function(a){var d=a.nodeName.toLowerCase();return("input"===d||"button"===d)&&a.type===i}},B=function(i){var a=!1,d=t.createElement("div");try{a=
i(d)}catch(c){}return a},ja=B(function(i){i.innerHTML="<select></select>";i=typeof i.lastChild.getAttribute("multiple");return"boolean"!==i&&"string"!==i}),ka=B(function(i){i.id=n+0;i.innerHTML="<a name='"+n+"'></a><div name='"+n+"'></div>";u.insertBefore(i,u.firstChild);var a=t.getElementsByName&&t.getElementsByName(n).length===2+t.getElementsByName(n+0).length;H=!t.getElementById(n);u.removeChild(i);return a}),la=B(function(i){i.appendChild(t.createComment(""));return 0===i.getElementsByTagName("*").length}),
ma=B(function(i){i.innerHTML="<a href='#'></a>";return i.firstChild&&"undefined"!==typeof i.firstChild.getAttribute&&"#"===i.firstChild.getAttribute("href")}),$=B(function(i){i.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";if(!i.getElementsByClassName||0===i.getElementsByClassName("e").length)return!1;i.lastChild.className="e";return 1!==i.getElementsByClassName("e").length}),m=function(i,a,d,c){var d=d||[],a=a||t,e,f,j,g,h=a.nodeType;if(1!==h&&9!==h)return[];if(!i||"string"!==
typeof i)return d;j=T(a);if(!j&&!c&&(e=fa.exec(i)))if(g=e[1])if(9===h)if((f=a.getElementById(g))&&f.parentNode){if(f.id===g)return d.push(f),d}else return d;else{if(a.ownerDocument&&(f=a.ownerDocument.getElementById(g))&&na(a,f)&&f.id===g)return d.push(f),d}else{if(e[2])return E.apply(d,C.call(a.getElementsByTagName(i),0)),d;if((g=e[3])&&$&&a.getElementsByClassName)return E.apply(d,C.call(a.getElementsByClassName(g),0)),d}return U(i,a,d,c,j)},k=m.selectors={cacheLength:50,match:D,order:["ID","TAG"],
attrHandle:{},createPseudo:A,find:{ID:H?function(a,b,d){if("undefined"!==typeof b.getElementById&&!d)return(a=b.getElementById(a))&&a.parentNode?[a]:[]}:function(a,b,d){if("undefined"!==typeof b.getElementById&&!d)return(b=b.getElementById(a))?b.id===a||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").value===a?[b]:G:[]},TAG:la?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:function(a,b){var d=b.getElementsByTagName(a);if("*"===a){for(var e,
c=[],f=0;e=d[f];f++)1===e.nodeType&&c.push(e);return c}return d}},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(F,"");a[3]=(a[4]||a[5]||"").replace(F,"");"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1]?(a[2]||m.error(a[0]),a[3]=+(a[3]?a[4]+(a[5]||1):2*("even"===a[2]||"odd"===a[2])),a[4]=+(a[6]+a[7]||"odd"===
a[2])):a[2]&&m.error(a[0]);return a},PSEUDO:function(a){var b,d=a[4];if(D.CHILD.test(a[0]))return null;if(d&&(b=Y.exec(d))&&b.pop())a[0]=a[0].slice(0,b[0].length-d.length-1),d=b[0].slice(0,-1);a.splice(2,3,d||a[3]);return a}},filter:{ID:H?function(a){a=a.replace(F,"");return function(b){return b.getAttribute("id")===a}}:function(a){a=a.replace(F,"");return function(b){return(b="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id"))&&b.value===a}},TAG:function(a){if("*"===a)return function(){return!0};
a=a.replace(F,"").toLowerCase();return function(b){return b.nodeName&&b.nodeName.toLowerCase()===a}},CLASS:function(a){var b=P[a];b||(b=P[a]=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),Q.push(a),Q.length>k.cacheLength&&delete P[Q.shift()]);return function(a){return b.test(a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}},ATTR:function(a,b,d){return!b?function(b){return null!=m.attr(b,a)}:function(e){var e=m.attr(e,a),c=e+"";if(null==e)return"!="===
b;switch(b){case "=":return c===d;case "!=":return c!==d;case "^=":return d&&0===c.indexOf(d);case "*=":return d&&-1<c.indexOf(d);case "$=":return d&&c.substr(c.length-d.length)===d;case "~=":return-1<(" "+c+" ").indexOf(d);case "|=":return c===d||c.substr(0,d.length+1)===d+"-"}}},CHILD:function(a,b,d,c){if("nth"===a){var e=W++;return function(a){var i,b=0,f=a;if(1===d&&0===c)return!0;if((i=a.parentNode)&&(i[n]!==e||!a.sizset)){for(f=i.firstChild;f&&!(1===f.nodeType&&(f.sizset=++b,f===a));f=f.nextSibling);
i[n]=e}a=a.sizset-c;return 0===d?0===a:0===a%d&&0<=a/d}}return function(b){var d=b;switch(a){case "only":case "first":for(;d=d.previousSibling;)if(1===d.nodeType)return!1;if("first"===a)return!0;d=b;case "last":for(;d=d.nextSibling;)if(1===d.nodeType)return!1;return!0}}},PSEUDO:function(a,b,d,c){var e=k.pseudos[a]||k.pseudos[a.toLowerCase()];e||m.error("unsupported pseudo: "+a);return!e.sizzleFilter?e:e(b,d,c)}},pseudos:{not:A(function(a,b,d){var c=aa(a.replace(M,"$1"),b,d);return function(a){return!c(a)}}),
enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},parent:function(a){return!k.pseudos.empty(a)},empty:function(a){for(var b,a=a.firstChild;a;){if("@"<a.nodeName||3===(b=a.nodeType)||4===b)return!1;a=a.nextSibling}return!0},contains:A(function(a){return function(b){return-1<
(b.textContent||b.innerText||V(b)).indexOf(a)}}),has:A(function(a){return function(b){return 0<m(a,b).length}}),header:function(a){return ha.test(a.nodeName)},text:function(a){var b,d;return"input"===a.nodeName.toLowerCase()&&"text"===(b=a.type)&&(null==(d=a.getAttribute("type"))||d.toLowerCase()===b)},radio:z("radio"),checkbox:z("checkbox"),file:z("file"),password:z("password"),image:z("image"),submit:Z("submit"),reset:Z("reset"),button:function(a){var b=a.nodeName.toLowerCase();return"input"===
b&&"button"===a.type||"button"===b},input:function(a){return ia.test(a.nodeName)},focus:function(a){var b=a.ownerDocument;return a===b.activeElement&&(!b.hasFocus||b.hasFocus())&&!(!a.type&&!a.href)},active:function(a){return a===a.ownerDocument.activeElement}},setFilters:{first:function(a,b,d){return d?a.slice(1):[a[0]]},last:function(a,b,d){b=a.pop();return d?a:[b]},even:function(a,b,d){for(var b=[],d=d?1:0,c=a.length;d<c;d+=2)b.push(a[d]);return b},odd:function(a,b,d){for(var b=[],d=d?0:1,c=a.length;d<
c;d+=2)b.push(a[d]);return b},lt:function(a,b,d){return d?a.slice(+b):a.slice(0,+b)},gt:function(a,b,d){return d?a.slice(0,+b+1):a.slice(+b+1)},eq:function(a,b,d){b=a.splice(+b,1);return d?a:b}}};k.setFilters.nth=k.setFilters.eq;k.filters=k.pseudos;ma||(k.attrHandle={href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}});ka&&(k.order.push("NAME"),k.find.NAME=function(a,b){if("undefined"!==typeof b.getElementsByName)return b.getElementsByName(a)});$&&(k.order.splice(1,
0,"CLASS"),k.find.CLASS=function(a,b,d){if("undefined"!==typeof b.getElementsByClassName&&!d)return b.getElementsByClassName(a)});try{C.call(u.childNodes,0)[0].nodeType}catch(ra){C=function(a){for(var b,d=[];b=this[a];a++)d.push(b);return d}}var T=m.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1},na=m.contains=u.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:u.contains?function(a,b){var d=9===a.nodeType?a.documentElement:
a,c=b.parentNode;return a===c||!(!c||!(1===c.nodeType&&d.contains&&d.contains(c)))}:function(a,b){for(;b=b.parentNode;)if(b===a)return!0;return!1},V=m.getText=function(a){var b,d="",c=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)d+=V(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[c];c++)d+=V(b);return d};m.attr=function(a,b){var d;(d=T(a))||(b=b.toLowerCase());return k.attrHandle[b]?k.attrHandle[b](a):
ja||d?a.getAttribute(b):(d=a.getAttributeNode(b))?"boolean"===typeof a[b]?a[b]?b:null:d.specified?d.value:null:null};m.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};[0,0].sort(function(){return X=0});u.compareDocumentPosition?g=function(a,b){return a===b?(I=!0,0):(!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition:a.compareDocumentPosition(b)&4)?-1:1}:(g=function(a,b){if(a===b)return I=!0,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-
b.sourceIndex;var d,c,e=[],f=[];d=a.parentNode;c=b.parentNode;var g=d;if(d===c)return h(a,b);if(d){if(!c)return 1}else return-1;for(;g;)e.unshift(g),g=g.parentNode;for(g=c;g;)f.unshift(g),g=g.parentNode;d=e.length;c=f.length;for(g=0;g<d&&g<c;g++)if(e[g]!==f[g])return h(e[g],f[g]);return g===d?h(a,f[g],-1):h(e[g],b,1)},h=function(a,b,d){if(a===b)return d;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});m.uniqueSort=function(a){var b,d=1;if(g&&(I=X,a.sort(g),I))for(;b=a[d];d++)b===
a[d-1]&&a.splice(d--,1);return a};var aa=m.compile=function(e,b,d){var f,g,h=R[e];if(h&&h.context===b)return h;var j,s=[];f=0;for(var l=Y.exec(e),p=!l.pop()&&!l.pop(),r=p&&e.match(N)||[""],v=k.preFilter,y=k.filter,q=!d&&b!==t;null!=(j=r[f])&&p;f++){s.push(h=[]);for(q&&(j=" "+j);j;){p=!1;if(l=J.exec(j))j=j.slice(l[0].length),p=h.push({part:l.pop().replace(M," "),captures:l});for(g in y)if((l=D[g].exec(j))&&(!v[g]||(l=v[g](l,b,d))))j=j.slice(l.shift().length),p=h.push({part:g,captures:l});if(!p)break}}p||
m.error(e);for(g=0;f=s[g];g++){h=s;j=g;l=b;p=d;v=r=void 0;for(y=0;r=f[y];y++)k.relative[r.part]?v=a(v,k.relative[r.part],l):(r.captures.push(l,p),v=c(v,k.filter[r.part].apply(null,r.captures)));h[j]=v}h=R[e]=function(a,b){for(var d,c=0;d=s[c];c++)if(d(a,b))return!0;return!1};h.context=b;h.runs=h.dirruns=0;S.push(e);S.length>k.cacheLength&&delete R[S.shift()];return h};m.matches=function(a,b){return m(a,null,null,b)};m.matchesSelector=function(a,b){return 0<m(b,null,null,[a]).length};var U=function(a,
b,d,c,g){var a=a.replace(M,"$1"),h,j,s,l,p,r,v;l=a.match(N);s=a.match(ea);p=b.nodeType;if(D.POS.test(a)){h=a;var y,u,n,w,t;s=0;p=l.length;r=D.POS;v=RegExp("^"+r.source+"(?![\\x20\\t\\r\\n\\f])","i");for(var H=function(){for(var a=1,b=arguments.length-2;a<b;a++)arguments[a]===G&&(y[a]=G)};s<p;s++){r.exec("");h=l[s];g=[];a=0;for(n=c;y=r.exec(h);)if(t=r.lastIndex=y.index+y[0].length,t>a){j=h.slice(a,y.index);a=t;w=[b];J.test(j)&&(n&&(w=n),n=c);if(u=ga.test(j))j=j.slice(0,-5).replace(J,"$&*");1<y.length&&
y[0].replace(v,H);t=j;var z=y[1],B=y[2],x=void 0,A=k.setFilters[z.toLowerCase()];A||m.error(z);if(t||!(x=n))q(t||"*",w,x=[],n);n=0<x.length?A(x,B,u):[]}n?(g=g.concat(n),(j=h.slice(a))&&")"!==j?J.test(j)?q(j,g,d,c):m(j,b,d,c?c.concat(n):n):E.apply(d,g)):m(h,b,d,c)}return 1===p?d:m.uniqueSort(d)}if(c)h=C.call(c,0);else if(l&&1===l.length){if(1<s.length&&9===p&&!g&&(l=D.ID.exec(s[0]))){b=k.find.ID(l[1],b,g)[0];if(!b)return d;a=a.slice(s.shift().length)}j=(l=O.exec(s[0]))&&!l.index&&b.parentNode||b;v=
s.pop();p=v.split(":not")[0];c=0;for(s=k.order.length;c<s;c++)if(r=k.order[c],l=D[r].exec(p))if(h=k.find[r]((l[1]||"").replace(F,""),j,g),null!=h){p===v&&((a=a.slice(0,a.length-v.length)+p.replace(D[r],""))||E.apply(d,C.call(h,0)));break}}if(a){j=aa(a,b,g);f=j.dirruns++;null==h&&(h=k.find.TAG("*",O.test(a)&&b.parentNode||b));for(c=0;l=h[c];c++)e=j.runs++,j(l,b)&&d.push(l)}return d};if(t.querySelectorAll){var ba,oa=U,pa=/'|\\/g,qa=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,w=[],K=[":active"],
L=u.matchesSelector||u.mozMatchesSelector||u.webkitMatchesSelector||u.oMatchesSelector||u.msMatchesSelector;B(function(a){a.innerHTML="<select><option selected></option></select>";a.querySelectorAll("[selected]").length||w.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||w.push(":checked")});B(function(a){a.innerHTML="<p test=''></p>";a.querySelectorAll("[test^='']").length&&w.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");
a.innerHTML="<input type='hidden'>";a.querySelectorAll(":enabled").length||w.push(":enabled",":disabled")});w=w.length&&RegExp(w.join("|"));U=function(a,b,c,e,f){if(!e&&!f&&(!w||!w.test(a)))if(9===b.nodeType)try{return E.apply(c,C.call(b.querySelectorAll(a),0)),c}catch(g){}else if(1===b.nodeType&&"object"!==b.nodeName.toLowerCase()){var h=b.getAttribute("id"),k=h||n,l=O.test(a)&&b.parentNode||b;h?k=k.replace(pa,"\\$&"):b.setAttribute("id",k);try{return E.apply(c,C.call(l.querySelectorAll(a.replace(N,
"[id='"+k+"'] $&")),0)),c}catch(m){}finally{h||b.removeAttribute("id")}}return oa(a,b,c,e,f)};L&&(B(function(a){ba=L.call(a,"div");try{L.call(a,"[test!='']:sizzle"),K.push(k.match.PSEUDO.source,k.match.POS.source,"!=")}catch(b){}}),K=RegExp(K.join("|")),m.matchesSelector=function(a,b){b=b.replace(qa,"='$1']");if(!T(a)&&!K.test(b)&&(!w||!w.test(b)))try{var c=L.call(a,b);if(c||ba||a.document&&11!==a.document.nodeType)return c}catch(e){}return 0<m(b,null,null,[a]).length})}"function"===typeof define&&
define.amd?define(function(){return m}):x.Sizzle=m})(window);
ReadSpeaker.lib.RSLib=function(){var x={core_pnum:function(){return/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source},rposition:function(){return/^(top|right|bottom|left)$/},rmargin:function(){return/^margin/},rnumsplit:function(){return RegExp("^("+this.core_pnum+")(.*)$","i")},rnumnonpx:function(){return RegExp("^("+this.core_pnum+")(?!px)[a-z%]+$","i")},rmsPrefix:function(){return/^-ms-/},rdashAlpha:function(){return/-([\da-z])/gi}},G={_formatRet:function(a){return a.length?1==a.length?a[0]:a:[]},
get:function(a){return"object"==typeof a?a:document.getElementById(a)||this._formatRet(window.Sizzle(a))},findIn:function(a,c){"string"===typeof a&&(a=this.get(a));return this._formatRet(window.Sizzle(c,a))},closest:function(a,c){var e=!1,f=null,g=null,f=null,h=a;"string"===typeof a&&(h=this.get(a));f=$rs.findIn(h.parentNode,c);if(f===h)return h;for(;!e&&h!==document.body;){g=h.parentNode;f=h.parentNode.parentNode;if((f=$rs.findIn(f,c))&&f===g){e=!0;break}else if(f&&$rs.isArray(f)&&f.length)for(var h=
0,q=f.length;h<q;h++)if(f[h]&&f[h]===g){e=!0;f=f[h];break}h=g}if(e)return f},getAttr:function(a,c){"string"===typeof a&&(a=this.get(a));if("style"===c)return a.style.cssText.toLowerCase()||void 0;if(a.attrName)return a.attrName;if(a.getAttribute)return a.getAttribute(c)},setAttr:function(a,c,e){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var f=0,g=a.length;f<g;f++)"style"===c?a[f].style.cssText=e:a[f].attrName?a[f].attrName=e:a[f].setAttribute&&a[f].setAttribute(c,e);return e},
regEvent:function(a,c,e){var f,g;"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var h=0,x=a.length;h<x;h++)g=a[h].window?document.documentElement:a[h],f=this.getAttr(g,"data-rsevent-id")||"rs_"+Math.round(1E6*Math.random()),this.setAttr(g,"data-rsevent-id",f),q.push(f,c,e),(!q.store[f]||!(q.store[f][c]&&1<q.store[f][c].length))&&_addEvent(a[h],c,q.dispatch)},unregEvent:function(a,c,e){var f;"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var g=0,h=a.length;g<h;g++)f=
a[g].window?document.documentElement:a[g],f=this.getAttr(f,"data-rsevent-id"),e?(f=q.pop(f,c,e))||_removeEvent(a[g],c,q.dispatch):_removeEvent(a[g],c,q.dispatch)},fireEvent:function(){return!1},width:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"width")},height:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"height")},innerWidth:function(a){"string"===typeof a&&(a=this.get(a));var c=parseFloat(_getCss(a,"border-left-width"))+parseFloat(_getCss(a,"border-right-width"));
return _getSize(a,"width")-c},innerHeight:function(a){"string"===typeof a&&(a=this.get(a));var c=parseFloat(_getCss(a,"border-top-width"))+parseFloat(_getCss(a,"border-bottom-width"));return _getSize(a,"height")-c},outerWidth:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var e=c?parseFloat(_getCss(a,"margin-left"))+parseFloat(_getCss(a,"margin-right")):0;return _getSize(a,"width")+e}return null},outerHeight:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var e=
c?parseFloat(_getCss(a,"margin-top"))+parseFloat(_getCss(a,"margin-bottom")):0;return _getSize(a,"height")+e}return null},offsetParent:function(a){"string"===typeof a&&(a=this.get(a));for(var c=/absolute|relative|fixed/i;a!==document.body&&!(a=a.parentNode,a.style&&c.test(_getCss(a,"position"))););return a||document.body},offset:function(a){"string"===typeof a&&(a=this.get(a));var c=document.body,e=document.defaultView||window,f=document.documentElement,g=document.createElement("div");g.style.paddingLeft=
g.style.width="1px";c.appendChild(g);var h=2==g.offsetWidth;c.removeChild(g);g=a.getBoundingClientRect();return{top:g.top+(e.pageYOffset||h&&f.scrollTop||c.scrollTop)-(f.clientTop||c.clientTop||0),left:g.left+(e.pageXOffset||h&&f.scrollLeft||c.scrollLeft)-(f.clientLeft||c.clientLeft||0)}},absOffset:function(a){return this.offset(a)},position:function(a){"string"===typeof a&&this.get(a);return!1},scrollLeft:function(a,c){"string"===typeof a&&(a=this.get(a));return _scrollXY("scrollLeft","pageXOffset",
a,c)},scrollTop:function(a,c){"string"===typeof a&&(a=this.get(a));return _scrollXY("scrollTop","pageYOffset",a,c)},addClass:function(a,c){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var e,f=0,g=a.length;f<g;f++)e=_trim(a[f].className+" "+c).replace(/ {2,}/g," ").split(" "),a[f].className=e.join(" ")},removeClass:function(a,c){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var e,f=0,g=a.length;f<g;f++){e=_trim(c).replace(/ {2,}/g," ");newClassName=_trim(a[f].className);
this.isArray(e)||(e=e.split(" "));for(var h=0,q=e.length;h<q;h++)newClassName=newClassName.replace(RegExp("\\b"+e[h]+"\\b","gi"),"");a[f].className=_trim(newClassName).replace(/ {2,}/g," ")}},hasClass:function(a,c){"string"===typeof a&&(a=this.get(a));if(!a||this.isArray(a)&&!a.length)return!1;for(var e=a.className.split(" "),f=0,g=e.length;f<g;f++)if(e[f]==c)return!0;return!1},css:function(a,c,e){"string"===typeof a&&(a=this.get(a));if("object"==typeof c||e){var f={};"string"===typeof c?f[_camelCase(c)]=
e:f=c;for(var g in f)f.hasOwnProperty(g)&&(a.style[_camelCase(g)]=f[g])}else return _getCss(a,_camelCase(c))},addStyleRule:function(a,c,e){e="string"==typeof e?document.styleSheets[e]||document.getElementById(e):e;e.addRule?e.addRule(a,c):e.sheet.insertRule&&e.sheet.insertRule(a+" {"+c+"}",e.sheet.cssRules.length)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},rsid:function(a){if(""==this.getAttr(a,"data-rsid")||void 0==this.getAttr(a,"data-rsid")){var c=ReadSpeaker.rsidCount++;
this.setAttr(a,"data-rsid",c)}return this.getAttr(a,"data-rsid")},detach:function(a){return a.parentNode.removeChild(a)},convertEvent:function(a,c){var a=a||window.event,e=new ReadSpeaker.lib.Facade.RSEvent;e.pageX=a.pageX||a.clientX+$rs.scrollLeft(document);e.pageY=a.pageY||a.clientY+$rs.scrollTop(document);e.screenX=a.screenX;e.screenY=a.screenY;e.clientX=a.clientX;e.clientY=a.clientY;e.target=a.currentTarget||c;e.type=a.type;e.keyCode=a.keyCode;e.targetTouches=a.targetTouches;e.originalEvent=a;
return e},clone:function(a,c,e){return a.cloneNode(e||!1)},camel:function(a){return _camelCase(a)},remove:function(){return jQuery(elm).remove()},replaceWith:function(a,c){return _formatRet(jQuery(a).replaceWith(c))},focus:function(a,c){void 0!==c?this.focusIn(a,c):(a=this.get(a),this.isArray(a)&&0<a.length?a[0].focus?a[0].focus():a[0].setActive&&a[0].setActive():a.focus?a.focus():a.setActive&&a.setActive())},focusIn:function(a,c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var e=0;e<a.length;e++)void 0!==
c&&_addEvent(a[e],"focus",c);else void 0!==c&&_addEvent(a,"focus",c)},focusOut:function(a,c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var e=0;e<a.length;e++)void 0!==c&&_addEvent(a[e],"blur",c);else void 0!==c&&_addEvent(a,"blur",c)}},q=null;_getWindow=function(a){return null!=a&&a==a.window?a:9===a.nodeType?a.defaultView||a.parentWindow:!1};_camelCase=function(a){return a.replace(x.rmsPrefix(),"ms-").replace(x.rdashAlpha(),_fcamelCase)};_fcamelCase=function(a,c){return(c+"").toUpperCase()};
_trim=function(a){return a.replace(/^ +/,"").replace(/ +$/,"")};_getCss=window.getComputedStyle?function(a,c){return window.getComputedStyle(a,null)[_camelCase(c)]||!1}:function(a,c){var e,f,g=a.currentStyle&&a.currentStyle[c],h=a.style;null==g&&(h&&h[c])&&(g=h[c]);if(x.rnumnonpx().test(g)&&!x.rposition().test(c)){e=h.left;if(f=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;h.left="fontSize"===c?"1em":g;g=h.pixelLeft+"px";h.left=e;f&&(a.runtimeStyle.left=f)}return""===
g?"auto":g};_getSize=function(a,c){var e="width"==c?"Width":"Height";if(a!==window&&a!==document){e=a["offset"+e];if(isNaN(e)||!e)e=_getCss(a,c);isNaN(e);return parseInt(e)}if(a===window)return window["inner"+e]||document.documentElement["client"+e]||document.body["client"+e];if(a===document)return document.body["client"+e]};_scrollXY=function(a,c,e,f){var g=/X/.test(c),h=_getWindow(e);if(void 0===f)return h?c in h?h[c]:h.document.documentElement[a]:e[a];h?h.scrollTo(!g?f:$rs.scrollLeft(h),g?f:$rs.scrollTop(h)):
e[a]=f};_addEvent=document.addEventListener?function(a,c,e){a.addEventListener&&a.addEventListener(c,e,!1)}:function(a,c,e){a.attachEvent&&a.attachEvent("on"+c,function(c){e(c,a)})};_removeEvent=document.removeEventListener?function(a,c,e){a.removeEventListener&&a.removeEventListener(c,e,!1)}:function(a,c,e){a.detachEvent&&a.detachEvent("on"+c,e)};return{meta:{revision:"1316"},init:function(){window.Sizzle?(q=ReadSpeaker.lib.Facade.eq,ReadSpeaker.lib.Facade.adapterInit(G),ReadSpeaker.log("[rspkr.l.RSLib] Initialized.")):
ReadSpeaker.log("[rspkr.l.RSLib] Error, Sizzle unavailable.",3)}}}();
