ReadSpeaker.Common=function(){var e={onInit:[],onCoreLoaded:[],onModsLoaded:[],onAfterModsLoaded:[],onConfigLoaded:[],onConfigSetup:[],onDOMReady:[],onReady:[],onSelectedText:[],onDeselectedText:[],onSettingsInitialized:[],onSettingsChanged:[],onSettingsLoaded:[],onFocusIn:[],onFocusOut:[],onUIInitialized:[],onUIBeforePlay:[],onUIAfterPlay:[],onUIPause:[],onUISliderMove:[],onUIStop:[],onUIShowPlayer:[],onUIClosePlayer:[],onAPIPlay:[],onAPIPause:[],onAPIStop:[],onAPIVolumeUp:[],onAPIVolumeDown:[],
onAPIMute:[],onAPIFastForward:[],onAPIRewind:[],onAPISetVolume:[],onAPISetProgress:[],onAPIGetProgress:[],onAPIInitAdapter:[],onAPIReleaseAdapter:[],onAPIReloadAdapter:[],onBeforeSyncInit:[],onAfterSyncInit:[],onBeforeSync:[],onAfterSync:[]},l={speed:function(a,b){var c=parseInt(b||rspkr.pub.Config.item("general.defaultSpeedValue")||100);switch(a){case "slow":return c-25;case "medium":return c;case "fast":return c+25;default:return c}}},f={audioLink:null,params:{},postContent:"",postLink:null,saveLink:null,
selectedHTML:"",selectedText:"",selectedRange:null,sync:"wordsent",syncLink:null,browser:{name:"",flashVersion:"",version:"",OS:"",html5AudioFormat:"",html5Support:!1,html5Priority:!1,syncContainer:""},setParams:function(a){rspkr.log("[rspkr.c.data.setParams] "+a);if("string"==typeof a){this.params=[];for(var b="",c="",b="",a=a.split("?")[1].split(/[;&]/),d=0;d<a.length;d++)if((b=a[d].split("="))&&2==b.length)c=unescape(b[0]),b=unescape(b[1]),b=b.replace(/\+/g," "),"url"==c&&(0==b.length&&(b=document.location.href),
b=encodeURIComponent(b)),this.params[c]=b;this.params.rsjs_ver=rspkr.getVersion();this.params.synccontainer=this.browser.syncContainer}},setDefaultValues:function(){rspkr.log("[rspkr.c.data.setDefaultValues] Called!");rspkr.Common.data.selectedHTML="";rspkr.Common.data.saveLink=null},setPostContent:function(a){if("string"==typeof a)if("textsel"===a)this.postContent=i.encode(this.selectedHTML);else{var a=[],b="";if(rspkr.Common.data.params.hasOwnProperty("readclass")){var c=rspkr.Common.data.params.readclass,
a=$rs.get("."+c);$rs.isArray(a)||(a=[a]);for(var d in a)b+='<div class="'+c+'">'+a[d].innerHTML+"</div>"}else if(rspkr.Common.data.params.hasOwnProperty("readid"))for(d in a=rspkr.Common.data.params.readid.split(","),a)b+='<div id="'+a[d]+'">'+$rs.get(a[d]).innerHTML+"</div>";this.postContent=i.encode(b)}},setSelectedText:function(a){this.selectedText="";var b=void 0,c=void 0;window.getSelection?(c=window.getSelection(),c.isCollapsed||(c.getRangeAt?b=c.getRangeAt(0):(b=document.createRange(),b.setStart(c.anchorNode,
c.anchorOffset),b.setEnd(c.focusNode,c.focusOffset)),b?(DOM=b.cloneContents(),object=document.createElement("div"),object.appendChild(DOM.cloneNode(!0)),this.selectedText=object.innerHTML):this.selectedText=c),this.selectedRange=b):document.selection?(c=document.selection,this.selectedText=(b=c.createRange())&&b.htmlText&&b.text&&0<b.text.length?b.htmlText:b&&b.text?b.text:"",this.selectedRange=b.duplicate()):document.getSelection&&(this.selectedText=document.getSelection());window.getSelection?0<
this.selectedText.length&&window.getSelection().getRangeAt(0)&&0<window.getSelection().getRangeAt(0).toString().length?g("onSelectedText",window,[a]):(this.selectedText="",g("onDeselectedText",window,["empty"])):0<this.selectedText.length?g("onSelectedText",window,[a]):g("onDeselectedText",window,["empty"]);rspkr.log("[rspkr.c.setSelectedText] Selected text length is "+this.selectedText.length)},getParam:function(a){return this.params&&this.params[a]&&void 0!==this.params[a]?this.params[a]:null},
getParams:function(){return this.params},getPostContent:function(){return this.postContent},getRestoreContent:function(){return this.restoreContent},getSelectedText:function(){return this.selectedText},getAudioLink:function(a){this.audioLink=null;var b={},c;for(c in this.params)this.params.hasOwnProperty(c)&&(b[c]=this.params[c]);for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.speed=l.speed(rspkr.Common.Settings.get("hlspeed"),b.speed?b.speed:void 0);0<this.selectedText.length||0<this.selectedHTML.length?
(0<this.selectedText.length&&rspkr.HL.clientMarkup.preProcess.init(),b.sync="user",b.syncalignuser=rspkr.st.get("hl"),this.setPostContent("textsel"),this.audioLink=k.issuePost(b)):!0===rspkr.pub.Config.item("general.usePost")?(b.sync="wordsent",this.setPostContent("nosel"),this.audioLink=k.issuePost(b)):(b.sync="wordsent",this.audioLink=m(b));rspkr.log("[rspkr.c.data.getAudioLink] Audio link: "+this.audioLink);return this.audioLink},getSaveData:function(a){rspkr.log("[rspkr.c.data.getSaveData]");
if(!this.saveLink){var b={},c={audioformat:"mp3"};if("iOS"!==this.browser.OS&&"dialog"===(a||"link"))c.save="1";for(var d in this.params)this.params.hasOwnProperty(d)&&(b[d]=this.params[d]);for(d in c)c.hasOwnProperty(d)&&(b[d]=c[d]);a=rspkr.pub.Config.item("settings.hlspeed");b.speed=l.speed(a);0<this.selectedHTML.length?(this.setPostContent("textsel"),this.saveLink=k.issuePost(b)):!0===rspkr.pub.Config.item("general.usePost")?(this.setPostContent("nosel"),this.saveLink=k.issuePost(b)):this.saveLink=
m(b)}return this.saveLink}},m=function(a){var b=rspkr.pub.Config.item("general.protocol")+"//"+rspkr.pub.Config.item("general.subdomain")+"."+rspkr.pub.Config.item("general.domain")+"/cgi-bin/"+rspkr.pub.Config.item("general.rsent")+"?",c;for(c in a)a.hasOwnProperty(c)&&(b="customerid"==c?b+(c+"="+a[c]):b+("&"+c+"="+a[c]));return b},g=function(a,b,c){if(e[a]){c=c||[];if(!e[a].length)return rspkr.log("[rspkr.c] Dispatched event: "+a+" - no handlers to call.",2),!0;rspkr.log("[rspkr.c] Dispatching event: "+
a,1);for(var d in e[a])if("function"==typeof e[a][d])try{"__self__"===b&&(b=e[a][d]),e[a][d].apply(b,c)}catch(h){this.isok=!1}else if("object"==typeof e[a][d])try{var j=e[a][d];j.func.apply(j.context||window,j.params||c)}catch(f){this.isok=!1}}else rspkr.log("[rspkr.c] Undefined event: "+a,3)},k={issuePost:function(a){rspkr.log("[rspkr.c] Using POST");document.getElementById("ReadSpeakerPostIframe")||this.createIframe();var b=Math.random(),a=this.createForm(a),c=rspkr.pub.Config.item("general.protocol")+
"//"+rspkr.pub.Config.item("general.subdomain")+"."+rspkr.pub.Config.item("general.domain")+"/enterprise/iframeproxy.php?rsent="+rspkr.pub.Config.item("general.rsent")+"&version="+rspkr.pub.Config.item("general.proxyVersion");a.action=c+"&randid="+b;var d=document.createElement("input");1<f.getSelectedText().length?d.setAttribute("name","selectedhtml_base64"):d.setAttribute("name","html_base64");d.setAttribute("value",f.getPostContent());a.appendChild(d);document.body.appendChild(a);a.submit();document.body.removeChild(a);
return c+"&listen=1&randid="+b},createForm:function(a){var b,c=document.createElement("form");c.target="ReadSpeakerPostIframe";c.method="post";for(var d in a)b=document.createElement("input"),b.setAttribute("name",d),"url"===d?b.setAttribute("value",decodeURIComponent(a[d])):b.setAttribute("value",a[d]),c.appendChild(b);b=document.createElement("input");b.setAttribute("name","output");b.setAttribute("value","audiolink");c.appendChild(b);return c},createIframe:function(){var a=null;if(document.selection)try{a=
document.createElement('<iframe name="ReadSpeakerPostIframe">')}catch(b){a=document.createElement("iframe")}else a=document.createElement("iframe");a.setAttribute("name","ReadSpeakerPostIframe");a.setAttribute("id","ReadSpeakerPostIframe");a.setAttribute("style","display: none; position: absolute;");a.style.display="none";var c=document.getElementsByTagName("body"),d=null;0<c.length&&(d=c.item(0));d&&d.appendChild(a)},removeIframe:function(){document.getElementById("ReadSpeakerPostIframe")&&document.body.removeChild(document.getElementById("ReadSpeakerPostIframe"))}},
i={encode:function(a){newdata=encodeURIComponent(a);for(var b=0,c=0,a=[];b<newdata.length;b++)37!=newdata.charCodeAt(b)?a[c]=newdata.charCodeAt(b):(a[c]=parseInt("0x"+newdata.charAt(b+1)+""+newdata.charAt(b+2)),b+=2),c++;b=a.length;parseInt((b+2)/3);for(var c=new String,d=parseInt(b/3),h,j=b-3*d,b=0;b<3*d;b+=3)h=this.chars(a[b]>>2),c+=h,h=this.chars((a[b]&3)<<4|a[b+1]>>4),c+=h,h=this.chars((a[b+1]&15)<<2|a[b+2]>>6),c+=h,h=this.chars(a[b+2]&63),c+=h;1==j&&(c+=this.chars(a[b]>>2),c+=this.chars((a[b]&
3)<<4),c+="==");2==j&&(c+=this.chars(a[b]>>2),c+=this.chars((a[b]&3)<<4|a[b+1]>>4),c+=this.chars((a[b+1]&15)<<2),c+="=");return c},decode:function(a){for(var b="",c="",d=0,h=0,j="",f=a.length;d<f;)if(-1!=this.value(a[d])){for(var j=a.substring(d,d+4),e=h=0;4>e;e++)"="==j[e]&&h++;for(e=0;e<3-h;e++){0==e?c=this.value(j[0])<<2|(this.value(j[1])&48)>>4:1==e?c=(this.value(j[1])&15)<<4|(this.value(j[2])&60)>>2:2==e&&(c=(this.value(j[2])&3)<<6|this.value(j[3]));var g=c.toString(16);1==g.length&&(g="0"+g);
b+="%"+g}d+=4}else d++;return decodeURIComponent(b)},value:function(a){a=a.charCodeAt(0);return 65<=a&&90>=a?a-65:97<=a&&122>=a?a-97+26:48<=a&&57>=a?a-48+52:43==a?62:47==a?63:-1},chars:function(a){return 26>a?String.fromCharCode(a+65):52>a?String.fromCharCode(a+97-26):62>a?String.fromCharCode(a+48-52):62==a?"+":63==a?"/":String.fromCharCode(0)}};return{meta:{revision:"1316"},init:function(){g("onInit",window);e.onInit=[];e.onUIShowPlayer.push(rspkr.Common.data.setDefaultValues)},addEvent:function(a,
b){e[a].push(b)},base64:i,buildReadSpeakerCall:function(a){return m(a)},data:f,Detect:{init:function(){rspkr.log("[rspkr.c.Detect] Initialized!");var a=navigator.userAgent;f.browser.name=this.searchString(this.dataBrowser)||"Unknown";f.browser.version=this.searchVersion(a)||this.searchVersion(navigator.appVersion)||"Unknown";f.browser.OS=this.searchString(this.dataOS)||"Unknown";"Android"==f.browser.OS&&"Unknown"==f.browser.version?f.browser.version=20:"Windows"===f.browser.OS&&-1!==a.indexOf("Windows NT 6.0")&&
(this.browserSettings.Firefox.html5Priority=!1);f.browser.flashVersion=this.getFlashVersion();rspkr.log("[rspkr.c.Detect.init] Flash version: "+f.browser.flashVersion);f.browser.syncContainer="default"!==rspkr.pub.Config.item("general.syncContainer")?rspkr.pub.Config.item("general.syncContainer"):"rs:span";a=f.browser.name;this.browserSettings.hasOwnProperty(f.browser.name)||(this.browserSettings[a]={});"default"===rspkr.pub.Config.item("general.syncContainer")&&this.browserSettings[a].hasOwnProperty("syncContainer")&&
(f.browser.syncContainer=this.browserSettings[a].syncContainer);this.browserSettings[a].hasOwnProperty("html5Support")?f.browser.html5Support=this.browserSettings[a].html5Support:document.createElement("audio").canPlayType&&(f.browser.html5Support=!0);if(!0===f.browser.html5Support){var b=document.createElement("audio"),c=!1,d=!1;b.canPlayType&&(c=!!b.canPlayType&&""!=b.canPlayType("audio/mpeg"),d=!!b.canPlayType&&""!=b.canPlayType('audio/ogg; codecs="vorbis"'));!0===c?f.browser.html5AudioFormat=
"mp3":!0===d?f.browser.html5AudioFormat="ogg":f.browser.html5Support=!1;f.browser.html5Priority=this.browserSettings[a].hasOwnProperty("html5Priority")?this.browserSettings[a].priority:!0}},browserSettings:{Explorer:{syncContainer:"font"},Firefox:{},Opera:{html5Support:!1,priority:!1}},getFlashVersion:function(){try{if(document.selection){try{var a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{a.AllowScriptAccess="always"}catch(b){return"6,0,0"}}catch(c){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,
",").match(/^,?(.+),?$/)[1]}try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(d){}}catch(h){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(e){}}return"0,0,0"},
searchString:function(a){for(var b=0;b<a.length;b++){var c=a[b].string,d=a[b].prop;this.versionSearchString=a[b].versionSearch||a[b].identity;if(c){if(-1!=c.indexOf(a[b].subString))return a[b].identity}else if(d)return a[b].identity}},searchVersion:function(a){var b=a.indexOf(this.versionSearchString);if(-1!=b)return parseFloat(a.substring(b+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chromium",identity:"Chromium"},{string:navigator.userAgent,subString:"Chrome",
identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera",versionSearch:"Version"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},
{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",
identity:"iOS"},{string:navigator.userAgent,subString:"iPad",identity:"iOS"},{string:navigator.userAgent,subString:"Android",identity:"Android"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]},dispatchEvent:function(a,b,c){g(a,b,c)},post:k,cookie:{create:function(a,b,c,d,h){c=c||rspkr.pub.Config.item("general.cookieLifetime");d=d||rspkr.pub.Config.item("general.cookiePath");h=h||rspkr.pub.Config.item("general.cookieDomain");if(c){var e=new Date;e.setTime(e.getTime()+c);c="; expires="+
e.toGMTString()}else c="";return document.cookie=a+"="+b+c+(d?"; path="+d:"")+(h?"; domain="+h:"")},read:function(a){for(var a=a+"=",b=decodeURIComponent(document.cookie).split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}},readKey:function(a,b){var c=this.read(a),d;if(c)for(var c=c.split("&"),e=0,f=c.length;e<f;e++)if(d=c[e].split("="),d[0]==b)return d[1]},readKeyAll:function(a){var a=this.read(a),b={},
c;if(a){for(var a=a.split("&"),d=0,e=a.length;d<e;d++)c=a[d].split("="),b[c[0]]=c[1];return b}},createSub:function(a,b,c,d,e){if("object"!==typeof b)this.create(a,b.toString(),c,d,e);else{var f=[],g;for(g in b)f.push(g+"="+b[g]);return this.create(a,f.join("&"),c,d,e)}},updateKey:function(a,b,c,d,e,f){for(var c=c.toString(),g=decodeURIComponent(this.read(a)),k,i={},l=!1,g=!g||"null"==g||"undefined"==g?[]:-1<g.indexOf("=")&&-1==g.indexOf("&")?[g]:g.split("&"),m=0,n=g.length;m<n;m++)k=g[m].split("="),
k[0]==b&&(k[1]=c,l=!0),k.length&&k[1].length&&(i[k[0]]=k[1]);!l&&c.length&&(i[b]=c);return this.createSub(a,i,d,e,f)},erase:function(a,b,c){this.create(a,"",-1,b,c)}},css:{getStylesheet:function(a){var b;if(!(b=document.styleSheets[a]||document.getElementById(a)))b=document.createElement("style"),b.type="text/css",b.id=b.name=a,(document.getElementsByTagName("head")[0]||document.body).appendChild(b),!b.addRule&&!b.sheet&&(b=document.styleSheets[a]);return b.sheet||b},rsSheet:function(a){this.rules=
a.rules||a.cssRules;this.del=function(a,c){a.deleteRule?a.deleteRule(c):a.removeRule&&a.removeRule(c)};this.ins=function(a,c,d){$rs.isArray(d)||(d=[d]);if(a.insertRule&&a.cssRules)a.insertRule(c+" {"+d.join(";")+";}",a.cssRules.length);else if(a.addRule)for(var e=0,g=d.length;e<g;e++)a.addRule(c,d[e])}},setRule:function(a,b,c){var a=this.getStylesheet(a),d=new this.rsSheet(a);d.ins(a,b,"string"==typeof c?c.split(";"):c);return d.length},removeRule:function(a,b){var c=this.getStylesheet(a),d=new this.rsSheet(c),
e=[];if(d.rules){for(var g=0,f=d.rules.length;g<f;g++)d.rules[g].selectorText==b&&e.push(g);for(;e.length;)d.del(c,e.pop());return e}return d},replaceRule:function(a,b,c){this.removeRule(a,b);this.setRule(a,b,c)}},converter:l,findFirstRSButton:function(a){for(var a=a||document.body,a=a.getElementsByTagName("a"),b=0,c=a.length;b<c;b++)if($rs.hasClass(a[b],"rsbtn_play")||a[b].href&&-1!==a[b].href.indexOf(rspkr.pub.Config.item("general.domain")+"/cgi-bin/"+rspkr.pub.Config.item("general.rsent"))||a[b].href&&
/customerid=/i.test(a[b].href)&&/lang=/i.test(a[b].href)&&/(readid|readclass)/i.test(a[b].href))return a[b];return!1},decodeEntities:function(a){var b=document.createElement("p");b.innerHTML=a;return b.textContent||b.innerText}}}();rspkr.lib||(rspkr.lib={});
rspkr.lib.Facade=function(e){var l=[{name:"jquery",minver:"1.4",check:function(){return"function"==typeof jQuery&&parseFloat(jQuery.fn.jquery)>=parseFloat(this.minver)?!0:!1}}],f="",m={store:[],push:function(e,f,i){this.store[e]||(this.store[e]=[]);this.store[e][f]||(this.store[e][f]=[]);this.store[e][f].push(i);return this.store.length},pop:function(e,f,i){var a;if(this.store[e]&&this.store[e][f]){a=this.store[e][f];for(var b=a.length-1;-1<b;b--)a[b]==i&&this.store[e][f].splice(b,1);return this.store[e][f].length}return 0},
dispatch:function(e,f){var i=$rs.convertEvent(e,f),a=$rs.getAttr(i.target.window?document.documentElement:i.target,"data-rsevent-id");if(a){for(var b=!0,a=m.store[a][i.type],c=0,d=a.length;c<d;c++)"function"==typeof a[c]&&(a[c].apply(i.target,[i])||(b=!1));return b}}};return{init:function(){for(idx in l)if(l[idx]&&l[idx].check&&l[idx].check()){f=l[idx].name;break}f.length||(f="RSLib")},currentLib:function(){return f},eq:m,adapterInit:function(f){e.$rs=f}}}(window);ReadSpeaker.lib.Facade.RSEvent=function(){};
ReadSpeaker.modmap={products:{all:[["Common.Settings","text/javascript",["Common.Settings"]]],custom:function(){var e=[];e.push(["Custom","text/javascript"]);return e},dr:function(){var e=[];e.push(["DocReader.AutoAdd","text/javascript"]);return e},exp:function(){var e=this.all;e.push(["PlayerAPI","text/javascript"]);return e},embhl:function(){var e=this.exp();e.push(["PlayerAPI","text/javascript"],["HL","text/javascript"],["ui","text/javascript",["ui","ui.Lightbox","ui.Slider"]]);return e}}};
