<?php
/**
 * @file
 * Declare api for the feature list of standard profile.
 */

/**
 * Implements hook_feature_set_api().
 */
function multisite_drupal_features_set_standard_feature_set_api() {
  return array('version' => '1.0');
}

/**
 * Implements hook_permission().
 */
function multisite_drupal_features_set_standard_permission() {
  $featuresets = feature_set_get_featuresets();
  $permissions = array();
  if (!empty($featuresets)) {
    foreach ($featuresets as $featureset => $details) {
      $permissions['enable feature set ' . $featureset] = array(
        'title' => t('Administer feature set @feature', array('@featureset', $featureset)),
        'description' => t('Enable and disable feature set @feature as defined by the feature set module. Note that this functionality is similar and is a subset of the functionality allowed by administer modules so be aware that users with this permission will be able to enable, disable, and uninstall modules defined via the feature set module', array('@feature' => $featureset)),
      );
    }
  }
  return $permissions;
}
