<?php

/**
 * @file
 * Install the feature social bookmark.
 */

/**
 * Implements hook_uninstall().
 */
function social_bookmark_uninstall() {
  $global_var = _social_bookmark_get_global_var();
  // Delete all the custom global variables.
  foreach ($global_var as $var) {
    variable_del($var);
  }
}

/**
 * Implements hook_enable().
 */
function social_bookmark_enable() {
  // Set the default value.
  variable_set('social_bookmark_user_value_socialbookmark', 'EU_Commission');

  // Add block in context.
  global $theme_key;

  if ($theme_key == 'ec_resp') {
    multisite_drupal_toolbox_add_block_context('site_wide', 'social_bookmark-social-bookmark', 'social_bookmark', 'social-bookmark', 'content_bottom');
  }
  else {
    multisite_drupal_toolbox_add_block_context('site_wide', 'social_bookmark-social-bookmark', 'social_bookmark', 'social-bookmark', 'tools_bottom');
  }
  // Activation message.
  drupal_set_message(t('Social bookmark feature is now active on your site.'));
  drupal_set_message(t('Social bookmark block has been created.'));
  $link = l(t('admin/config/socialbookmark/social_bookmark'), 'admin/config/socialbookmark/social_bookmark', array('attributes' => array('target' => '_blank')));
  drupal_set_message(t('Social bookmark widget configuration: !link', array('!link' => $link)));
  drupal_set_message(t('Social bar block has been created.'));
  $link = l(t('admin/config/socialbookmark/social_bar'), 'admin/config/socialbookmark/social_bar', array('attributes' => array('target' => '_blank')));
  drupal_set_message(t('Social bar widget configuration: !link', array('!link' => $link)));
}

/**
 * Implements hook_disable().
 */
function social_bookmark_disable() {
  // Remove block in context.
  multisite_drupal_toolbox_remove_block_context('site_wide', 'social-bookmark');
  // Deactivation message.
  drupal_set_message(t('Social bookmark  feature is now disabled on your site.'));
}

/**
 * Returns all custom global variables.
 */
function _social_bookmark_get_global_var() {
  $global_var = array(
    'social_bookmark_type_socialbookmark',
    'social_bookmark_icon_size_socialbookmark',
    'social_bookmark_override_socialbookmark',
    'social_bookmark_label_socialbookmark',
    'social_bookmark_display_socialbookmark',
    'social_bookmark_least_socialbookmark',
    'social_bookmark_orientation_socialbookmark',
    'social_bookmark_statistics_socialbookmark',
    'social_bookmark_language_socialbookmark',
    'social_bookmark_language_selector_socialbookmark',
    'social_bookmark_data_table',
    'social_bookmark_type_socialbar',
    'social_bookmark_icon_size_socialbar',
    'social_bookmark_text_socialbar',
    'social_bookmark_statistics_socialbar',
    'social_bookmark_language_socialbar',
    'social_bookmark_language_selector_socialbar',
    'social_bookmark_user_value_socialbookmark',
  );

  return $global_var;
}

/**
 * Set twitter custom user parameter.
 */
function social_bookmark_update_7310() {
  variable_set('social_bookmark_user_value_socialbookmark', 'EU_Commission');
}
