<?php
/**
 * @file
 * Code for the wiki feature.
 */

include_once 'wiki_core.features.inc';

/**
 * Implements hook_token_info().
 */
function wiki_core_token_info() {
  $info['types']['Breadcrumb_wiki'] = array(
    'name' => 'Breadcrumb_wiki',
    'description' => 'Tokens related to Breadcrumb.',
  );
  $info['tokens']['Breadcrumb_wiki']["wiki_title"] = array(
    'name' => t("wiki Breadcrumb title"),
    'description' => t("The Breadcrumb title of the wiki."),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function wiki_core_tokens($type, $tokens, $data = array(), $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);
  // Tokens for e_libray_core Breadcrumb.
  if ($type == 'Breadcrumb_wiki') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'wiki_title':
          $replacements[$original] = t("wiki");
          break;
      }
    }
  }
  return $replacements;
}
