<?php
/**
 * Implements hook_node_access().
 */
function multisite_drupal_access_node_access($node, $op, $account) {
  if (is_string($node)) {
    return NODE_ACCESS_IGNORE;
  }
  
  if($node->type == "community") {
    return NODE_ACCESS_ALLOW; // allow any users to view a community node
  }
 
  $group = og_get_entity_groups('node', $node);
  if(count($group) > 0) {
    $cm_rid = get_og_rid('community_manager');
    $user_og_roles = og_get_user_roles(current($group));
    if(in_array($cm_rid, $user_og_roles))  {
	  return NODE_ACCESS_ALLOW; // allow all permissions for a community manager in his groups
	}
  }
 
  return NODE_ACCESS_IGNORE;
}


/**
 * Implements hook_node_grants().
 */
function multisite_drupal_access_node_grants($account, $op) {
  $grants = array();
  
  // allow any users to view private communities in the communities directory
  if(arg(0) == 'communities_directory') {
    if ($op == 'view' && $groups = og_get_all_group()) {
      foreach ($groups as $gid => $value) {
        $grants[OG_ACCESS_AUTHENTICATED_REALM][] = $gid;
      }
    }
  }
  return $grants;
}


/*
function multisite_drupal_access_node_access_records($node) {
	$grants = array();
	
	print "<br>node_access_record<br>";
	return $grants;
}
*/


